### ISSUE TITLE
Plot is constrained below image on Schedule - Poster view

### ISSUE THREAD

**Issue by labrys** [SickRage/sickrage-issues#102]
When expanding the plot on the poster view of the schedule, it only spans the width of the poster image, and not the full width of the container.

**Comment by OmgImAlexis** [comment]
I can't see this being fixed without redoing all of the CSS and HTML for that view since we still use tables for it instead of divs. :disappointed:

**Comment by miigotu** [comment]
Fixed in develop as soon as #276 is merged
