### ISSUE TITLE
Add 2160p/4k as download option

### ISSUE THREAD

**Issue by Rouzax** [SickRage/sickrage-issues#110]
With the apparent downloads now of true 4k content and the relase groups having cracked HDCP
https://torrentfreak.com/pirates-can-now-rip-4k-content-from-netflix-and-amazon-151127/ 
It may be time to add that to SickRage.
![image](https://cloud.githubusercontent.com/assets/4103090/11474298/9245a3fc-9777-11e5-9567-dda3d50fdf41.png)

**Comment by duramato** [comment]
By the way ,there have been 2k rips before that article :P 
https://torrentfreak.com/first-netflix-4k-content-leaks-to-torrent-sites-150828/

**Comment by OmgImAlexis** [comment]
Either way this should be on [feathub](feathub.com/SickRage/SickRage) and we really should add this soon.

**Comment by duramato** [comment]
And request it here http://feathub.com/SickRage/SickRage

**Comment by duramato** [comment]
@OmgImAlexis lol

**Comment by Rouzax** [comment]
To be honest Feathub is really nice but there is so much garbage in there that good and valid ideas are snowed down to page 11 were normally nobody will look to up vote.

**Comment by OmgImAlexis** [comment]
@fernandog has said this before.. :disappointed: 

Keep in mind the devs go through there every so often and DO add stuff that isn't too hard to add so this will probably be added soon.

**Comment by fernandog** [comment]
We need to add one random feature in SR page like the update available div so users can vote up/down. We already talked about this in IRC

**Comment by Rouzax** [comment]
@fernandog :+1:
