### ISSUE TITLE
SR Failing to process shows, show searcher eventually dies

### ISSUE THREAD

**Issue by Zipties** [SickRage/sickrage-issues#111]
SR Version:	BRANCH: (master) / COMMIT: (1e8a1a0ede9b386f25e243c1c4e3814a520bd325) 
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
Windows Server 2008 R2

I am having an issue where when I enable the automatic post processor I get thousands of failure to process errors, and eventually the show searcher stops working and I start missing shows. Trying to manually search for a show will put it in queued status permanently. Looking at the queue list in server status shows it to be empty.

Deleting the cache folder and cache.db will fix this issue temporarily, but the only long term solution is to disable the post processor scanning and use scripts.  

The warnings seem to come from the fact that a current file exists, with a larger file size. Take this one for example

2015-11-30 09:29:19 POSTPROCESSER :: [D:\Downloads\Complete\TV2\The.Walking.Dead.S06E06.1080p.WEB-DL.DD5.1.H.264-Cyphanix.mkv : Processing failed: ]

That file is 1.6GB and the existing one is 8.7GB. The 8.7GB existing file is an HDTV file BUT SR has it marked as Web-DL, so it wont replace it with the new Web-DL copy. This seems to happen to a lot of shows and episodes (downloads HDTV, but marks as Web-DL, then downloads Web-Dl and can't use it). If I manually set the show to HDTV, it will then process the new file properly.

There is also an issue where an episode will download over and over, despite the fact it is logged as downloaded at the quality it is attempting to download. 

Game of Thrones Season 5 Episode 10 is the worst offender. it tries to snatch it every few days (Although my logs have so much going on I only have one occurrence to show)

Here is a shared folder of all my logs, and screenshots of the issues.

https://drive.google.com/folderview?id=0B2ggqo902tNhNUZfVjQ0ZUNfcWM&usp=sharing

**Comment by medariox** [comment]
You seem to have multiple issues here. Let's start with the first problem.
What is the original name of the release that got tagged WEB-DL instead of HDTV? We need to know why it has been incorrectly tagged, before making any further assumptions.

**Comment by fernandog** [comment]
I think the downloaded the 1080p.HDTV that is 8gb than snatched the 1080p.webdl

**Comment by Zipties** [comment]
The.Walking.Dead.S06E06.1080p.HDTV.X264-DIMENSION

**Comment by medariox** [comment]
@Zipties 
SR tagged it as 1080p HDTV with that name for me, not sure how you get it as WEB-DL?
@fernandog 
I think the problem here is that SR tagged HDTV as WEB-DL and the new WEB-DL version doesn't get replaced. I can't reproduce the incorrect tagging tho.

**Comment by Zipties** [comment]
for example 2015-11-30 10:59:12 POSTPROCESSER :: [D:\Downloads\Complete\TV2\Anger.Management.S02E82.720p.BluRay.x264-BRAVERY\anger.management.s02e82.720p.bluray.x264-bravery.mkv : Processing failed: ]

it is a 1GB 720p Bluray file and the existing is a 1080p blueray at 1.45GB correctly tagged as 1080p Bluray.

**Comment by miigotu** [comment]
Because the 720p shouldnt have ever been downloaded there, and has never been processed. Clear out your PP folder of files that SR either didn't DL or doesnt know about anymore (because of recreating DB?)

**Comment by Zipties** [comment]
I never download anything to those folders that SR didn't download, and I haven't cleared the DB. I setup a new PP folder and will monitor it. I have done once before and the problem came back after the folder got to a decent size.

**Comment by labrys** [comment]
@Zipties its something we are looking at, along with a lot of other improvements.

**Comment by Zipties** [comment]
I went back and looked at torrent time stamps. It looks like SR snatched the 720p release and it was a very slow download that took days. Before it finished it found a 1080p release which downloaded in a few minutes. A day or two later the 720p release finished and started spawning errors.

**Comment by labrys** [comment]
@Zipties that's good information to have, appreciate the update.

**Comment by Zipties** [comment]
So, it looks like SR has stopped searching for shows again. All shows that aired last night are marked as "missed" If I manually search for it I don't see any updates made to the log, and it gets put in queue status for an indefinite amount of time.


If I restart SR then the show searcher starts working for a little while. You should be able to see in the logs where this happens. 


Here are the latest logs. 

https://drive.google.com/folderview?id=0B2ggqo902tNhM3FNVXc2cmM3OGM&usp=sharing

**Comment by Zipties** [comment]
@labrys I tried disabling the post processor as it has been a  common theme in  this issue where the show searcher stops working, but the issue persists. I am not at all sure what the root cause is now, but the show searcher stops working about every 24 hours and requires a SR restart.

**Comment by labrys** [comment]
@Zipties what commit are you currently on, I will set mine up to the same commit and see if I can duplicate it.  Also I noticed you are using NZBs, can you confirm that you are not hitting your API limits, as that might cause it to no longer search until your limit resets.

**Comment by Zipties** [comment]
@labrys 


SR Version:	BRANCH: (master) / COMMIT: (81aa99c0b4bd39fbf333decd6e4f6c155d9401ef) 

it has been happening for about 6 months. What causes the show searcher to die seems to change, but that is always the end result. 

I use both torrents and NZBs. All my NZB indexers have unlimited API calls, and being the issue is resolved from a SR restart totally rules out an a tracker issue.

**Comment by labrys** [comment]
Yeah, I had to confirm the limits weren't an issue though due to the 24 hours and we have had other issues that were API limit related.

**Comment by labrys** [comment]
@Zipties  I noticed your logs show you are constantly post processing and there are a lot of items that failed to process.  First of all try increasing your Auto Post Processing Frequency (Gears --> Post Processing Menu --> Post-Processing Tab --> Auto Post-Processing Frequency).  If it's set at 10 minutes try increasing it to 40.  It also wouldn't hurt to manually process the files that are failing to process so that SickRage doesn't waste its effort trying them repeatedly.

**Comment by Zipties** [comment]
@labrys which logs are you looking at? The latest I posted have a fresh post process directory and everything is processing fine. Furthermore I turned automated post processing off completely several days ago for troubleshooting.

**Comment by labrys** [comment]
The latest logs you posted were on the 1st of December and the first half of the logs was all PP warnings.

**Comment by labrys** [comment]
And I'm an idiot for not seeing the comment about you turning off PP.

**Comment by Zipties** [comment]
Usually turning it off resolved the issue, so why it is continuing is a mystery to me now.

**Comment by miigotu** [comment]
try disabling all notifiers.

**Comment by Zipties** [comment]
Roger, disabled the only two I had setup (Plex, and Trak)

**Comment by fernandog** [comment]
@miigotu @Thraxis shouldn't we add a try:except for all calls to notifiers?

here we don't have for example:
https://github.com/SickRage/SickRage/blob/develop/sickbeard/show_queue.py#L466

also here :
https://github.com/SickRage/SickRage/blob/develop/sickbeard/tv.py#L1048
https://github.com/SickRage/SickRage/blob/develop/sickbeard/tv.py#L1457
https://github.com/SickRage/SickRage/blob/develop/sickbeard/search.py#L179
https://github.com/SickRage/SickRage/blob/develop/sickbeard/search.py#L184
https://github.com/SickRage/SickRage/blob/develop/sickbeard/webserve.py#L1658
https://github.com/SickRage/SickRage/blob/develop/sickbeard/webserve.py#L1669
https://github.com/SickRage/SickRage/blob/develop/sickbeard/webserve.py#L1779
https://github.com/SickRage/SickRage/blob/develop/sickbeard/webserve.py#L1790

most of them are trakt. and we know trakt have some issues with servers. others may have timeout issues.

Don't know if we should add a try:except in the notifiers itself or outside it as we do in other parts of the code.

**Comment by miigotu** [comment]
Thats why Im waiting to see if it fixes his problem.

**Comment by Quiptix** [comment]
With all respect, my issue #185 was somewhat hijacked by others making the team angry. I hope that the functionality decribed in #185 will be considered.

**Comment by BRTPOB** [comment]
I don't want to be a pile-on, but one of the issues that Zipties is running into, and the issue that Quiptix saw is happening to me, but it's 100%. If I have something set to accepted for 720p (Web-DL or HDTV) and preferred is 1080p (Web-DL or HDTV) it'll fail to replace the older file as the quality is better.
