### ISSUE TITLE
Listen on IPv6 breaks IPv4 connectivity.

### ISSUE THREAD

**Issue by labrys** [SickRage/sickrage-issues#114]
Enabling Listen on IPv6 under `Gear -> General Configuration -> Interface` causes IPv4 connectivity to break.  Access by any of the following fail:
* `[hostname]:[port]` 
* `[IPv4]:[port]`
* `127.0.0.1:[port]`

However the following work as advertised:
* `localhost:[port]`
* `[[IPv6]]:[port]`

**Comment by Thraxis** [comment]
Looks like this was reported on Feathub a couple months ago as a feature request not a bug.

http://feathub.com/SickRage/SickRage/+133

**Comment by Arcanemagus** [comment]
In this day support for IPv6 should be a requirement, not a feature...

**Comment by duramato** [comment]
@Arcanemagus Most home connections still only have a ipv4 adress , but yes it should be a requirement 
https://www.google.com/intl/en/ipv6/statistics.html#tab=per-country-ipv6-adoption&tab=per-country-ipv6-adoption ,not bad Portugal :P

**Comment by labrys** [comment]
@Thraxis Not supporting IPv6 might be considered a feature.  Enabling IPv6 breaking all IPv4 access is definitely a bug, particularly since this can be enabled remotely via the web interface and potential making the service unreachable if no IPv6 route to host exists.
@duramato Which is exactly why enabling an IPv6 feature shouldn't completely kill an IPv4 implementation

**Comment by labrys** [comment]
Fixed in develop with SickRage/SickRage#477
