### ISSUE TITLE
CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version. Error: AssertionError('Commit hash wrong length: 4 hash: None',)

### ISSUE THREAD

**Issue by OIK2** [SickRage/sickrage-issues#115]
SR Version:	BRANCH: (master) / COMMIT: (d294e9faf48d45051a50d4e2cf3a0252c28d5b17) on Win7 Python 2.78

CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version. Error: AssertionError('Commit hash wrong length: 4 hash: None',)

I get the above error each time I attempt to update.

**Comment by OmgImAlexis** [comment]
@miigotu

**Comment by miigotu** [comment]
Its having a problem connecting to github

**Comment by fastdriver** [comment]
I am also getting a warning 

2015-12-01 16:27:16 Thread-26 :: Unable to contact github, can't check for update: UnknownObjectException()

**Comment by miigotu** [comment]
That happens when you have reached the github api limit, or when your github username/password is wrong in config

**Comment by FelipeSQ** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@c575707408313497ee391e761f0164fe574a3c6f
Link to Log: https://gist.github.com/8a8d800f671c051f0760
### ERROR
```
CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version. Error: AssertionError('Commit hash wrong length: 4 hash: None',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by pazyarev** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: ****
Commit: SickRage/SickRage@
Link to Log: https://gist.github.com/c391eb38266ea8d1ecc6
### ERROR
```
CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version. Error: AssertionError('Commit hash wrong length: 4 hash: None',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by pazyarev** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: ****
Commit: SickRage/SickRage@
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version. Error: AssertionError('Commit hash wrong length: 4 hash: None',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
