### ISSUE TITLE
Scene numbering change not saved

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#117]
@OmgImAlexis 
Ep 4, I enter for example: 4, hit enter. it changes to 1x4.
Ep 5, I enter for example: 5, hit enter. it changes to 1x5
Refresh page. Scene change wasn't changed

Also I got:
![image](https://cloud.githubusercontent.com/assets/2620870/11501550/36cdb56e-981c-11e5-97aa-b28a0930248d.png)

**Comment by fernandog** [comment]
@OmgImAlexis any clue?

@duramato confirmed?

**Comment by OmgImAlexis** [comment]
Sounds like the page isn't loading core.js and instead of loading either the old js file or something else..

What page is this on?

**Comment by fernandog** [comment]
displayShow

**Comment by OmgImAlexis** [comment]
For the `$` issue, looks like you've got a cache issue. I have to look into the other issue still.

![screen shot 2015-12-04 at 12 47 03 pm](https://cloud.githubusercontent.com/assets/6525926/11580251/285d44a2-9a85-11e5-87b1-68a4dbd82ea3.png)

**Comment by fernandog** [comment]
@supergonkas can you confirm please?

**Comment by medariox** [comment]
I can confirm it only happens when you let the JS auto-complete the numbering. For example, if I write 4x8 it is saved, but if I only write 8 and it auto-completes to 4x8, the scene numbering is not saved.

**Comment by fernandog** [comment]
That is it!! Thanks

**Comment by OmgImAlexis** [comment]
@fernandog can you open a new issue then, this is the reason bugs are meant to be in separate issues.

**Comment by fernandog** [comment]
The main issue is scene numbet no saving. Why open another? I though JS was related

**Comment by duramato** [comment]
@fernandog Working fine here maybe adblock/noscript?

**Comment by fernandog** [comment]
Does it work when you let SR auto complete the number. Type 4. SR changes to 1x4.

**Comment by duramato** [comment]
yes

**Comment by fernandog** [comment]
no adblock. tried again. still not working

**Comment by fernandog** [comment]
@duramato are you using Chrome? still not working for me and @medariox

**Comment by duramato** [comment]
yes chrome win and also works on chrome for android

**Comment by fernandog** [comment]
@OmgImAlexis can you check this too please?

**Comment by labrys** [comment]
@duramato I couldn't get it to work on Chrome or Firefox (Win 10x64)

**Comment by fernandog** [comment]
@medariox can you check this please??

**Comment by fernandog** [comment]
@OmgImAlexis can you reply please?

**Comment by OmgImAlexis** [comment]
@fernandog it's currently the holidays and I've got a bunch of other stuff going on like most people do. I probably won't be fully back till some time in January and tagging me won't make me be avaliable any quicker.

**Comment by p0psicles** [comment]
I'll have a look at it tomorrow

**Comment by p0psicles** [comment]
Okay, please check my PR.
https://github.com/SickRage/SickRage/pull/806

This was not a bug, more of a feature request. The regex used to parse the user input always asumes you enter it like 1x4. Only providing the episode, resulted in sending an empty ajax request.

If you want this functionality, accept the PR. If not dismiss it. But either way, I think this issue can be closed.

**Comment by fernandog** [comment]
@p0psicles it detects the season that your are changing the number. so it you type 1 in season 4, it changes to 4x1.  but it doesn't save when you type only the episode number
