### ISSUE TITLE
Only find subtitle searching manually on Legendastv provider..

### ISSUE THREAD

**Issue by felipesalomao** [SickRage/sickrage-issues#120]
Hi, i dont know what is happening.. Dont know if is legendas.tv provider issue or sickrage issue..

It search for subtitles everyday each 1 hour.. i see on log that it really try find subtitles, but it never download subtitles..  today for example, GOTHAM S02E11 subtitle was published on legendas.tv 20:48.. 
In log i see that it tried look for new subtitles 20:58, 21:58, 22:58 and not downloaded anything.. Only legendas.tv provider is marked.. 

Here have 2 hours difference, so if in log show 22:00, correct time  (my local time is 20:00)..
````
2015-12-02 01:00:27 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-12-02 00:58:47 INFO     FINDSUBTITLES :: Checking for subtitles
2015-12-02 00:58:44 INFO     CHECKVERSION :: Checking for updates using GIT

2015-12-02 00:00:27 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-12-01 23:58:46 INFO     FINDSUBTITLES :: Checking for subtitles
2015-12-01 23:58:44 INFO     CHECKVERSION :: Checking for updates using GIT

2015-12-01 22:58:50 INFO     FINDPROPERS :: Beginning the search for new propers
2015-12-01 22:58:45 INFO     FINDSUBTITLES :: Checking for subtitles
2015-12-01 22:58:43 INFO     CHECKVERSION :: Checking for updates using GIT
````

Then, as it not downloaded i opened Gotham page in sickrage and clicked on CC button, it found subtitle and downloaded it in 5 seconds..

So legendas.tv provider looks work great, i think.. problem is that it isnt downloading automatically and also Log is too much poor for subtitle module, it only says Checking for subtitles, nothing more, it does not say if found, if not, why.. So its hard discovery whats them problem..

Could you help @ratoaq2 @fernandog @medariox ? 

If need anything, just ask me ! Thanks

**Comment by labrys** [comment]
@felipesalomao Could you provide us some information such as OS, branch, commit, etc.. It would be much appreciated.

**Comment by felipesalomao** [comment]
BRANCH: (master)
COMMIT: (1e8a1a0ede9b386f25e243c1c4e3814a520bd325) 
Running on Qnap ARM: 219P II

I dont know if have this error on all subtitle providers or if is only with legendas.tv.. It seems work great as if i click on CC it download subtitle without problem.. Log have too little details.. Not say anything about if it downloaded subtitle or not, if not, why.. @ratoaq2 developed this legendastv subtitle provider..

**Comment by labrys** [comment]
Logging is one of many things we are looking to improve.  Do you have `Enable Debug` check marked under `Gears -> General Configuration -> Advanced Configuration`?  This may help narrow down the issue.

**Comment by felipesalomao** [comment]
Enabled option.. Now new wait release any new subtitle that is pending.. Tomorrow should be published.. As I understood, log will more complete.. Will update post

**Comment by duramato** [comment]
@felipesalomao  do you have your login set for legendas.tv ? As just yesterday my SR downloaded sub's from there..

**Comment by fernandog** [comment]
mine is working too. Code is the same for manual or auto.
@felipesalomao maybe legendatv was down or timeouted - as we know it's commno.

**Comment by felipesalomao** [comment]
@duramato 
Yes, I have user and pass configured.. When I click on CC it download automatically the subtitle from Legendas.tv

@fernandog 
I suspect that is not downtime issue, because I waited 3 hours (3 subtitle scans) before click to on CC, I also opened Legendas.tv website several times and no problem in those 3 hours.. 
Last scan was 00:58, I made manual scan clicking on CC button just 1 minute after and it found..

**Comment by felipesalomao** [comment]
Interesting..
I have supergirl tv show, subtitle was published 01:56, it downloaded automatically, but only downloaded 10:59, so it needed 10 hours or 10 automatic scans to find subtitle.. @duramato could you check time between subtitle published and how many time to download it automatically?!

**Comment by fernandog** [comment]
You need to check if the subtitle for that release was published in the first upload or not. What qualit/resolution are you looking for?

**Comment by duramato** [comment]
@felipesalomao It just downloaded one a few hours ago, for gotham which is a few months old http://legendas.tv/download/552da3a34d2b1/Gotham/Gotham_S01E19_HDTV_x264_LOL_AFG_FUM_DIMENSION_YFN
You do need to keep in mind you need to be looking for your release which in my case was ```Gotham.S01E19.720p.HDTV.X264-DIMENSION```

**Comment by fernandog** [comment]
@felipesalomao we have the same local time:

```
2015-12-02 02:50:05 DEBUG    FINDSUBTITLES :: Setting permissions for /media/SAMSUNG/media/downloaded/series/Supergirl.S01E06.1080p.HDTV.X264-DIMENSION.pt-BR.srt to 644 as parent directory has 755
2015-12-02 02:50:05 DEBUG    FINDSUBTITLES :: Found subtitle for /media/SAMSUNG/media/downloaded/series/Supergirl.S01E06.1080p.HDTV.X264-DIMENSION.mkv in legendastv provider with language pob
```

**Comment by felipesalomao** [comment]
@duramato are you from brazil too?
Your search is perfect.. Supergirl Subtitle was published 01:56, your sickrage downloaded it 02:50 (next subtitle scan, yours scan 01:50, 02:50, 03:50...), 
About release as can see it is not problem because my sickrage is configured to aways download killer or dimension releases, and aways Legendas.tv publish subtitle for these releases (the make about 4 releases at same time and killers or dimension is aways included on this first subtitle). As can see, @duramato have same local time than me, same tv show and it downloaded in less than 1 hour (first scan), mine downloaded after 10 hours (10th scan). 

Now time correct time is 19:55, but in log it show 21:55, maybe this error in time could affect some way search? Maybe I need fix that? How?

Today it downloaded automatically the flash s02e08, subtitle was published 14:42, it only downloaded 18:59.. So it downloaded after 5 scans.. It's really strange..

See configuration and logs
![image](https://cloud.githubusercontent.com/assets/2954256/11545352/168e9062-992e-11e5-8d1d-b5191c845027.png)
![image](https://cloud.githubusercontent.com/assets/2954256/11545353/16c23a48-992e-11e5-8832-2308aa5d01bd.png)
![image](https://cloud.githubusercontent.com/assets/2954256/11545458/9a43a15e-992e-11e5-8fb7-e19c09a5fec8.jpeg)
![image](https://cloud.githubusercontent.com/assets/2954256/11545459/9aef121e-992e-11e5-8625-579bcd0183a3.jpeg)

**Comment by fernandog** [comment]
@felipesalomao your are confusing names lol

Check the bottom of any SR page. See if the time is correct.

If is not you need to adjust your OS time and/or locale.

**Comment by felipesalomao** [comment]
@fernandog confusing witch names? As I told it's wrong.. There is 2 hours difference.. See photo..
![image](https://cloud.githubusercontent.com/assets/2954256/11546044/fb955efe-9931-11e5-9f9c-b8c7e99de30c.png)

How can I change time on Qnap? There is some code that I can change using winscp? Do you think that this time difference could be the problem? Strange that difference is 2 hours and some subtitles delay 10 hours, another 5 hours..

**Comment by fernandog** [comment]
@felipesalomao you tagged @duramato but that log was mine

**Comment by fernandog** [comment]
@neoatomic how to change timezone in qnap? know a easy way?

**Comment by neoatomic** [comment]
No idea. Dont own a Qnap. :(

**Comment by felipesalomao** [comment]
I changed time myself.. Was easy, used qnap gui under general settings > time
Then after restarted SR.. 
Do you think that's problem could be caused by difference in time?

**Comment by felipesalomao** [comment]
![image](https://cloud.githubusercontent.com/assets/2954256/11546426/5822c63c-9934-11e5-8f5f-79a519b073c7.png)

**Comment by fernandog** [comment]
wrong time changes when SR snatches episodes.
when find subtitle again send full logs with debug enabled.
use gist or pastebin to post log please.

**Comment by felipesalomao** [comment]
Now need wait some new TV release and subtitle publish.. Tomorrow should have arrow tb show subtitle available, will check if it will download automatically on first scan.. Time already is correct.. What you mean with gist or pastebin? Debug already is enabled.. Could I get full log file by ssh.. This is ok? Thank you a lot for help

**Comment by fernandog** [comment]
when it download subs, open gist.github.com, paste fulllog from SR there and send us the link
entendeu? lol

**Comment by felipesalomao** [comment]
Entendi :) ops, understood. Will make it once download subs..

**Comment by felipesalomao** [comment]
Hi @fernandog, made test today again, but now with correct time and with debug log activated
 
Had same problem, found something interesting on code:

2015-12-03 17:25:38 DEBUG    FINDSUBTITLES :: Episode already has all needed subtitles, skipping  episode 4x8 of show Arrow

But at this moment, Arrow S04E08 had not subtitle downloaded.. Not understood why skipped..

Subtitle was releasead at 17:10 as you can see:
http://legendas.tv/download/566093b5b27c7/Arrow/Arrow_S04E08_HDTV_x264_LOL_FUM_DIMENSION_RARBG

It tried find check new subtitles on those times:
17:25:38 (automatic scan after upgrade sickrage to commit a89bf7fbf5dd0762d1d6ac98cd624219697a6a54): FINDSUBTITLES :: Episode already has all needed subtitles, skipping  episode 4x8 of show Arrow

17:54:12 (automatic scan): FINDSUBTITLES :: Episode already has all needed subtitles, skipping  episode 4x8 of show Arrow
18:54:12 (automatic scan): FINDSUBTITLES :: Episode already has all needed subtitles, skipping  episode 4x8 of show Arrow

19:51:52 (here i clicked on download all subtitles in arrow SR page, then it downloaded successfuly)

Here is full log as you requested:
https://gist.github.com/felipesalomao/608488579244fc96bd9f

One last observation, i dont know why (some update maybe), but CC button to download subtitle by epesode manually on Tv Show SR page disapear.. Now only option is click: "download subtitles" (All)..

If any additional information needed, just let me know.. Thank you !

**Comment by fernandog** [comment]
@felipesalomao do you have the setting "ignore embedded subtitles" disabled?

**Comment by felipesalomao** [comment]
@fernandog Yes, its disabled..

**Comment by fernandog** [comment]
So enabled it! Lol
Most mkv has embebded subs

**Comment by felipesalomao** [comment]
Obvious.. Hehehe SR is thinking that i already have subtitle (most mkv that i see has only english sub).. So it ignore and does not download.. But how could explain download it 5 hours after, 10 hours after, i am not 100% right if the problem is this..  @fernandog, By the way, your idea to improve subtitle accuracy is awesome.. Hope all works great.. Are you from brazil too ?!

**Comment by fernandog** [comment]
Yes. Join us at IRC # sickrage-issues
Download an IRC app for phone.
Better to talk

**Comment by felipesalomao** [comment]
Not use IRC more than 10 years.. RS.. Added here.. It's great have mobile client for irc..

**Comment by felipesalomao** [comment]
Hi, i really should have big problem on SR..  Now i am on latest commit: 81aa99c0b4bd39fbf333decd6e4f6c155d9401ef, Master

As asked by @fernandog, i enabled option: "Ignore subtitles embedded inside video file?" in subtitle settings to avoid make SR think that embed mkv subtitles (english) think that subtitle already was downloaded..

Today was publied at 00:57 on Legendas.tv subtitle for Z nation S02e13, and again it not downlloaded on first scan, in log i can see: 
2015-12-06 02:28:40 DEBUG    FINDSUBTITLES :: Episode already has all needed subtitles, skipping  episode 2x13 of show Z Nation
But it not had subtitle for that show yet..

Worse than this, is that on manage missed subtitles, it appears that all epsodes of all my tv shows are missing subtitles, but they are not.. 99,9% have SRT subtitle with same name of mkv video in folder.. I tried click on buttons: "Re-scan Files" and "Force Full Search" on SR TV Show page..But it continues show it as missed subtitles on manage missed subtitles, one observation is that on tv show SR page, it show subtitles as downloaded (checked).. It does not make any sense..

Here is all images that i show it..
![subtitle problem](https://cloud.githubusercontent.com/assets/2954256/11611786/b5d840ec-9bc6-11e5-9701-9c644a4914fb.png)


And also full debug log when it tried seach for subtitle (after i updated to the latest commit on 02:27 06/12/15..
https://gist.github.com/felipesalomao/5b26783f705f9063521b

Please, somebody can help solve it ? I really dont know whats going on..

**Comment by felipesalomao** [comment]
As commented by @fernandog, this bugs only occurs if lang code isn't added to subtitle name.. I tested here and CC button is on again, and also after rescan, manage missed subtitles don't show subtitle that i already have.. Not tested yet if it can download on first scan new subtitles.. 
But problem is that most of players don't recognize subtitle when language code is added to subtitle name, including LG Smart TV (i use it).. So need solve bug when lang isn't added to subtitle name..
About 1 week ago, this problem not was happening..

If any test needed, just ask me..

**Comment by medariox** [comment]
@felipesalomao 
Please try the develop branch and let me know if you still have problems.

**Comment by felipesalomao** [comment]
Yes, I am on develop branch since yesterday.. Latest test I made was about
12 hours ago.. Only with lang in subtitle, that I hadn't problems..

Em terça-feira, 8 de dezembro de 2015, Dario <notifications@github.com>
escreveu:

**Comment by medariox** [comment]
@felipesalomao 
Update to latest develop version and check if the 'Missing Subtitles Management' works as it should now.

**Comment by felipesalomao** [comment]
Ok.. Will update and post here..

Em terça-feira, 8 de dezembro de 2015, Dario <notifications@github.com>
escreveu:

**Comment by felipesalomao** [comment]
Yes.. now it worked fine on develop branch wihout lang.. Missed subtitles disapear after rescan and CC button is working again.. Dont know if it download subtitles on first scan, will need some time to test it (next subtitle download should be tomorrow i think)..

Now another issue, that i think is related to legendas.tv subtitle provider.. 
Min score to download now is 132 points, thats fine, becase we sure that only will download 100% compatible sub, but for example SR snatched and downloaded this file:
Z.Nation.S02E13.720p.HDTV.x264-KILLERS.mkv

then when i tried click on CC to download this subtitle, wasnt possible because this:
Z.Nation.S02E13.720p.HDTV.x264-KILLERS[ettv]

They are exactly same, but SR thinked that Release is wrong because [ettv] and give only 115 points, result = not downloaded
See log: 
2015-12-08 02:44:07 DEBUG    FINDSUBTITLES :: [legendastv] Subtitle score for Z.Nation.S02E13.720p.HDTV.x264-KILLERS[ettv].srt (5663a433b7223) is: 115 (min=132)

We need way to ignore [ettv], for example if release of mkv is killers and subtitle is killers(sodijsjsijd203), no problem, if have killers inside release, just match.. then would avoid this..

I know that subtitler should release with correct name, but it occurs too many times.. We need adapt code to avoid errors.. 

Thank you for support !  If need, i could open another issue for this another problem..

**Comment by fernandog** [comment]
@felipesalomao please open another issue
