### ISSUE TITLE
[APP SUBMITTED]: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>

### ISSUE THREAD

**Issue by OmgImAlexis** [SickRage/sickrage-issues#121]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-67-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@1e8a1a0ede9b386f25e243c1c4e3814a520bd325
Link to Log: https://gist.github.com/dfaf899a16ae2831b0b9
### ERROR
```
POSTPROCESSER :: Boxcar2 notification failed.error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
It happens sometimes
