### ISSUE TITLE
Add tooltip/title to all table fields explaining the row filter

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#124]
```
Supports =, >, >=, <=, <, xx to yy , xx - yy
Note: =, >, >=, <=, < should be first, followed by a space, then the value
Examples: '> 90', '= 100', '0 to 99'
Fields yes/no/enable/disable you should use 'y' or 'n'
```

Suggestions to the text?

**Comment by labrys** [comment]
On the last line spell `should` correctly and `use` not `user` :grinning:, other than that :+1:

**Comment by fernandog** [comment]
damn phone keyboard! fixed

**Comment by fernandog** [comment]
can we have a title in html with multiple lines??

**Comment by labrys** [comment]
Take a look at how `download_stat_tip` is done in `home.mako`.

```python
download_stat_tip = download_stat_tip + "&#013;" + "Total: " + str(cur_total)
```

**Comment by neoatomic** [comment]
@fernandog Can this be closed.?

**Comment by fernandog** [comment]
Yes. But we need to think the best way to do this.

**Comment by fernandog** [comment]
@OmgImAlexis @miigotu @labrys 

what do you think?
https://mottie.github.io/tablesorter/docs/example-widget-header-titles.html

**Comment by OmgImAlexis** [comment]
I guess if we have to but keep in mind this is just adding more clutter to the UI and more stuff that needs to be loaded every time you load a page.

**Comment by labrys** [comment]
@fernandog While I like the look of it, I think that for a tooltip thats a little too heavy.  Personally i think just a help link (such as to the wiki, or some kind of expanding div or something) on pages with the filter would be sufficient and much more lightweight.
