### ISSUE TITLE
[APP SUBMITTED]: EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by rssfed23** [SickRage/sickrage-issues#125]
### INFO
Python Version: **2.7.10 (default, Sep 24 2015, 17:50:09) [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]**
Operating System: **Linux-4.2.6-200.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1e8a1a0ede9b386f25e243c1c4e3814a520bd325
Link to Log: https://gist.github.com/8e3d9050ad38125403b3
### ERROR
```
SEARCHQUEUE-BACKLOG-298901 :: [TvChaosUK] :: Prowl notification failed.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rssfed23** [comment]
### INFO
Python Version: **2.7.10 (default, Sep 24 2015, 17:50:09) [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]**
Operating System: **Linux-4.2.6-200.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1e8a1a0ede9b386f25e243c1c4e3814a520bd325
Link to Log: https://gist.github.com/962edb4f6f31843f5a75
### ERROR
```
POSTPROCESSER :: Prowl notification failed.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rssfed23** [comment]
### INFO
Python Version: **2.7.10 (default, Sep 24 2015, 17:50:09) [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]**
Operating System: **Linux-4.2.6-200.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1e8a1a0ede9b386f25e243c1c4e3814a520bd325
Link to Log: https://gist.github.com/b6389f439393214a3312
### ERROR
```
POSTPROCESSER :: Prowl notification failed.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rssfed23** [comment]
This has started happening since the latest update.

Doesn't matter what series is being downloaded (although could be length of the name). It also happens randomly on certain episodes of the same show.

Trace:

2015-12-02 19:23:35 ERROR    POSTPROCESSER :: Prowl notification failed.
Traceback (most recent call last):
  File "/var/lib/transmission/sickrage/sickbeard/notifiers/prowl.py", line 146, in _send_prowl
    body=urlencode(data))
  File "/usr/lib64/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
2015-12-02 19:23:35 INFO     POSTPROCESSER :: Processing succeeded for /downloads/t

**Comment by labrys** [comment]
Please wrap your logs in  ``` to make 'em all purty.  :grinning:

**Comment by rssfed23** [comment]
Thanks for the tip! - First time doing anything "public" on GitHub and yep; looks much more b-e-a-uuuutiful :+1:

**Comment by Amadeus-** [comment]
@rssfed23   Can you confirm that your Prowl notification API(s) are correct?    Or, are most prowl notifications working, but you're just getting this error occasionally?

I will look into this since I recently updated the Prowl notifications.   It looks like there is something going wrong when contacting the Prowl API website (perhaps related to SSL.)    But, I'll spend some time on it over the next few days.

Anyway, as far as the error goes, it looks like it pertains exclusively to the Prowl notification.   So, it shouldn't be affecting anything else.

**Comment by rssfed23** [comment]
From what I can tell yep the apis are correct. You're right: It's only on a minority of notifications. 95% get through okay.

I'm wondering if it may be a timeout of the connection - at the time I was doing a lot of downloading (no seeding) so bandwidth would of been reduced a bit. I do have a 2Gbit line into this server though so although it was maxed out there should've been enough left for a Prowl api call. 

I've not seen it happen for the hourly tv searches/downloads yet - only when I'm adding a new show and it's trying to send many notifications one after the other does the error occur and notification fail to send. So if it's not a timeout the only other thing specific to my configuration could be the number of notifications sent within a short time frame. If that was recently changed in the code then it could be that and a rate-limit per second may help, but I'm not an expert with Prowl or Python.

If there's anything you'd like me to test on the server just post a comment and I'm more than happy to give it a try :)

**Comment by Amadeus-** [comment]
I will look into the ssl library and see what exactly is causing that error message, it very well could be a timeout issue (i.e., our application interprets a delayed response as no response, or something along those lines.)

For now, just let me know if you discover a pattern; otherwise, I'll post here when I know more.   Since it's a very occasional thing, we probably just need to better handle connection (and/or connection responses.)    

I don't think it's anything caused by my recent update to the notifier...which is good.

**Comment by Amadeus-** [comment]
@rssfed23 Can you provide your openssl and python versions on that machine?
```
python --version
openssl version
```
Also, if you're using python 2.7.9 or 2.7.10 (which is what you should be using), you should not have pyOpenSSL installed ....so, you'd want to remove that if you have it.

From our lead dev:
> <miigotu> so the recommended setup is always 2.7.10, remove pyOpenSSL, and have openssl 1.0.1e+

**Comment by rssfed23** [comment]
[rob@torrent ~]$ python --version
Python 2.7.10
[rob@torrent ~]$ openssl version
OpenSSL 1.0.1k-fips 8 Jan 2015
[rob@torrent ~]$ rpm -qa | grep -i pyopenssl
pyOpenSSL-0.15.1-1.fc22.noarch

I've now removed pyOpenSSL and will keep an eye out!

**Comment by rssfed23** [comment]
### INFO
Python Version: **2.7.10 (default, Sep  8 2015, 17:20:17) [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]**
Operating System: **Linux-4.2.6-301.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e44f3ea56ed7150bbc18e3312f0eb1442ef724bf
Link to Log: https://gist.github.com/9e1115369332f67f529b
### ERROR
```
POSTPROCESSER :: Prowl notification failed. [e44f3ea]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rssfed23** [comment]
### INFO
Python Version: **2.7.10 (default, Sep  8 2015, 17:20:17) [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]**
Operating System: **Linux-4.2.6-301.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@e44f3ea56ed7150bbc18e3312f0eb1442ef724bf
Link to Log: https://gist.github.com/96d890ce7cf238a7e0b3
### ERROR
```
POSTPROCESSER :: Prowl notification failed. [e44f3ea]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rssfed23** [comment]
This has started happening again a couple of days ago. Nothing has changed on the server-end.
````
2016-02-14 00:16:45 DEBUG    POSTPROCESSER :: PROWL: Sending notice with details: title="SickRage" event="Download Finished", message="The X-Files - 10x01 - My Struggle - 720p WEB-DL :: Sun, Feb 14, 2016 12:16 am", priority=0, api=****************************************
2016-02-14 00:16:50 ERROR    POSTPROCESSER :: Prowl notification failed. [e44f3ea]
Traceback (most recent call last):
  File "/var/lib/transmission/sickrage/sickbeard/notifiers/prowl.py", line 153, in _send_prowl
    body=urlencode(data))
  File "/usr/lib64/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
````
