### ISSUE TITLE
Not snatching automatically, but manual snatch works

### ISSUE THREAD

**Issue by POEDaley** [SickRage/sickrage-issues#129]
Hello,

In the last couple weeks, I've really been struggling with sickrage and it not snatching properly. Sometimes when I clear out the cache and restart it, it will work temporarily. Also, click on the magnifying glass next to an episode will search out the episode just fine and snatch it.

It worked very well for quite a long time. This just started happening recently and not sure what could have prompted it.

Everything else seems to work just fine, but it's not snatching new episodes by itself anymore

Does anyone have any ideas, or where to look for where the problems is?

Thanks in advance

Windows 10 64bit
SR Version: BRANCH: (master) / COMMIT: (1e8a1a0ede9b386f25e243c1c4e3814a520bd325) 
Python Version: 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

**Comment by adaur** [comment]
How long is the backlog search set?

**Comment by POEDaley** [comment]
Backlog search days = 7
Backlog Search frequency = 720
Daily Search frequency = 15

**Comment by miigotu** [comment]
@POEDaley set your daily higher for one. Second, is this error occurring with the latest master? (A release to master was made a few hours ago)

**Comment by POEDaley** [comment]
It didn't update automatically, and I have not seen it update for quite some time now. Even manually trying to update came up with zeros.  I just tried to do a manual update again, and said I was 221 commits behind now.. Hopefully this solves some issues??

In regards to setting the daily higher, what do you suggest setting it to?  What seems to work the best?

Thanks,

**Comment by miigotu** [comment]
minimum 20 minutes, but 40 minutes is suggested

**Comment by POEDaley** [comment]
That's updated to 40 now.  I'll see how this goes over the next couple days. 

Thanks again for your help.

**Comment by dbrain** [comment]
I'm not sure if this is related, but when I add new shows marking everything as wanted, it takes a long time for anything to start downloading (without a manual search press).

Does this get put into the "Backlog Search" queue or something? Any chance a toggle could be added to "Add show" page to automatically search for episodes when added?

**Comment by miigotu** [comment]
It has to scan the entire show in from tvdb and imdb before it will start searching, there is nothing that can be done to avoid that.

**Comment by POEDaley** [comment]
So it seems like it went back to not snatching anymore.  No errors came up at all.  It really should have picked up a show last night, but it missed it completely.  Just tried to use the manual search for it, and snatched it right away.

Any other ideas, or anything I can provide you to help further?

Thanks

**Comment by miigotu** [comment]
There was a small issue fixed, but beyond that the team cannot reproduce this.

**Comment by tooobe** [comment]
I'm having the same problem. Manual search for a episode works fine, but automatic search won't snatch episodes. Not even a force daily search under "manage searches" works.

**Comment by POEDaley** [comment]
Oh, I switched to the other sickrage (SickrageTV), and it fixed everything
and has been running great since my previous post at the beginning of
December last year.

**Comment by POEDaley** [comment]
But yeah, that was exactly my problem as well.

**Comment by tooobe** [comment]
I'd do that too but I don't trust that developer anymore after everything that happened.

**Comment by miigotu** [comment]
@tooobe doo a mass update on all shows:

On the mass update page, click the bulkcheck the `update` column and click submit, then wait for the work to finish.

After that, any episodes you are missing that are > 1 day old are backlog items. New items will be found with daily search.

@POEDaley do not advise people here to move back to a broken fork. That fork literally has 4 ppl using it who can actually get it working (i have proof).

**Comment by tooobe** [comment]
@miigotu I did a mass update already, it didn't seem to help but i'll see if it fetces upcoming episodes, and report back if it doesn't :)

**Comment by tooobe** [comment]
Same problem appearing again. What could be the cause? Same problem both on the install on my server AND on my laptop...

**Comment by miigotu** [comment]
Sickrage is meant to be ran 24/7. Also you need a provider with daily search enabled.

**Comment by tooobe** [comment]
It is running 24/7 on my server. It worked with my provider for like 2 years up until now. I will have no choice but to move to the "broken" fork if this doesn't get fixed.

**Comment by simo26246** [comment]
I'm also having this issue, it won't automatically snatch episodes, but if I click the magnifying glass, everything works fine. It's a brand new install, running on a server that's on 24/7. Is anyone else still having this issue?

**Comment by miigotu** [comment]
Check the date/time on the server maybe?
