### ISSUE TITLE
Unknown error code. Please submit an issue

### ISSUE THREAD

**Issue by giantpune** [SickRage/sickrage-issues#130]
```
2015-12-02 18:09:21 SEARCHQUEUE-BACKLOG-75382 :: [Torrentz] :: Unknown error code. Please submit an issue
2015-12-02 18:09:06 SEARCHQUEUE-BACKLOG-75382 :: [Torrentz] :: Unknown error code. Please submit an issue
2015-12-02 18:07:51 SEARCHQUEUE-BACKLOG-75382 :: [Torrentz] :: Unknown error code. Please submit an issue
2015-12-02 18:07:02 SEARCHQUEUE-BACKLOG-75382 :: [Torrentz] :: Unknown error code. Please submit an issue
```

This is running from master branch.  Not sure what other info you need.

**Comment by labrys** [comment]
@giantpune You can find what information we would like to see in an issue request [here](https://github.com/SickRage/sickrage-issues).  Also if you could please wrap code or log output posted here with ``` it really improves the readability.  See [markdown](https://guides.github.com/features/mastering-markdown/) for other ways to edit your posts.

**Comment by miigotu** [comment]
Lol what's up @giantpune found your way to the party?

Do you have debug logging enabled, and how might I reproduce?

**Comment by Amadeus-** [comment]
I find it sad that the log message mentions that the error code is unknown, but doesn't share what the erroneous error code happens to be :(

**Comment by giantpune** [comment]
I think i filled the bug report in the wrong repo anyways.  Mine's running from https://github.com/SiCKRAGETV/

**Comment by duramato** [comment]
@giantpune switch repo and see if its fixed on this one ,it will probably be

**Comment by miigotu** [comment]
@giantpune we are about 1500 commits ahead of the other repo. Entire team/community except echelon has moved here.
