### ISSUE TITLE
Show marked like unaired show even after aire date

### ISSUE THREAD

**Issue by artentica** [SickRage/sickrage-issues#133]
Hi I have deleted cache.db cache/sessions,mako,rss and regenerate the sickbeard.db but my show still  do not update.
I am on the main branch of sickrage, do you know what I need to do?

**Comment by medariox** [comment]
What is the name of the show? Are you sure that thetvdb.com has the correct entries for the air dates?

**Comment by artentica** [comment]
yeah the air date show are good the all the showfor the moment that I follow: the Flash, iZombie, Marvel agents of SHEILD, Arrow, Chivalery of the failed knight, The last man on earth

**Comment by duramato** [comment]
Check your timezone

**Comment by artentica** [comment]
timeone is set on "network" and it's been days that shows are aired

**Comment by duramato** [comment]
Your actual system timezone

**Comment by neoatomic** [comment]
Also post the commit version you are currently using of Sickrage.

**Comment by artentica** [comment]
Duramato i change to local my timezone then i put it on network again and it's seems to work fine now :O thanks for all your answer.
I spend times on it for just an undo/do... Thanks again everyone

**Comment by bondjw07** [comment]
Had the same issue, toggling the timezone option worked for me as well
