### ISSUE TITLE
[APP SUBMITTED]: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by Pacha56** [SickRage/sickrage-issues#134]
### INFO
Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-4.1.13-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@a89bf7fbf5dd0762d1d6ac98cd624219697a6a54
Link to Log: https://gist.github.com/dc701d23db37ca509731
### ERROR
```
EVENT-QUEUE :: Exception generated in thread EVENT-QUEUE: error 9 : Bad file descriptor
EVENT-QUEUE :: anidb: handling(1-2) command LOGOUT 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
random. will re-open if this becomes common
