### ISSUE TITLE
No WebUI - Could not start webserver on port 8081, already in use 

### ISSUE THREAD

**Issue by bluezed** [SickRage/sickrage-issues#138]
Hi there,

I've only just moved here from the "old" SickRage as nobody there seemed to care about my issue... Hopefully someone here can help?

I've installed a new machine (Intel NUC with Ubuntu 15.10) and have put SickRage on it following the Install guide linked to in the FAQ section. All went well, as with all my previous installations, but now I've come to a point where I can't find a solution.

I set up the ``` sickrage.service ``` under ``` /etc/systemd/system ``` and apparently SickRage starts fine when I reboot the machine but the WebUi does not. In the logs I see this line:
```
2015-12-04 11:51:52 INFO     TORNADO :: Starting SickRage on http://192.168.2.197:8081/
2015-12-04 11:51:52 INFO     TORNADO :: Could not start webserver on port 8081, already in use! 
```
If I restart the SickRage service manually it works fine and I can access the WebUi.
Here's a link to the log: http://paste.ubuntu.com/13665930/

Here's the content of my sickrage.service file:
``` [Unit]
Description=SickRage Daemon

[Service]
User=tv
Group=tv
Type=forking
GuessMainPID=no
ExecStart=/usr/bin/python /home/tv/.sickrage/SickBeard.py -q --daemon --nolaunch --datadir=/home/tv/.sickrage

[Install]
WantedBy=multi-user.target 
```

I've already tried changing the Port and also adding this line
``` After=network-online.target ```
to the ``` [Unit] ``` section of the file thinking maybe the network isn't up and running yet but still the same result.

Anyone got any other suggestions what I could try? I've already spent hours trying to figure it out but no luck so far...

Many thanks!

**Comment by OmgImAlexis** [comment]
@SickRage/moderators @SickRage/collaborators

**Comment by bluezed** [comment]
Ha! Actually raising this issue made me think of something and I've now solved it! :grin: 

The problem on my system is that I'm starting a VPN service with systemd as well and when sickrage starts the VPN isn't fully up yet.

After some more digging around I changed my ``` sickrage.service ``` to this:
``` [Unit]
Description=SickRage Daemon
After=openvpn-connection.service sys-devices-virtual-net-tun0.device network.target network-online.target
Requires=openvpn-connection.service sys-devices-virtual-net-tun0.device

[Service]
User=tv
Group=tv
Type=forking
GuessMainPID=no
ExecStart=/usr/bin/python /home/tv/.sickrage/SickBeard.py -q --daemon --nolaunch --datadir=/home/tv/.sickrage

[Install]
WantedBy=multi-user.target 
```
So by adding the actual ``` sys-devices-virtual-net-tun0.device ``` device as Required and After it now waits with the execution of the SickRage daemon until the tunnel is actually up. Problem solved!

Maybe this is helpful for other people as well :smiley:

**Comment by limerick11** [comment]
Where can I find sickrage.service?

**Comment by miigotu** [comment]
@limerick11 on your system or?

**Comment by limerick11** [comment]
yeah, if I want to update the file, where can I find it?

**Comment by limerick11** [comment]
Raspbian (Raspberry)

**Comment by miigotu** [comment]
usually in `/etc/systemd/system/` for systems running systemd for it's init.

It might also be in `/etc/init.d/` if the system is running sysVinit

**Comment by limerick11** [comment]
hmmm, couldn't find it in either

**Comment by duramato** [comment]
Try `/etc/init/` too

**Comment by bluezed** [comment]
Just saying... But the file won't just be there if you haven't actually created it. It's not an automatic thing.

**Comment by miigotu** [comment]
@bluezed your original issue, you need to remove the --daemon, or add pid arguments to the unit.

**Comment by bluezed** [comment]
@miigotu Thanks for the hint, will try it out when I get the chance...

Though I actually quite like having Sickrage service depend on the VPN being up as it will actually kill off Sickrage if the VPN goes down for some reason ;)

**Comment by miigotu** [comment]
Thats ok too, but without the change I stated above systemd will lose track of the state/pid of the process almost immediately, at least for sure on the first restart from the gui or after an update.

**Comment by bluezed** [comment]
Ah I understand... Thanks for that :)
