### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by duramato** [SickRage/sickrage-issues#139]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-37-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@6f2fda500131638944d407604535c3e8989d4a27
Link to Log: https://gist.github.com/735aeabb624287a35876
### ERROR
```
SEARCHQUEUE-MANUAL-273719 :: [TransmitTheNet] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 126, in _doSearch
    download_url = self.urls['base_url'] + torrent_row.find('a', {"title": 'Download Torrent'})['href']
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Symbiot78** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.9**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@7fd6c98aafe1f543bf8f96b2e370666be5412288
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/providers/morethantv.py", line 138, in search
    torrent_id_long = link['href'].replace('torrents.php?action=download&id=', '')
TypeError: 'NoneType' object has no attribute '__getitem__'
 [7fd6c98]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-43-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@77c9f8bc1343c4f3d7154d437842e82f0cc21201
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/morethantv.py", line 137, in search
    torrent_id_long = link['href'].replace('torrents.php?action=download&id=', '')
TypeError: 'NoneType' object has no attribute '__getitem__'
 [77c9f8b]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by medariox** [comment]
Fixed in develop https://github.com/SickRage/SickRage/pull/707

**Comment by hzqtaegp** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7fd6c98aafe1f543bf8f96b2e370666be5412288
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\providers\morethantv.py", line 138, in search
    torrent_id_long = link['href'].replace('torrents.php?action=download&id=', '')
TypeError: 'NoneType' object has no attribute '__getitem__'
 [7fd6c98]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
its already fixed in develop. you can stop spamming it now.
