### ISSUE TITLE
Transmission: Authentication Failed issue

### ISSUE THREAD

**Issue by froggay** [SickRage/sickrage-issues#1397]
**Branch/Commit**: master /2016.03.28-2-6-g7902d12
**OS**: windows 7
**What you did**: transmission setup in config/search/
**What happened**: 
transmission test is ok, i get message : 

> "Success: Connected and Authenticated"

but when i go to manage/manageTorrents/ i have a 404 error message
and when i launch a search, the torrent is not sent to transmission daemon
i have a error messsage " 
> SEARCHQUEUE-MANUAL-77398 :: Transmission: Authentication Failed"

Logs: http://pastebin.com/f2Fm1nnv

my transmission deamon is coming from a french ISP DSL box ( freebox )
same transmission parameters works fine with transmission remote

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
