### ISSUE TITLE
Importing existing series: *.m2ts entered as "skipped," not "downloaded"

### ISSUE THREAD

**Issue by salfter** [SickRage/sickrage-issues#1398]
Branch/Commit: 89520a34e67073998be844c3721a3730341abb12
OS: Linux
What you did: imported an existing series
What happened: *.m2ts entered in database as "skipped"
What you expected: *.m2ts entered in database as "downloaded"

(Imports of .m4v files (and probably .mkv as well) work OK; it's just .m2ts imports that aren't being picked up properly.)

Logfile attached as a file due to length.

[import-log.txt](https://github.com/SickRage/sickrage-issues/files/198486/import-log.txt)

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
