### ISSUE TITLE
Migrating Synology install to the new repository

### ISSUE THREAD

**Issue by W7PEA** [SickRage/sickrage-issues#14]
How can I move my current install to this repository?
Synology does not have the git client available.
I see in the config.ini there are github settings, would it be possible to edit these directly?

```
git_autoissues = 0
git_username = ""
git_password = ""
git_reset = 1
branch = master
git_remote = origin
git_remote_url = https://github.com/SiCKRAGETV/SickRage.git
cur_commit_hash = d294e9faf48d45051a50d4e2cf3a0252c28d5b17
cur_commit_branch = ""
git_newver = 0
config_version = 7
```

**Comment by neoatomic** [comment]
@W7PEA Its very easy for a Synology. :

1) Make a backup with Sickrage.
2) Go to the Synology Package Center and remove Sickrage.
3) Then Reinstall Sickrage, but now in the installation screen/wizard add the new URL.
4) Restore your backup with Sickrage, and restart Sickrage.

Thats it. :+1:

**Comment by W7PEA** [comment]
Works like a charm. Note for future readers, you can use the SickRage installer again. Some older docs\links say to use the sickbeard custom package. That is not necessary.
