### ISSUE TITLE
SickRage :: Unable to determine free space

### ISSUE THREAD

**Issue by heymoe** [SickRage/sickrage-issues#1400]
**Branch/Commit:** master / 89520a34e67073998be844c3721a3730341abb12
**OS:** CentOS v5.11 using Python 2.7.10

**What you did:** Updated Sickrage? I can run "df" as both root and the user SickRage is running as and get free space information from it. I'm not seeing any errors or warnings in the system / OS logs that might be causing this issue.  

**What happened:** I noticed that the "Service Status" page is no longer displaying free space for the different paths I have configured under the "Disk Space" section. It's not reporting "Missing". I'm also seeing the following warnings in the logs:

- Thread-13 :: Unable to determine free space
- Thread-13 :: Unable to determine free space, so I will assume there is enough.

**What you expected:** Expected SickRage to be able to determine free space. This seems to have started around 2016-03-29 so I'm guessing after I did an update.

**Logs:** I did enable Debug logging but it doesn't seem to catch any debug information for this issue.

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by heymoe** [comment]
Created issue report in the new place... closing..
