### ISSUE TITLE
No subtitles found

### ISSUE THREAD

**Issue by SeeDborg** [SickRage/sickrage-issues#1401]
Branch/Commit: master
OS: OSMC (raspbian)

I just reinstalled Sickrage on my Raspberry Pi, but it does not find any subtitles for my shows... I'm searching on addic7ed only, and checked several times my username and password.
It was working before.

Is that a known issue and is there a way to solve it ?

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
