### ISSUE TITLE
Windows 10 service no access to networked mapped drives?

### ISSUE THREAD

**Issue by ruinit** [SickRage/sickrage-issues#1403]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:Branch: master Commit: 529c7cec3c2bc79b05f7dab501a45e9a29e03efc
OS:Windows 10
What you did: New Install
What happened:Starts but can't access my mapped drives
What you expected: Access to mapped drives

With the trouble on synology I decided to make a windows install and still use my disk station for storage. I got it installed and all but I can not access my mapped drives? I don't use a password for this windows computer. I have looked around a bunch and can't seem to get a solution. I used the windows installer package.

Thanks for any help

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
