### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-MANUAL-284210 :: DelugeD: Unable to send Torrent: Return code undefined [3dd13c3]

### ISSUE THREAD

**Issue by widend** [SickRage/sickrage-issues#1405]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.10**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@3dd13c33887e3e09d706646f007d92678b0697c0
Link to Log: https://gist.github.com/410cf38f98d78f8c8630e29f8632977e
### ERROR
```
SEARCHQUEUE-MANUAL-284210 :: DelugeD: Unable to send Torrent: Return code undefined [3dd13c3]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by widend** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.10**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@3dd13c33887e3e09d706646f007d92678b0697c0
Link to Log: https://gist.github.com/67bd9a30d80a30edcfb1a20fbbb00e65
### ERROR
```
SEARCHQUEUE-BACKLOG-284210 :: DelugeD: Unable to send Torrent: Return code undefined [3dd13c3]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
Update your sickrage version.
