### ISSUE TITLE
Custom renaming format not working

### ISSUE THREAD

**Issue by zatricky** [SickRage/sickrage-issues#1406]
The following pattern:
```
Season %S/%SN - Season %S, Episode - %EN/%RN
```
renders as:
```
Season 2/Show Name - Season 2, Episode - Ep Name/Show.Name.S02E03.HDTV.XviD-RLSGROUP.ext
```
which is correct.

But by adding in one parameter:
```
Season %S/%SN - Season %S, Episode %E - %EN/%RN
```
the season/episode format is completely lost from the folder name. This is rendered as:
```
Season 2/Show Name - 003 - Ep Name/Show.Name.S02E03.HDTV.XviD-RLSGROUP.ext
```

Am I doing something wrong? I copied the string verbatim from my old Sickbeard install.

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
