### ISSUE TITLE
Snatched Status Should Return to Previous Once Snatch Fails

### ISSUE THREAD

**Issue by Ashkaan** [SickRage/sickrage-issues#1408]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: f59e46744829adf67a73a7dc9442eda26c40301d
OS: Synology DSM
What you did: Nothing
What happened: Sickbeard snatched a higher quality episode of a show.  Once the download failed, it did not return the status to the old quality.
What you expected: Once the download failed, it would return the status to the old quality (so I can see and know what it is).  If it cannot get that data from NZBGet, then there should be a manual button to return it to it's previous quality.
Image:

![image](https://cloud.githubusercontent.com/assets/5667978/14376591/50084112-fd1f-11e5-8e95-7a5aab1545f7.png)

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
