### ISSUE TITLE
Missing time zone for network

### ISSUE THREAD

**Issue by maxcore** [SickRage/sickrage-issues#1409]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

 SickRage Info:	Branch: master
 Commit: 98927da437d1bcac38ef7aac72d819e6f0e91c2a
 Version: 2016.04.08-1
 Python Version:	2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]
 SSL Version:	OpenSSL 1.0.2e 3 Dec 2015
 OS:	Linux-3.10.35-x86_64-with-glibc2.2.5
 Locale:	None.None
Logs:
```
2016-04-08 08:41:39 Thread-13 :: [98927da] Missing time zone for network: SRC
2016-04-08 08:41:39 Thread-13 :: [98927da] Missing time zone for network: Fuse
```

SRC: USA/Canada EAST Time
Fuse: USA/Canada EAST Time

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
