### ISSUE TITLE
Mass update "Default Ep Status" search bar is broken.

### ISSUE THREAD

**Issue by below9k** [SickRage/sickrage-issues#1410]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master / https://github.com/SickRage/SickRage/commit/98927da437d1bcac38ef7aac72d819e6f0e91c2a
OS: Ubuntu 14.04
What you did: Entered every character into the search bar
What happened: No matches for anything
What you expected: Matches for something
Logs: Nah
```
Nahhhhhhhhhh
```

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by below9k** [comment]
Wrong repo.
