### ISSUE TITLE
Please help with QnAP install

### ISSUE THREAD

**Issue by Dohnerd** [SickRage/sickrage-issues#1411]
I switched from Qnap ts-219p(arm) to ts-269p (intel) and i have been trying to install sickrage on it for 4 days now, and I must admit i've hit a brick wall... a short description, the only git im able to install is Qgit 2.7.9 and trying to run 5 different versions of your repo i get "unable to install missing qpkg package git".... and on a really old ipkg, i get net optware (which is discontinued)

the only sickrage i was able to install is QSickrage 7.0.22, so i thought " ok i will do a "git remote set-url origin https://github.com/SickRage/SickRage.git"  but that gives me an "fatal: No such remote 'origin'"
I even tried a "git init" and "git add -all" but it gave me the same results.

Please help, I'm totally lost :(

Thx in advance.
 
```

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
