### ISSUE TITLE
Force language to english

### ISSUE THREAD

**Issue by stanthewizzard** [SickRage/sickrage-issues#1412]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 31aad15d12e7eb43b5b5a7e3d417a2b3c0235b99
Version: 2016.04.10-1

Since last update GUI isn't in English anymore.

How can I Force the Language to English ?
Thanks

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
