### ISSUE TITLE
[APP SUBMITTED]: local variable 'cmd_index' referenced before assignment

### ISSUE THREAD

**Issue by mationic** [SickRage/sickrage-issues#1413]
### INFO
Python Version: **2.7.9 (default, May  1 2015, 09:18:34) [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]**
Operating System: **Linux-2.6.32-042stab113.11-x86_64-with-centos-6.6-Final**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5d51b1687edf252958317c8cbb110069d7b207b3
Link to Log: https://gist.github.com/6650c1e9d962d6da6a5ecb866f63b9ed
### ERROR
```
TORNADO :: API :: local variable 'cmd_index' referenced before assignment [5d51b16]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by neoatomic** [comment]
Please update your Sickrage version.
