### ISSUE TITLE
Cant open sickrage today

### ISSUE THREAD

**Issue by syrys** [SickRage/sickrage-issues#1415]
Hey Guys,

First of all, im used the windows SR installer, installed last year sometime. Im not 100% sure of the current version, as i cannot get in to the UI, but auto update was set, so likely a very recent update from few hours ago?

Anyway, SR worked just fine about 4 hours ago. When i tried to load it now, it shows an error instead of showing the web UI. Thus not being able to do anything at all. Error is as follows:

````
This site can’t be reached

localhost refused to connect.
ERR_CONNECTION_REFUSED
````
or 
````
This site can’t be reached

PC_NAME refused to connect.
ERR_CONNECTION_REFUSED
````
I access SR using localhost:8081 or PC_NAME:8081 (if i use another computer on the network). All worked fine for months, worked fine this morning. How can i debug/fix this?

I did absolutely nothing. Restarted several times, and still nothing :(

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by neoatomic** [comment]
https://github.com/SickRage/SickRage/issues/1454#issuecomment-208857081
