### ISSUE TITLE
2-step verification causing "Permission denied"

### ISSUE THREAD

**Issue by Weggy** [SickRage/sickrage-issues#1416]
2-step verification causing "Permission denied"

Branch: master
Commit: e718ba29b4fd92099d2c2c665ae9c7845a633c23
Version: 2016.04.11-2
OS: Synology - DSM 6.0-7321
What you did: Requested an episode
What happened:Failed to download due to "Permission denied"
What you expected: The episode to download

Logs:
```
2016-04-12 18:34:39 WARNING  SEARCHQUEUE-MANUAL-273181 :: DownloadStation: Authentication Failed
2016-04-12 18:34:39 INFO     SEARCHQUEUE-MANUAL-273181 :: Permission denied
```

Temp Fix:
- Disable 2-step verification
- Attempt to reconnect
- Success

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by neoatomic** [comment]
2-step verification is currently not yet supported on DSM6.
You can read more in this topic. : https://github.com/SickRage/sickrage-issues/issues/587#issuecomment-201949331
