### ISSUE TITLE
Can't enable post processing

### ISSUE THREAD

**Issue by PhunkyBob** [SickRage/sickrage-issues#1417]
Hello,

I can't enable post-processing.

Step to reproduce:
- go to : http://my_ip:8083/config/postProcessing/
(the "enable" checkbox is not checked)
- check the "enable" checkbox
- click the first "save changes" button
(a pop-up "Configuration saved" is displayed)
- click the second "save changes" button, just in case
- change page
- go to : http://my_ip:8083/config/postProcessing/
→ the "enable" checkbox is still not checked

Branch: master (up to date).

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by miigotu** [comment]
Check the permissions on your config.ini.

**Comment by PhunkyBob** [comment]
A forgot to say that others parameters (subtitles, general, ...) **are** saved.


ps: where is the real repo for submitting issues?
https://github.com/SickRage/sickrage-issues/issues/
or
https://github.com/SickRage/SickRage/issues/
