### ISSUE TITLE
QQ/FR: rename files after episode naming change

### ISSUE THREAD

**Issue by mgaulton** [SickRage/sickrage-issues#1418]
I haven't found anything that would work so I'm looking for suggestions. I've changed both the regular and anime naming schemes and would like to be able to force rename on all existing episodes/shows. I'm not seeing anything in the API that would let me do this and the Mass Edit is now limited on the number of shows you can do.

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
