### ISSUE TITLE
Can't get Notifications working

### ISSUE THREAD

**Issue by sulaimanwalsh** [SickRage/sickrage-issues#1419]
Hi sickrage users,

I'm new to this platform and i'm loving it, but i'm having an issues setting up notifications from the ubuntu machine to my ios device.

OS: Ubuntu 14.04

What you did:  
I am trying to add devices to the notification tab in settings, i've tried pushbullet, pushover and telegram

What happened:
For pushover and telegram when i try to test message it says message sent, but I don't receive anything on my devices.
For Pushbullet the test message fails, see log output below.

What you expected:
I was hoping someone with experience setting up the notifications may know if this is an issue or a workaround.

Logs:

Request failed: 401 Client Error: Unauthorized for url: https://api.pusbullet.com/v2/pushes

thanks anyone and everyone

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
