### ISSUE TITLE
Add provider

### ISSUE THREAD

**Issue by Sokkar** [SickRage/sickrage-issues#1420]
Hello,

Anyone can explain us how can i add a provider coming from sickbear to sickrage plz?.

THanks you.

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by Sokkar** [comment]
Ok SickRage2 thanks you for your reply.

**Comment by neoatomic** [comment]
@Sokkar http://feathub.com/SickRage/SickRage
