### ISSUE TITLE
[APP SUBMITTED]: Scorpion is in process of being updated by Post-processor or manually started, can't update again until it's done.

### ISSUE THREAD

**Issue by CraXyOW3** [SickRage/sickrage-issues#1423]
### INFO
Python Version: **2.7.10 (default, Mar 19 2016, 15:43:19) [GCC 4.6.3]**
Operating System: **Linux-4.1.13+-armv6l-with-debian-7.9**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@3dd13c33887e3e09d706646f007d92678b0697c0
No Log available with ERRORS:
### ERROR
```
SHOWUPDATER :: Automatic update failed: Scorpion is in process of being updated by Post-processor or manually started, can't update again until it's done. [3dd13c3]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
