### ISSUE TITLE
Discussion: "Please update SickRage, unable to submit issue ticket to GitHub with an outdated version!"

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#143]
Can we disable this in develop? Develop branch has commits almost everyday and we can't submit issues using issue submitter

@SickRage/collaborators

**Comment by miigotu** [comment]
You would just end up with users on develop but 500 commits behind spamming issues that were fixed 490 commits ago.

**Comment by fernandog** [comment]
I was only 4 commits behind

For example this issue below. I could not reproduce again after I updated the 4 commits behind. I'm sure it didn't fixed this:
https://github.com/SickRage/sickrage-issues/issues/142

**Comment by miigotu** [comment]
If someone is running develop I would assume they can manually submit an issue if its that big of a deal.
