### ISSUE TITLE
[APP SUBMITTED]: index() got an unexpected keyword argument '<methodCall> <methodName>system.listMethods</methodName> <params></params> </methodCall>'

### ISSUE THREAD

**Issue by AubreyKloppers** [SickRage/sickrage-issues#1448]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.10**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5195b784b76916a2acfe21c1fffd12f837ce0e93
No Log available with ERRORS:
### ERROR
```
Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument '<methodCall> <methodName>system.listMethods</methodName> <params></params> </methodCall>'
 [5195b78]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by AubreyKloppers** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.10**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5195b784b76916a2acfe21c1fffd12f837ce0e93
No Log available with ERRORS:
### ERROR
```
Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument '<methodCall> <methodName>system.listMethods</methodName> <params></params> </methodCall>'
 [5195b78]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by AubreyKloppers** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.10**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5195b784b76916a2acfe21c1fffd12f837ce0e93
No Log available with ERRORS:
### ERROR
```
Thread-21 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument '<methodCall> <methodName>system.listMethods</methodName> <params></params> </methodCall>'
 [5195b78]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
