### ISSUE TITLE
[APP SUBMITTED]: Thread-215 :: git config remote.origin.pushurl  returned :  [cdf22bf]

### ISSUE THREAD

**Issue by ducapedia** [SickRage/sickrage-issues#1449]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/bbb743952b523b38e466cbb7646536e9
### ERROR
```
Thread-215 :: git config remote.origin.pushurl  returned :  [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by ducapedia** [comment]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/eabcc5f5df062baecff42c75f67cacad
### ERROR
```
Thread-223 :: git config remote.origin.pushurl  returned :  [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ducapedia** [comment]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/fd8a8bfc531dd3abf9e6218cb7017bfc
### ERROR
```
Thread-237 :: git config remote.origin.pushurl  returned :  [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Your install is fucked, back up and reclone, then restore. Your SR hasnt updated in a long time.
