### ISSUE TITLE
[APP SUBMITTED]: Old quality does not match new: 1080p WEB-DL != 1080p BluRay : Lucifer.s01e06.1080p.HEVC.WEB.DL.x265.HEVCBluRay

### ISSUE THREAD

**Issue by ducapedia** [SickRage/sickrage-issues#1450]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/4f419267f61bb7b796aa5a71e423825c
### ERROR
```
SEARCHQUEUE-BACKLOG-295685 :: [Torrentz] :: Unknown exception while searching Torrentz. Error: 'Old quality does not match new: 1080p WEB-DL != 1080p BluRay : Lucifer.s01e06.1080p.HEVC.WEB.DL.x265.HEVCBluRay' [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
