### ISSUE TITLE
[APP SUBMITTED]: Old quality does not match new: 720p HDTV != 720p WEB-DL : Mythbusters.-.Season.15.-.720P.-.WEB-DL-HDTV.-.X265-HEVC.-.O69

### ISSUE THREAD

**Issue by ducapedia** [SickRage/sickrage-issues#1451]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/e8f3cceb92ff80f1ed2334326afc99f7
### ERROR
```
SEARCHQUEUE-BACKLOG-71663 :: [TorrentProject] :: Unknown exception while searching TorrentProject. Error: 'Old quality does not match new: 720p HDTV != 720p WEB-DL : Mythbusters.-.Season.15.-.720P.-.WEB-DL-HDTV.-.X265-HEVC.-.O69' [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by ducapedia** [comment]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/d4c0a01c6744682ab4991dfb82115b9a
### ERROR
```
SEARCHQUEUE-BACKLOG-71663 :: [TorrentProject] :: Unknown exception while searching TorrentProject. Error: 'Old quality does not match new: 720p HDTV != 720p WEB-DL : Mythbusters.-.Season.15.-.720P.-.WEB-DL-HDTV.-.X265-HEVC.-.O69' [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
if ur getting this error you havent updated in months.

**Comment by ducapedia** [comment]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/f552f8aca8a2ce3af26c1d9adfd1d445
### ERROR
```
SEARCHQUEUE-BACKLOG-71663 :: [TorrentProject] :: Unknown exception while searching TorrentProject. Error: 'Old quality does not match new: 720p HDTV != 720p WEB-DL : Mythbusters.-.Season.15.-.720P.-.WEB-DL-HDTV.-.X265-HEVC.-.O69' [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
if ur getting this error you havent updated in months.
