### ISSUE TITLE
[APP SUBMITTED]: [Errno 40] Too many levels of symbolic links: '/DataVolume/shares/Public/Shared Videos/Series/The Simpsons/Season 26/The.Simpsons.S26E16.720p.WEB-DL-NTb.mkv'

### ISSUE THREAD

**Issue by ducapedia** [SickRage/sickrage-issues#1453]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/ea1567964357146be4ddc29614ddd330
### ERROR
```
Thread-211 :: Unable to get size for file /DataVolume/shares/Public/Shared Videos/Series/The Simpsons/Season 26/The.Simpsons.S26E16.720p.WEB-DL-NTb.mkv Error: u'error 40 : Too many levels of symbolic links' [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by ducapedia** [comment]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/4b128eaf3871061bc2c609d22d2f3584
### ERROR
```
Thread-14 :: Unable to get size for file /DataVolume/shares/Public/Shared Videos/Series/The Simpsons/Season 26/The.Simpsons.S26E16.720p.WEB-DL-NTb.mkv Error: u'error 40 : Too many levels of symbolic links' [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ducapedia** [comment]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/14505b5a883f1815e1e9f9f4bcaf777b
### ERROR
```
Thread-235 :: Unable to get size for file /DataVolume/shares/Public/Shared Videos/Series/The Simpsons/Season 26/The.Simpsons.S26E16.720p.WEB-DL-NTb.mkv Error: u'error 40 : Too many levels of symbolic links' [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ducapedia** [comment]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/31ccb3aafa8720f6c1622f32c411f779
### ERROR
```
Thread-233 :: Unable to get size for file /DataVolume/shares/Public/Shared Videos/Series/The Simpsons/Season 26/The.Simpsons.S26E16.720p.WEB-DL-NTb.mkv Error: u'error 40 : Too many levels of symbolic links' [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ducapedia** [comment]
### INFO
Python Version: **2.7.3 (default, Jan  4 2013, 13:44:41) [GCC 4.6.3]**
Operating System: **Linux-3.2.26-armv7l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@cdf22bfe1cf70b90c32932a6b9326b6d3b8f7e63
Link to Log: https://gist.github.com/79a92a11ae58671310e130d36cead9a7
### ERROR
```
Thread-253 :: Unable to get size for file /DataVolume/shares/Public/Shared Videos/Series/The Simpsons/Season 26/The.Simpsons.S26E16.720p.WEB-DL-NTb.mkv Error: u'error 40 : Too many levels of symbolic links' [cdf22bf]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
