### ISSUE TITLE
Embedded subtitles not recognized 

### ISSUE THREAD

**Issue by nycom83** [SickRage/sickrage-issues#1455]
Branch: master
Commit: 2f6204d2500bdfa328fe572e0f1ab88058fe25d3

I'm using SickRage a long time without a single problem, until now.
I've got many tv show episodes with embedded subtitles. But it seems that these embedded subtitles are not recognized anymore.
For example, some mkv files are not process whereas there is an embedded subtitle.

There is a option in the "Subtitle Settings; "Ignore subtitles embedded inside video file". This option is not active
Does anyone has an idea?

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
