### ISSUE TITLE
Renaming Multiple Episodes

### ISSUE THREAD

**Issue by fidofido300** [SickRage/sickrage-issues#1458]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: f970b5fd5e222469059e71c9b0d6a18348d2770e
Version: 2016.05.12-1
OS: Windows 7
Ok I want to use Extended (Limited) E-Prefixed MultiEpisode rename but with an `e` prefix because ny custom rename uses `e` prefix
How can I achieve this.
Custom rename 
Season-%S/%S.N.s%0Se%0E.%E.N.%SQ.N.%RT-%RG
Thanks 

```
PASTE LOGS HERE
```

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
