### ISSUE TITLE
 No subtitle downloaded

### ISSUE THREAD

**Issue by Spyd05** [SickRage/sickrage-issues#1459]
Hello,

I have problems to download the subtitle to keg once I get the following error "No subtitles downloaded ."

I use the addic7ed supplier and yet I will see directly on the website , I find well for the series The 100 , subtitles in French.

Exception in Stage I nevertheless added "The 100 " so that research can be done with "Les 100 " and "The 100 " .

What should I do to have subtitles in VF ?

Thanks for your help.

Debug : 

> 2016-05-15 21:27:43 DEBUG    Thread-13 :: 268592: No subtitles downloaded for Les 100 S02E13
2016-05-15 21:27:43 DEBUG    Thread-13 :: No subtitles found for Les 100 S02E13
2016-05-15 21:27:43 DEBUG    Thread-13 :: Checking subtitle candidates for Les 100 S02E13 (Les 100 . S02 E13 - Résurrection (1080p.WEB.DL).mkv)

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by Spyd05** [comment]
ok
