### ISSUE TITLE
[APP SUBMITTED]: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by samtheeagle** [SickRage/sickrage-issues#1460]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-4.1.13+-armv6l-with-debian-7.8**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@3dd13c33887e3e09d706646f007d92678b0697c0
No Log available with ERRORS:
### ERROR
```
CHECKVERSION :: Exception generated in thread CHECKVERSION: argument of type 'NoneType' is not iterable [3dd13c3]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
