### ISSUE TITLE
Missing time zone for network: The Comedy Network

### ISSUE THREAD

**Issue by beodegit** [SickRage/sickrage-issues#1464]
### Info:
Branch/Commit:**master / a70d27a**
OS: **slackware64 current / Linux 4.4.11 x86_64 / Python 2.7.11**

### Logs:
```
2016-05-29 11:51:11 Thread-14 :: [a70d27a] Missing time zone for network: The Comedy Network
```

Probably "Canada/Eastern" as "The Comedy Network" is from Toronto / Ontario / Canada

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by beodegit** [comment]
Moved issue to https://github.com/SickRage/SickRage/issues/1888
