### ISSUE TITLE
Please restart sick rage. CA apache or http.

### ISSUE THREAD

**Issue by binarylimited** [SickRage/sickrage-issues#1465]
Hi guys

Please restart the webservice or fox the 503 error on sickrage.ca.
Looking for the forums to help with the iCal Google setup.

Thanks

Keep on keeping on with the great software!

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by duramato** [comment]
Forum isn't ours and this repo isn't in use anynore
