### ISSUE TITLE
provider torrentday no longer works

### ISSUE THREAD

**Issue by Fungie** [SickRage/sickrage-issues#1467]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/89676eb74a3fc9f765f17db291c9134df2537e38
OS: Linux-3.18.10-armv7l-with-glibc2.4 (openelec, raspberry pi 2)
What you did:  Manually download show as it didn't automatically
What happened: couldn't find the show on torrentday, checked the website and its up. They may have tweaked their website
What you expected: to download automatically or to successfully manually download it
Logs:
```
2016-05-30 19:25:35 INFO SEARCHQUEUE-MANUAL-277165 :: Unable to find a download for:      [Silicon Valley - S03E06 - Bachmanity Insanity]
```

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
