### ISSUE TITLE
show API call doesn't expose Scene Exception field

### ISSUE THREAD

**Issue by pyrodex** [SickRage/sickrage-issues#147]
The SickRage API call for show exposes a good deal of existing data for the show which is great! I noticed in my leveraging the API for my own project it doesn't expose the Scene Exception field which helpful for what I am doing. Could this be added please? Thanks!

**Comment by OmgImAlexis** [comment]
Duplicate: https://github.com/SickRage/sickrage-issues/issues/99

**Comment by miigotu** [comment]
@pyrodex, you could add your request for it in apiv2 issue
