### ISSUE TITLE
Download Station -  Torrentday credentials mess?

### ISSUE THREAD

**Issue by abdiz1** [SickRage/sickrage-issues#1473]
Hi

My Download Station suddenly stop connection to Torrentday. 
I have confirmed the login at Torrentday.
 
Back to my NAS and DownLoad Station:
When i Edit the settings, i verify the username and password -  i click the "Verify" that states:
The Account or password is invalid

Though: when i have set my password and verified, i see the password "dots" do NOT match my actual password... it seems that DS do not "save" my password and the password keeps "jumping" back to 8 digits pw. (my pw is 10 characters).

I have re-installed Download Station, still the same.
Any clues?  please help!

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
