### ISSUE TITLE
Missing time zone for network: Twitch

### ISSUE THREAD

**Issue by RossyK** [SickRage/sickrage-issues#1474]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 2016.05.09-1
OS: Linux Debian
What you did:Presented in Error Log
What happened:N/A
What you expected: Error to be dealt with by the addition of 'Twitch' to the timezone mapping
Logs:
```
2016-06-29 19:48:11 Thread-14 :: [34d0987] Missing time zone for network: Twitch
```

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
