### ISSUE TITLE
Associated files get deleted, pattern does not match

### ISSUE THREAD

**Issue by saru-man** [SickRage/sickrage-issues#1475]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/up-to-date
OS: Linux
What you did: added several file extensions (ts.meta,eit,ts.sc,ts.cuts,ts.ap,ts.cuts.save) to the "keep file extensions" field.
What happened: Files are removed.
What you expected: Should have been moved with the *.ts file. Must be the dot in the extension, but that's needed.

Tried to masquerade the dot with \ but that doesn't work either. Entering only "meta,eit,sc,cuts,save" into the filed all the files are moved to the final location but with the wrong name (e.g. *.meta instead of *.ts.meta).

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
