### ISSUE TITLE
TVDB Not working

### ISSUE THREAD

**Issue by Xebozone** [SickRage/sickrage-issues#1476]
Branch/Commit: VERSION:[7.0.22]
OS: Ubuntu Server
What you did: Added shows
What happened: Cannot add shows, cannot search shows from existing meta data
What you expected: TVDB performs correctly
Logs:
```
HTTP error None while loading URL https://api-beta.thetvdb.com/search/series?name=pure pwnage, Retrying in 3 seconds...
HTTP error None while loading URL https://api-beta.thetvdb.com/search/series?name=my name is earl, Retrying in 6 seconds...
HTTP error None while loading URL https://api-beta.thetvdb.com/search/series?name=bobs burgers, Retrying in 3 seconds...
HTTP error None while loading URL https://api-beta.thetvdb.com/search/series?name=drawn together, Retrying in 3 seconds...
HTTP error None while loading URL https://api-beta.thetvdb.com/search/series?name=man vs wild, Retrying in 3 seconds...


```

Proceeding to the URLs gives me 'Not Authorized" JSON error. SickRage is not really reading the JSON errors, but rather relying on HTTP error codes, I assume (thus why HTTP error is NONE).

Example of the error from TVDB:

{
  "Error": "Not authorized"
}

This has been happening for a long time. I cannot add new shows or update information from existing shows. All searches to TVDB fail.

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
