### ISSUE TITLE
[APP SUBMITTED]: 409 Client Error: Conflict for url: https://api-v2launch.trakt.tv/sync/collection/shows

### ISSUE THREAD

**Issue by AubreyKloppers** [SickRage/sickrage-issues#1477]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.10**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5195b784b76916a2acfe21c1fffd12f837ce0e93
No Log available with ERRORS:
### ERROR
```
TRAKTCHECKER :: Could not connect to Trakt. Code error: 409 [5195b78]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
