### ISSUE TITLE
Sickrage, showing alot of episode as unaired.

### ISSUE THREAD

**Issue by aprillia99** [SickRage/sickrage-issues#1478]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

 SickRage Info:
Branch: master
Commit: 
Version: 2016.07.10-1
Database Version: 44.0
 Python Version: 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
 SSL Version: OpenSSL 1.0.1f 6 Jan 2014
 OS: Linux-4.4.0-24-generic-x86_64-with-Ubuntu-14.04-trusty
 Locale: None.None

I have a few shows that are many seasons and after the most current seasons everything else goes to unaired. i tried force update, mass update and rescan. Ive also adjusted my time from server time, to local time zone and back again and nothing. any thoughts? i put a log below of my last mass update and a photo of what it looks like. 

Thanks!

![sickrage](https://cloud.githubusercontent.com/assets/20538128/16950258/68469954-4d8d-11e6-9029-50e86e2b2bae.png)

![sickragelog](https://cloud.githubusercontent.com/assets/20538128/16950332/b9a3a8be-4d8d-11e6-8707-21b6df075ead.png)

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by duramato** [comment]
Fix air date on tvdb. thats where it gets it from
