### ISSUE TITLE
Adding shows from trakt throws an error when opening the shows in webUI

### ISSUE THREAD

**Issue by Firemogle** [SickRage/sickrage-issues#1480]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Main
OS: Windows 10
What you did: Add shows from Trakt
What happened: Seems to have added, but throws an error when trying to access the shows in the web UI
What you expected:
Logs:
```
File C:\SickRage\SickRage\sickbeard\common.py:586, in __missing__: raise KeyError(key) # ... so the key is invalid KeyError: None
```

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)
