### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by theskillwithin** [SickRage/sickrage-issues#1482]
```
File /apps/sickrage/sickbeard/common.py:586, 
in __missing__: raise KeyError(key) # ... so the key is invalid 
KeyError: None
```

![screen shot 2016-09-12 at 4 53 42 pm](https://cloud.githubusercontent.com/assets/8095506/18456904/9ebef452-7909-11e6-9f68-1298a42f1c2d.png)
![screen shot 2016-09-12 at 4 53 54 pm](https://cloud.githubusercontent.com/assets/8095506/18456906/9ed00030-7909-11e6-9529-20cddef379b4.png)

**Comment by SickRage2** [comment]
This repository is no longer in use for issues or wiki, please use the main repo for [Issues](https://github.com/SickRage/SickRage/issues) and the [Wiki](https://github.com/SickRage/SickRage/wiki)

**Comment by theskillwithin** [comment]
only occurring on newly added show
