### ISSUE TITLE
[APP SUBMITTED]: Thread-27 :: git fetch origin returned : error: Cannot update the ref 'refs/remotes/origin/providers': unable to append to .git/logs/refs/remotes/origin/providers: Permission denied
From https://github.com/SickRage/SickRage
 ! a716b91...e6f4fb1 providers  -> origin/providers  (unable to update local ref)

### ISSUE THREAD

**Issue by gielie** [SickRage/sickrage-issues#152]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@c575707408313497ee391e761f0164fe574a3c6f
Link to Log: https://gist.github.com/fcfecf29dd72c28df306
### ERROR
```
Thread-27 :: git fetch origin returned : error: Cannot update the ref 'refs/remotes/origin/providers': unable to append to .git/logs/refs/remotes/origin/providers: Permission denied
From https://github.com/SickRage/SickRage
 ! a716b91...e6f4fb1 providers  -> origin/providers  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment]
Seems to be a permission problem. 
`Permission denied`
maybe you have run Git/Sickrage with another user.?

**Comment by miigotu** [comment]
Or have used git commands with sudo at some point?
