### ISSUE TITLE
Can't connect to Cpasbien

### ISSUE THREAD

**Issue by cyan** [SickRage/sickrage-issues#157]
heya,
i'm setting up a fresh SR install on a freshly installed raspberry.
my problem is that every time SR search new episode, cpasbien say that there is nothing new while there are lot of season.
it seems there used to be a 'bypasse country blocking mechanism' solution in some previous version but i can seems to find it now :/
thanks for help and your great work on SR :)

**Comment by medariox** [comment]
So you can actually connect to Cpasbien? Could their CloudFlare DDoS protection be the problem?

**Comment by cyan** [comment]
heya,
actually i can from the laptop (using windows) but the raspberry can't connect either the old sickbeard install or the new SR install can't connect but SR just say that it can't find new episode (even if there are 4season available ^^), it could be the DDoS but it seems outside france it can't work, while it work fine in france (i was in france 3month ago) witouth changing anything ;/

**Comment by miigotu** [comment]
@cyan set google dns for the pi

**Comment by duramato** [comment]
@cyan its working fine here ,its probably blocked for you

**Comment by duramato** [comment]
lol

**Comment by cyan** [comment]
heya, what do you mean by setting google dns for the pi? thanks :)

**Comment by miigotu** [comment]
http://bfy.tw/3CCa

**Comment by labrys** [comment]
or http://bfy.tw/3CCf

**Comment by miigotu** [comment]
or http://bfy.tw/9b3

**Comment by cyan** [comment]
thanks for pointing out that i'm a complete noob, but since it's not working is there someone who, without being a dick, can be kind enough to help? thanks

**Comment by miigotu** [comment]
lolz, what OS on your pi?

**Comment by cyan** [comment]
i have a raspberry pi 2 with a raspbian jessie on it( i also have a windows seven on virtualbox doing the same thing :/)

**Comment by miigotu** [comment]
For debian/raspbian: http://raspberrypihell.blogspot.com/2013/08/quick-tip-change-dns-on-raspberry-pi.html

Windows you right click the connection in "network connections" and set a static ip and enter 8.8.8.8 in the dns field.

**Comment by cyan** [comment]
yeah i did those on both but nothing changed even after a full night :/

**Comment by cyan** [comment]
i just tried a free(for 1 month only sadly) vpn and it seems that the connection went trough but couldn't get torrent, the log keep giving 
INFO     SEARCHQUEUE-BACKLOG-255316 :: [Cpasbien] :: Ignoring result elementary.s03e16.french.hdtv because we don't want an episode that is Unknown
(the word "french" was deleted from the forbiden words) and it might the reason why the tvshow "the transporter" was renamed in a wrong way like "the transporter serie.S01e08.avi to The transporter - S01 - E02.avi"

**Comment by miigotu** [comment]
Both of those file names are invalid according to scene standards.

**Comment by labrys** [comment]
@cyan That log message means that it could not determine the quality of the download.  Since your quality settings are not set to include files of unknown quality, it ignores that result.  To determine quality it looks for information such as 720p HDTV itunes etc etc.  For more information about quality settings, see the [wiki](https://github.com/SickRage/SickRage/wiki/Quality-Settings).

**Comment by cyan** [comment]
Thanks labrys, i'm checking this
@Miigotu, well, that's how files are usually named in cpasbien i think :/
