### ISSUE TITLE
Time at the botom of page needs formating

### ISSUE THREAD

**Issue by neoatomic** [SickRage/sickrage-issues#16]
The time shown at the bottom of the page shows 6 numbers micro seconds also.?

![naamloos3](https://cloud.githubusercontent.com/assets/7928052/11269502/9f474132-8eb7-11e5-8bd8-6fc0c322648f.png)

```
SR Version: 	BRANCH: (develop) / COMMIT: (70ba9357c8dac3149405f0bcaf258593fe40fa9d)
SR User:	sickrage
SR Locale:	(None, None)
SR Config:	/usr/local/sickrage/var/config.ini
SR Database:	/usr/local/sickrage/var/sickbeard.db
SR Cache Dir:	/usr/local/sickrage/var/cache
SR Log Dir:	/volumeUSB1/usbshare/Temp
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickrage/var/sickrage.pid', '--config', '/usr/local/sickrage/var/config.ini', '--datadir', '/usr/local/sickrage/var/', '--nolaunch']
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]
```

**Comment by OmgImAlexis** [comment]
@neoatomic what should we be using there? I can add the date element and enable it for fuzzy dates but I'm not too sure if we've got a class or function to convert it to a generic date/time yet.

**Comment by fernandog** [comment]
I added that. Its supposed to check date time with gmt.

**Comment by Amadeus-** [comment]
In main.mako, line 309 (currently), replace:
     Now: <span class="footerhighlight">${datetime.datetime.now(network_timezones.sb_timezone)}</span>

with:
     Now: <span class="footerhighlight">${datetime.datetime.now(network_timezones.sb_timezone).strftime(sickbeard.DATE_PRESET+" "+sickbeard.TIME_PRESET)}</span>

**Comment by OmgImAlexis** [comment]
https://github.com/SickRage/SickRage/pull/103
