### ISSUE TITLE
Preview Rename with ranged episodes (display bug?)

### ISSUE THREAD

**Issue by Rycochet** [SickRage/sickrage-issues#161]
Just added a bunch of old cartoons where they're grouped into multiple episodes per file, but it's displaying each file multiple times for the rename -

![image](https://cloud.githubusercontent.com/assets/290714/11612063/db05f064-9be2-11e5-82d3-8eda6564859a.png)

With that file there's three episodes and it displays twice, with four episodes it displays three times - apart from the display issue it's not causing a problem as files rename correctly (at a guess it's only expecting a two-parter and only removing a second one, rather than checking for multiples and removing all duplicate lines).

**Comment by miigotu** [comment]
Fixed in develop
