### ISSUE TITLE
[APP SUBMITTED]: 'tuple' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by tonyp1983** [SickRage/sickrage-issues#165]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@637d7826ff0a77857661e716c6677b54cf8cdaea
Link to Log: https://gist.github.com/97a0354d70e90b903a2c
### ERROR
```
SEARCHQUEUE-BACKLOG-72248 :: [KickAssTorrents] :: Error while searching KickAssTorrents, skipping: 'tuple' object has no attribute 'endswith'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tonyp1983** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@637d7826ff0a77857661e716c6677b54cf8cdaea
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72248 :: [KickAssTorrents] :: Error while searching KickAssTorrents, skipping: 'tuple' object has no attribute 'endswith'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tonyp1983** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@637d7826ff0a77857661e716c6677b54cf8cdaea
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72248 :: [KickAssTorrents] :: Error while searching KickAssTorrents, skipping: 'tuple' object has no attribute 'endswith'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tonyp1983** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@637d7826ff0a77857661e716c6677b54cf8cdaea
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-167571 :: [Torrentz] :: Error while searching Torrentz, skipping: 'tuple' object has no attribute 'endswith'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
```
01:22:07 DEBUG::SEARCHQUEUE-BACKLOG-72248 :: [KickAssTorrents] :: Search string: Quantum Leap S03
01:22:07 DEBUG::SEARCHQUEUE-BACKLOG-72248 :: [KickAssTorrents] :: Search URL: https://kat.cr/usearch/?q=Quantum+Leap+S03&field=seeders&rss=1&category=tv&sorder=desc
01:22:08 DEBUG::SEARCHQUEUE-BACKLOG-72248 :: [KickAssTorrents] :: Discarding torrent because it doesn't meet the minimum seeders or leechers: Quantum Leap S03e03-04.Mux.Italian English MIRCrew (S:3 L:4)
01:22:08 DEBUG::SEARCHQUEUE-BACKLOG-72248 :: [KickAssTorrents] :: Discarding torrent because it doesn't meet the minimum seeders or leechers: Quantum Leap S03e01 - Ritorno a casa - Parte 1 -[Mux - XviD - Italian English Mp3] MIRCrew [TNT Village] (S:0 L:0)
01:22:08 DEBUG::SEARCHQUEUE-BACKLOG-72248 :: [KickAssTorrents] :: Discarding torrent because it doesn't meet the minimum seeders or leechers: Quantum Leap S03e02 - Ritorno a casa - Parte 2 - The Leap Home [Mux - XviD - Italian English Mp3] MIRCrew [TNT Village] (S:0 L:1)
01:22:10 INFO::SEARCHQUEUE-BACKLOG-72248 :: [KickAssTorrents] :: No needed episodes found during backlog search for: [Quantum Leap]
```

**Comment by miigotu** [comment]
Someone else has had this happen, still cannot reproduce, but surely needs looked into.
