### ISSUE TITLE
Provider login error

### ISSUE THREAD

**Issue by ThomasDK81** [SickRage/sickrage-issues#166]
The HoundDawgs provider is not working of me.
I see a timeout message, I don't understand. The timeout is the settings is set to 30 sec. But the error is immediately. I can visit the url "https://hounddawgs.org/login.php" and it works fine.
"'__str__ returned non-string (type Error)'" could be the key to finding the error?

Other user report, they have errors to, some say it works fine.

Full log after a restart (I can reproduce by doing a manual search):
https://gist.github.com/ThomasDK81/508e3647fc0b3ceee5ed

System:
SR Version:	BRANCH: (master) / COMMIT: (81aa99c0b4bd39fbf333decd6e4f6c155d9401ef) 
SR User:	media
SR Locale:	('en_US', 'UTF-8')
SR Config:	/var/db/sickrage/config.ini
SR Database:	/var/db/sickrage/sickbeard.db
SR Cache Dir:	/var/db/sickrage/cache
SR Log Dir:	/var/db/sickrage/Logs
SR Arguments:	['--datadir', '/var/db/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '-q', '--nolaunch']
SR Web Root:	/sickrage
Python Version:	2.7.9 (default, Sep 9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]

**Comment by duramato** [comment]
Try checking Disable ssl verify

**Comment by ThomasDK81** [comment]
That did the trick, thanks.
Still an issue, right?

**Comment by duramato** [comment]
@ThomasDK81 Not quite ,its becouse the site is using a not secure SSL cerificate and thatthe only way to "bypass" the checks for a valid one
Try asking if they can ugrade their certificate
