### ISSUE TITLE
High CPU usage sickrage on DS212J

### ISSUE THREAD

**Issue by NjayNL** [SickRage/sickrage-issues#167]
Hi Team,

since a few days and after some updates the cpu usage of sickrage just sits on 99 % while doing nothing in the background that i can see. 

i already tried switching off subtitlte search and then rebooting.
It will stay low for a few hours and just go's back up to 99 % 

[logsickrage.txt](https://github.com/SickRage/sickrage-issues/files/53516/logsickrage.txt)

i attached the log for you to look at... it keeps adding items to cache that i don't even have :)

**Comment by miigotu** [comment]
raise your daily search up to 40 minutes.
also, it isn't adding that stuff to the cache, it is updating the cache from RSS, the same as it has always done.
