### ISSUE TITLE
Duplicate results on add new show

### ISSUE THREAD

**Issue by OmgImAlexis** [SickRage/sickrage-issues#170]
The code for searching for years with brackets made it return duplicate results. From memory it was either @Thraxis or @VinceVal that added that.

![screen shot 2015-12-08 at 12 51 33 am](https://cloud.githubusercontent.com/assets/6525926/11629095/ec9ae7da-9d45-11e5-9d95-9c1bdc5e06fe.png)

**Comment by medariox** [comment]
Should only happen with leading articles.
