### ISSUE TITLE
Torrents doesn't start with Shazbat provider

### ISSUE THREAD

**Issue by Jougtde** [SickRage/sickrage-issues#172]
Hi, each time SickRage download a torrent from Shazbat, my torrent don't start and i have to manually pause it and start it again for it to be downloaded. Do you know where it come from ? I have no problem with my other providers.
Thanks !

**Comment by OmgImAlexis** [comment]
@SickRage/moderators

**Comment by neoatomic** [comment]
@Jougtde Please provide all the info as requested here. : 
https://github.com/SickRage/sickrage-issues#before-you-open-an-issue

**Comment by miigotu** [comment]
Without an account or contact to shazbat admin cant help. Ping if that changes and we can re-open.
