### ISSUE TITLE
Sickrage freezes after a day or running

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SickRage/sickrage-issues#18]
Branch: Master

Commit hash: c19526435dc15ba1bcd5827dd24d6a8e69c83e2b (this from the SickRageTV, but it was the final build b4 the switch over to this new one (new Repo))

Your operating system and python version: Mac OS X El Capitan 10.11.1, Python Ver: Python 2.7.10

What you did: unsure i just run sickrage like i normally do: /usr/local/bin/python2.7 ~/Apps/SickRage/SickBeard.py -d &

What happened: about after a day of running and this is consistent BTW, sickrage freezes as in i cannot shut it down, or restart it or when i tell python to quit it won't quit and nothing show in the log no shutdown commands. the Web GUI still works but very limited. update requests still work and browsing still works. but TV show searches etc don't work..

What you expected: to work without out any issues

How can we reproduce your issue: unsure.

i have hard reset Sickrage for that past 4 days in a row & reinstall python, and i am still having this issue as well with deleted cashe. nothing seems to solve the issue and i am unsure why this is happening.

i have also noticed no updates to master since like 1-2 weeks.

maybe a merge with developer will resolve my issue as i am unsure what the exact problem is.

looking from the log it was only caching results from the providers then checking if any new shows where needed from the shows that i have then it just dies around there..

i would say the time frame of running fine is about 12 - 15 hours. my best EST it dies around 5-6 hours later after the "When to update shows" runs at 9AM so around 2PM it died..

sorry no log provided as i cannot pinpoint the error.

**Comment by neoatomic** [comment]
There has been a lot fixed since we switched.
Please test first to confirm this is indeed still a problem with the latest version.

If that is still the case i will reopen it for you.
