### ISSUE TITLE
Visual Glitch: Show list sorting loads unsorted page first

### ISSUE THREAD

**Issue by labrys** [SickRage/sickrage-issues#180]
*OS*: Win 7 x64, Win 10 x64
*Browser*: Chrome, Opera, Internet Explorer, Firefox, Edge
*Branch/Commit*: 
- Dev SickRage/Sickrage@b0b5980f0f87f0bfb078878fb0d7c52bd573ceed
- Master SickRage/Sickrage@81aa99c0b4bd39fbf333decd6e4f6c155d9401ef

##### Observed behaviour
When the show list is sorted in all but Poster view, the browser loads the page first in ascending alphabetical order before sorting or applying filters.  Internet Explorer is also extremely slow to load the page (nearly 10 seconds between initial unsorted list and sorted list).  Firefox and Edge do not appear to have this issue with simple layout, but are affected for other layouts.

##### Expected behaviour
Page should not display content until sorting is completed.

**Comment by Amadeus-** [comment]
I am confirming this bug.

**Comment by OmgImAlexis** [comment]
@labrys I don't actually think this can be fixed as we can't hide items in the table before sorting. The sorting only happens on visible items in tablesorter.

The IE issue may be from it not caching or something similar. Could you run some tests with it and give me a screenshot or dump of the network section from console or whatever IE has.

Firefox and Edge may be loading the DOM in a different order than what Chrome does as neither of them use Webkit from what I remember.

**Comment by labrys** [comment]
I can take a look at it later today, personally I don't think its much of an issue, it was just something brought up in IRC.  

As for the IE being slow to load, that should probably be looked at.  Since I never use IE (except to download a different browser :)) I haven't used the dev console on IE, but I'll take a look at it and see if I can find the info you're looking for.

Possibly related to the sorting error, the Add shows page has a similar visual glitch which resolves once it finishes loading.  The text begins appearing but then the style information gets applied after a short delay.

**Comment by Amadeus-** [comment]
This is the only web-based UI that I have seen that has this glitch in Chrome.   It really makes SR look "amateurish", in my opinion.

I see glitches in chrome in two instances (I'm not sure if they're related):   loading the main page of shows, and when "adding a show".

**Comment by OmgImAlexis** [comment]
@Amadeus- all "glitches" where it's todo with the table loading there's nothing we can do to fix that.

**Comment by OmgImAlexis** [comment]
https://github.com/SickRage/SickRage/commit/33af1be68091c9f5423b96ad2bf9527e71547b5a should help fix a lot of the FOUC that we get.
