### ISSUE TITLE
Custom Quality settings on Add Shows page does not expand Allowed / Preferred selection boxes.

### ISSUE THREAD

**Issue by labrys** [SickRage/sickrage-issues#181]
*OS*: Win 7 x64, Win 10 x64
*Browser*: Chrome, Opera, Internet Explorer, Firefox, Edge
*Branch/Commit*: 
- Dev SickRage/Sickrage@b0b5980f0f87f0bfb078878fb0d7c52bd573ceed
- Master SickRage/Sickrage@81aa99c0b4bd39fbf333decd6e4f6c155d9401ef

##### Observed behaviour
Selecting custom for qualities when adding new shows (Add Show: Step 3 - Customize Options) displays the selection boxes for allowed and preferred qualities but they only show a single line for SDTV.  Switching quality from custom to any other quality hides the Allowed and Preferred boxes but expands the `<div>` leaving a large blank area.  Changing quality again collapses the `<div>.  The only way to properly select custom qualities is to select Custom in the drop-down and then click on the Allowed or Preferred box which will then prompt it to expand.

##### Expected behaviour
When Custom quality is selected, the Allowed and Preferred boxes should appear fully expanded.  When any other quality is selected the section should not expand.

**Comment by fernandog** [comment]
@ishkanan  can you check this ? we moved repo (don't remember If we tagged you here)

**Comment by ishkanan** [comment]
Sure I can take a look tonight.

**Comment by bluezed** [comment]
Have the same issue here... See this screenshot:
![Screenshot1](http://s19.postimg.org/c8xi9hffn/Quality_Add_Show.png)

In addition I have this, probably related, issue...
Add Show from Trakt and click on the "Customize Options" tab at the top. If "Custom" quality is already selected then the "Allowed" and "Preferred" boxes will not disappear when you select a different quality setting. See here:
![Screenshot2](http://s19.postimg.org/rixdgoaxv/Quality_Add_From_Trakt.png)

**Comment by fernandog** [comment]
@ishkanan can you look into this?

**Comment by ishkanan** [comment]
Ah sorry, slipped my mind. I will have to take a look tomorrow.

**Comment by mckinnon81** [comment]
@ishkanan How did you go with this? 

I tried looking but not skilled enough with css and such to find the issue. I am interested to see what was changed to fix it.

Thanks.

**Comment by ishkanan** [comment]
I had a look today. It's got to do with some of the refactoring of the
"quality" mako files I did a while back. Easy to replicate but proving
tricky to fix. Bunker down, it could take me a while.

**Comment by OmgImAlexis** [comment]
By the way this is probably a Javascript issue not CSS, I'll try and look into it tomorrow(today's Christmas).

**Comment by ishkanan** [comment]
@OmgImAlexis here's what I've found so far:

- the import of inc_qualityChooser.mako in inc_addShowOptions.mako should be wrapped in a "<div class="field-pair alt">" like the rest of the file
- I think line 41 in formwizard.js should be "if (i!=this.currentsection && doload)" to properly detect same page and not re-render, but this looks to cause the Search Results to clip

After some testing, I've found the height toggling is inverted (lower height when Custom quality, larger height when single quality), but after refreshing the page sometimes it corrects itself. Next check is line 45 in formwizard.js and work backwards.

Merry Xmas everyone!

**Comment by OmgImAlexis** [comment]
@ishkanan thanks for that.

I'll probably rewrite the stuff that uses formwizard after Christmas anyways. We really shouldn't need another library just for forms.

**Comment by fernandog** [comment]
@ishkanan can you fix his while Omg is on vacation? thanks

**Comment by ishkanan** [comment]
Sorry, I was on holidays as well. I'll do my best to fix it, hopefully
turns out to be trivial.

**Comment by fernandog** [comment]
@dbmandrake as we talked

**Comment by ishkanan** [comment]
@fernandog I have a patch but want your opinion before submitting a PR. I couldn't find why height is miscalculated/inverted but found it is corrected after clicking Prev/Next. After adding this to addShowOptions.js, it corrects the height. User doesn't see the Prev/Next scrolling.

```javascript
$('#qualityPreset').on('change', function() {
    //fix issue #181 - force re-render to correct the height of the outer div
    $('span.prev').click();
    $('span.next').click();
});
```

Tested with other Add/Edit Show screens, no impact to them. Not the best but least intrusive until @OmgImAlexis refactors to not use formwizard.js. Thoughts?

**Comment by fernandog** [comment]
i think @OmgImAlexis should check. I don't know JS/html at all =)

**Comment by labrys** [comment]
@fernandog @ishkanan what do you think about just doing away with the div and leaving it expanded.

**Comment by ishkanan** [comment]
It's a good idea just tricky to implement as it would affect the other two
sections (find show and choose folder). Let's wait for @OmgImAlexis.

@fernandog how about we patch it now so users get normal behavior back and
discuss proper fix when Omg is back?

**Comment by fernandog** [comment]
@ishkanan 
Im ok with that

**Comment by OmgImAlexis** [comment]
SickRage/SickRage#708 looks fine for now.

I'll have at a proper fix soon, trying to get back to this as soon as I can. Been busy with other projects and stuff.
