### ISSUE TITLE
Apply remove_non_release_groups before search for subs

### ISSUE THREAD

**Issue by felipesalomao** [SickRage/sickrage-issues#182]
Min score to download now is 132 points, thats fine, becase we sure that only will download 100% compatible sub, but for example SR snatched and downloaded this file:
Z.Nation.S02E13.720p.HDTV.x264-KILLERS.mkv

then when i tried click on CC to download this subtitle, wasnt possible because this:
Z.Nation.S02E13.720p.HDTV.x264-KILLERS[ettv]

They are exactly same, but SR thinked that Release is wrong because [ettv] and give only 115 points, result = not downloaded
See log: 
2015-12-08 02:44:07 DEBUG FINDSUBTITLES :: [legendastv] Subtitle score for Z.Nation.S02E13.720p.HDTV.x264-KILLERS[ettv].srt (5663a433b7223) is: 115 (min=132)

We need way to ignore [ettv], for example if release of mkv is killers and subtitle is killers(sodijsjsijd203), no problem, if have killers inside subtitle release, just match and ignore rest.. then would avoid this..

I know that subtitler should release with correct name, but it occurs too many times.. We need adapt code to avoid errors..

If any doubt, just contact me..

![fullsizerender 2](https://cloud.githubusercontent.com/assets/2954256/11660880/52cbbe88-9db6-11e5-88e7-065a9f2a4a25.jpg)
![fullsizerender 1](https://cloud.githubusercontent.com/assets/2954256/11660887/57033062-9db6-11e5-994b-a9307b262e3e.jpg)

**Comment by fernandog** [comment]
this needs to be done in the provider, in this case legendas.py.

@ratoaq2

```
from sickbeard.helpers import remove_non_release_groups
new_subtitle_filename = helpers.remove_non_release_groups(subtitle_filename)
```

**Comment by medariox** [comment]
Needs to be done in upstream.

**Comment by duramato** [comment]
@medariox dont think so ,as sr removes the non release groups

**Comment by fernandog** [comment]
@duramato this is for the feature "download subtitles in PP" folder together with "postpone PP if no subtitles"

**Comment by medariox** [comment]
@duramato 
What @fernandog said, it's just for postponed subs in PP folder (files will get renamed before the PP now, for better subs match).

**Comment by fernandog** [comment]
that PR don't fix the issue when video filename don't have non release group in name BUT subtitle filename has.  Only the other way around

**Comment by felipesalomao** [comment]
@ratoaq2 
Could you remove non release groups before search for subs for legendas.tv ?

This way it will avoid match error..
Z.Nation.S02E13.720p.HDTV.x264-KILLERS[ettv].srt 
would be changed to:
Z.Nation.S02E13.720p.HDTV.x264-KILLERS.srt

It must ignore [ettv], if not, wont have enough 132 points score to download subtitle, because, it think that release is KILLERS[ettv] instead KILLERS, so it do not download.. @fernandog suggested solution, but said that only you could change that..

Thank you !

**Comment by ratoaq2** [comment]
This is another general issue that could affect any provider. The name is parsed by guessit, and guessit is not guessing the release group properly:

```
guessit "Z.Nation.S02E13.720p.HDTV.x264-KILLERS[ettv].mkv"
For: Z.Nation.S02E13.720p.HDTV.x264-KILLERS[ettv].mkv
GuessIt found: {
    "title": "Z Nation",
    "season": 2,
    "episode": 13,
    "screen_size": "720p",
    "format": "HDTV",
    "video_codec": "h264",
    "release_group": "KILLERS[ettv]",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

I would first try to open an issue in the guessit project because it would be the cleanest solution and will work for all providers. They have already fixed the country issue (US, UK) in guessit 2.
