### ISSUE TITLE
SSL certificate weirdness

### ISSUE THREAD

**Issue by andyj682** [SickRage/sickrage-issues#186]
I run SR on Synology. Switched over to the new repo a few days ago but was having issues with updates, so just reinstalled the SynoCommunity package with the new repo address. All went well; installed the latest master branch; except that now I can't seem to get SR to use the SSL certificate for my domain. After restoring, I recopied my certificate and key into the SR dir, changed the permissions, verified that everything's right in SR config, but the web interface still seems to be serving me up the certificate signed by "SickRage" instead of the one for my domain. 

Any idea what's going on? Could this be some issue introduced in the last couple days, or did something weird happen when I reinstalled? The certificate is working fine for all the other apps I use (and was working fine for SR up until a couple hours ago), so don't think it's a bad SSL install or anything.

ETA: Bunch of SSL errors in the log, too--it's [here](http://pastebin.com/vScbuZ63).

**Comment by OmgImAlexis** [comment]
@SickRage/moderators

**Comment by neoatomic** [comment]
@andyj682 I just enabled https on my Synology for Sickrage. All working fine, no errors in the log etc.
I dont have a commercial cert so cant test that, but should be no difference.
Try to shutdown SR and remove the cache/sessions & mako folders. Maybe there is still old info in there.

@OmgImAlexis Please stop pinging every1 and tagging issues without reply...

**Comment by andyj682** [comment]
@neoatomic Really, really weird. Tried doing a fresh install and enabling SSL (without even trying to give it the commercial cert) and got the same errors. Just for fun tried the old repo, too, and it errored out just trying to generate the default certs (i.e. couldn't even turn SSL on if I wanted to). Wonder if I have to completely uninstall the comercial cert from the NAS and try again, or something? 

Mostly just bizarre because it worked like a charm until I tried reinstalling the package.

**Comment by neoatomic** [comment]
@andyj682 Can it be that a device is trying connection with http instead of https.? Or maybe a permission issue of the cert files.?
As i cant replicate the problem, its extremely hard to troubleshoot...

**Comment by andyj682** [comment]
@neoatomic Yeah, I mean, clearly it's something that went wonky on my end. It's connecting with https, just always showing the SickRage-generated cert even though the third-party ones are there (and yeah, permissions are right). It's not a huge deal; just perplexing, since I have no idea what uninstalling/reinstalling the Synology package could have done to break SSL only for SickRage (and not for CouchPotato, NZBGet, etc. etc.).

**Comment by miigotu** [comment]
Go to `/config/` and check the SR Arguments line, its highly likely your certs are being loaded from a different location than you expect.

**Comment by andyj682** [comment]
@miigotu You mean the data dir? It's the one where the certs are (/usr/local/sickrage/var/), which is where config.ini is telling it to look for them. Weird thing is that when I switch on SSL for the first time even before I copy over my own certs, it won't even generate the default ones--yet I can still load the SSL interface with the default cert issued to "SickRage." Which makes me think it really is loading them from somewhere else (otherwise wouldn't the SSL connection just not work at all?). Anyway, I guess I'll just give up and turn off SSL. It's only a minor bummer, but still have no idea why this would be suddenly not working on SR when it's working fine for all the other apps I use.

**Comment by miigotu** [comment]
The keys dont go in the data dir, but in the dir with the source.
 
```python
            'https_cert': ek(os.path.join, sickbeard.PROG_DIR, sickbeard.HTTPS_CERT),
            'https_key': ek(os.path.join, sickbeard.PROG_DIR, sickbeard.HTTPS_KEY),
```

**Comment by andyj682** [comment]
@miigotu Welp, I'm an idiot. Was that always where they went? I swear they used to go in the data dir. Anyway, that fixed it.

**Comment by miigotu** [comment]
yep, always been there =¶

**Comment by ryansully** [comment]
I'm also running SR on Synology, and there is a line at the bottom of the config page that reads:

All non-absolute folder locations are relative to /usr/local/sickbeard-custom/var

Should the code be updated to reflect that path?
