### ISSUE TITLE
[APP SUBMITTED]: 404 Client Error: Not Found for url: https://api-v2launch.trakt.tv/shows/0388635/progress/watched

### ISSUE THREAD

**Issue by tunisiano187** [SickRage/sickrage-issues#187]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1e2995459b809d7f47765a998e9b91a8d369f5dd
Link to Log: https://gist.github.com/8fb8d4150f5a393394e3
### ERROR
```
TRAKTCHECKER :: Trakt error (404) the resource does not exist: https://api-v2launch.trakt.tv/shows/0388635/progress/watched
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fernandog** [comment]
@Thraxis seems trakt changed their API

**Comment by tunisiano187** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1e2995459b809d7f47765a998e9b91a8d369f5dd
Link to Log: https://gist.github.com/ab425eb3ed25a31596ec
### ERROR
```
TRAKTCHECKER :: Trakt error (404) the resource does not exist: https://api-v2launch.trakt.tv/shows/0388635/progress/watched
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tunisiano187** [comment]
Sorry for the last comment.
Can you tell me how to find the serie attached?
I didn't find it on thetvdb, neither in sickrage
Thank you

**Comment by tunisiano187** [comment]
I find out the problem.
The show was "Petit ours brun". it is on IMDb but not on thetvdb.
The id that is on the previous record is the number when i went to http://www.imdb.com/title/tt0388635/
I suppose that it can be an issue with that but i have removed it from my sickrage and i suppose it will be good from now.

Thanks again for the help and the short time to respond....

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-39-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **develop**
Commit: SickRage/SickRage@45a2b1e580afbc01429a0bfd3e384a8f0f102ebe
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error 4
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
wtf why did it commented here oO the title was ```TORNADO :: API :: error 4```
