### ISSUE TITLE
Migrate from server X to Y and issue with tornado/web.py

### ISSUE THREAD

**Issue by stanthewizzard** [SickRage/sickrage-issues#188]
Hello

I have restored from a backup

At start, I got this when I try to access Sickrage

Traceback (most recent call last):
  File "/home/nzb/sickrage/lib/tornado/web.py", line 1390, in _execute
    result = self.prepare()
  File "/home/nzb/sickrage/lib/tornado/web.py", line 2103, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found

Help wouldbe appreciated :)

**Comment by miigotu** [comment]
make sure you are accessing with the right url, http or https.

**Comment by stanthewizzard** [comment]
OK

server2:8082/sickrage

forget the /sickrage

Working
thanks for the tip
