### ISSUE TITLE
[APP SUBMITTED]: Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/263365/en.xml: error('Error -3 while decompressing data: invalid distance too far back',)

### ISSUE THREAD

**Issue by jahhernandez** [SickRage/sickrage-issues#189]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.3.0-10-osmc-armv7l-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1e2995459b809d7f47765a998e9b91a8d369f5dd
Link to Log: https://gist.github.com/59455a2bac58d2f27a85
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/263365/en.xml: error('Error -3 while decompressing data: invalid distance too far back',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jahhernandez** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.3.0-10-osmc-armv7l-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1e2995459b809d7f47765a998e9b91a8d369f5dd
Link to Log: https://gist.github.com/21e630f0dcff99344267
### ERROR
```
POSTPROCESSER :: Unable to connect to theTVDB while creating meta files - skipping - error Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/263365/en.xml: error('Error -3 while decompressing data: invalid distance too far back',)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thraxis** [comment]
@miigotu This looks like it's just a case of TheTVDB being down using the regular Indexer code.

**Comment by miigotu** [comment]
yep

**Comment by jahhernandez** [comment]
Thanks for the input, but the main problem that I have is that once this error happens the auto post process is no longer active, meaning that sickrage cannot process the directory with the downloads, also is there any way to turn the post process on? normally what I do is restart sickrage.

**Comment by fernandog** [comment]
Should we try:except continue ?

**Comment by fernandog** [comment]
@jahhernandez a possible fix in develop branch

**Comment by jahhernandez** [comment]
@fernandog Thank you very much for your help
