### ISSUE TITLE
Post-Processing With Sab, NZBtoMedia constantly failing to Process

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SickRage/sickrage-issues#19]
Branch: Master
Commit hash: c19526435dc15ba1bcd5827dd24d6a8e69c83e2b (From SickRageTV, final build b4 the move to new Repo)
Your operating system and python version: OS X El Capitan, V 10.11.1
Python Ver: Python 2.7.10
What you did: Nothing its all Automated
What happened: fails to process, it thinks it has Already Processed but it didn't...
What you expected: to work without issues!
How can we reproduce your issue: Unsure

ok I'm not sure what the issue is here but these are starting to happen very often:
SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!
this is very frustrating...

this what i get from the nzbtomedia log:

Log: https://gist.github.com/XxUnkn0wnxX/27e4d0df18383a80b51f

Notice the errors.. no idea.. 1st one it thinks it already proceed this one some other error...

all of these errors give me the: SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.! error and it doesnt clean up or process it as a failed download.. same goes for successful downloads as well...

to the best of my knowledge to reproduce this is to download and manually process a episode before the NZB download process then you get that error.

as for shows that are being replaced with better quality or when i manly mass select multiple failed snatched episode they also seem to fail randomly... once downloaded..

**Comment by XxUnkn0wnxX** [comment]
would much appreciate if support for SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.! could be resolved. Issue, EG if it has already been downloaded and when Sab tries to process it. simply let sickrage delete the download and don't bother downloading a new one if it has been already downloaded/processed.

also if it gets "is the same size as" error and causes sickrage not process it, i'd recon it should delete it and set the downloaded episode to success or if it is a better quality that was downloaded and it is the same size it should replace it without question... or treat it as a failed download and auto try again for another download...

as for when marking multiple episodes to failed maybe allow the user to select the options for multiple episodes like when doing it with one episode function:

![image](https://camo.githubusercontent.com/957242e34dfaf078c51c5996ea6f21a92783d854/687474703a2f2f7075752e73682f6c6d5037752e706e67)

**Comment by neoatomic** [comment]
Added the additional info for mac users to the wiki.
Thanks for providing @XxUnkn0wnxX 

https://github.com/SickRage/sickrage-issues/wiki/Installation-&-Configuration-Guides#mac

**Comment by miigotu** [comment]
"would much appreciate if support for SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.! "

Fixed.
