### ISSUE TITLE
[APP SUBMITTED]: must be unicode, not str

### ISSUE THREAD

**Issue by oconnellkj** [SickRage/sickrage-issues#191]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@1e2995459b809d7f47765a998e9b91a8d369f5dd
Link to Log: https://gist.github.com/6036b27d09e109e89ca9
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: must be unicode, not str
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by oconnellkj** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@1e2995459b809d7f47765a998e9b91a8d369f5dd
Link to Log: https://gist.github.com/1430f412226fafe0e2c0
### ERROR
```
Thread-24 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files\SickRage\sickbeard\webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\Program Files\SickRage\sickbeard\webserve.py", line 2247, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "C:\Program Files\SickRage\sickbeard\processTV.py", line 224, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\Program Files\SickRage\sickbeard\processTV.py", line 552, in process_media
    result.result = processor.process()
  File "C:\Program Files\SickRage\sickbeard\postProcessor.py", line 1158, in process
    ep_obj.createMetaFiles()
  File "C:\Program Files\SickRage\sickbeard\tv.py", line 1838, in createMetaFiles
    self.createNFO()
  File "C:\Program Files\SickRage\sickbeard\tv.py", line 1849, in createNFO
    result = cur_provider.create_episode_metadata(self) or result
  File "C:\Program Files\SickRage\sickbeard\metadata\generic.py", line 260, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "C:\Program Files\SickRage\sickbeard\metadata\tivo.py", line 326, in write_ep_file
    nfo_file.write(data.encode("utf-8"))
TypeError: must be unicode, not str

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fernandog** [comment]
@Labrys know how to fix this?

**Comment by oconnellkj** [comment]
I don't know if it's related or not... post-processing used to run through
all the files in the designated directory...

Now it stops after the first file it finds, though it does seem to work
fine on that one file...

I have to manually re-run post processing for each file now

As I am consolidating my library... from multiple sources, this really is
painful

**Comment by labrys** [comment]
@fernandog Pretty sure I know, but I won't be able to look at it till tomorrow, it's my daughter's birthday today.

**Comment by fernandog** [comment]
congratulations to her! enjoy the day!

**Comment by duramato** [comment]
@labrys Happy Birthday to her ! :)

**Comment by labrys** [comment]
Thanks, she turns 16 today.  Going to pick her up from school now.

**Comment by miigotu** [comment]
@oconnellkj disable the tivo metadata and try again. Might have to leave that disabled until I can push a fix later.

**Comment by oconnellkj** [comment]
Done, and it's working now... many thanks :)

**Comment by ronlipke** [comment]
:+1: Thank you! Been driving me nuts lately.

**Comment by miigotu** [comment]
@ronlipke was yours also tivo or was it another meta provider?

**Comment by ronlipke** [comment]
It was tivo.  As soon as I unchecked episode metadata, automatic post-processing started working again without any problems.

**Comment by miigotu** [comment]
Test and let me know if it doesnt fix the tivo metadata, thanks.

**Comment by ronlipke** [comment]
Works great for me, thanks for the fix!
