### ISSUE TITLE
Auto Post-Processing not working

### ISSUE THREAD

**Issue by CYR4N0** [SickRage/sickrage-issues#193]
I've been having to manually post-process for the past month or so. It was working fine then all of a sudden stopped and I didn't make a changes in the settings at the time. I am not seeing any errors in the logs either. This started when I was still on the previous repo and has persisted since I switched over to this repo.

**Comment by labrys** [comment]
@CYR4N0 If you could please submit required information as per our [submission guidlines](https://github.com/SickRage/sickrage-issues), it would be much appreciated.

**Comment by miigotu** [comment]
Try disabling your metadata providers.... Let me know if that works.

**Comment by CYR4N0** [comment]
@miigotu I don't currently have metadata enabled as I have Plex handle that.

@labrys I enabled debug logs and will update this with the logs after some of the scheduled downloads are finished later this evening.

**Comment by labrys** [comment]
@CYR4N0 please include the OS, Python version, and commit when you do. Thanks! :grinning:

**Comment by zarxic** [comment]
I'm having this issue as well.  I'm running BRANCH: (master) / COMMIT: (4da36fb1c4fde840cb5ddae0da65fdb56a31c2d0) on Windows 10, Python 2.7.5.  I'm using SABnzbd 0.8.0beta1.  I'm using the nzbToMedia scripts.  I've attached the log.  It seems like when the script calls to SickRage, it's returning the HTML code.  I have verified that I can get to SickRage with the settings in the nzbToMedia autoProcessMedia.cfg file.  I'm not sure what changed along the way, but my manual post processing does work.

[nzbtosickbeard.txt](https://github.com/SickRage/sickrage-issues/files/58470/nzbtosickbeard.txt)

**Comment by unZane** [comment]
If nzbToMedia gets HTML code in return from SickRage it is probably the same problem that has been reported to nzbToMedia (https://github.com/clinton-hall/nzbToMedia/issues/898) and is fixed in the nzbToMedia nightly build and can be fixed by manually editing the following files in nzbToMedia: https://github.com/kri99/nzbToMedia/commit/198796e8b4e28937106b40f81d36820220fa358e

**Comment by miigotu** [comment]
if that's an issue then you aren't on our repo, or you aren't updated. ours should work just fine with latest master of nzbtomedia

**Comment by unZane** [comment]
Aah I see :P I had the same issue before I switched repo, and can comfirm that this repo works just fine with the latest master of nzbtomedia... my bad

**Comment by miigotu** [comment]
(This also means that users are reporting issues with the other repo to ours)

**Comment by CYR4N0** [comment]
Closed?

**Comment by CYR4N0** [comment]
...I guess I'll open a new one since this isn't resolved. I was planning on adding the requested info after some more episodes came up this evening. I am on currently on your repo from about a week or so?! and I haven't seen any difference.

I'm currently using Python 2.7.10, Windows 10 and on BRANCH: (master) / COMMIT: (97cd0fd633581154fb1ef43f3d2c2c0cc4609ebb)

**Comment by miigotu** [comment]
Auto post processing works fine (hence the sterile), and you still haven't provided the requested information (hence the "Need more info")

Every complication a user might face doesnt merit a place on the issue tracker unless it is a bug.
In this instance it is almost certainly a source origin quality deficiency or a configuration comprehension limitation.
