### ISSUE TITLE
Shows stay as wanted

### ISSUE THREAD

**Issue by martinuk5** [SickRage/sickrage-issues#195]
I logged on today and have 5 shows all saying wanted, i left it 2 hours and they still havent downloaded. I seem to have to press each show manually everyday to download anything
is there a settings im missing? shouldnt wanted shows automatically download after amount of time?

**Comment by neoatomic** [comment]
@martinuk5 All is working fine for me...

Please provide all the info requested here. https://github.com/SickRage/sickrage-issues#before-you-open-an-issue

**Comment by labrys** [comment]
@martinuk5 also make sure you have new episodes listed as wanted and not skipped, ignored, etc.
