### ISSUE TITLE
[APP SUBMITTED]: time data 'al (imdb display ti' does not match format '%Y-%m-%d %H:%M:%S'

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#196]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.3.0-11-osmc-armv7l-with-debian-8.2**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@bee0c5878d3348169dbc2f6e03ffbf2405dbe7dd
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Exception generated in thread FINDSUBTITLES: time data 'al (imdb display ti' does not match format '%Y-%m-%d %H:%M:%S'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fernandog** [comment]
Logs:

@medariox 

```
2015-12-10 23:52:54 DEBUG    FINDSUBTITLES :: 'Traceback (most recent call last):\n  File "/home/osmc/SickRage/sickbeard/scheduler.py", line 105, in run\n    self.action.run(self.force)\n  File "/home/osmc/SickRage/sickbeard/subtitles.py", line 458, in run\n    now - datetime.datetime.strptime(ep_to_sub[\'lastsearch\'], dateTimeFormat) >\n  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime\n    (data_string, format))\nValueError: time data \'al (imdb display ti\' does not match format \'%Y-%m-%d %H:%M:%S\'\n'
AAValueError: time data 'al (imdb display ti' does not match format '%Y-%m-%d %H:%M:%S'
AA    (data_string, format))
AA  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
AA    now - datetime.datetime.strptime(ep_to_sub['lastsearch'], dateTimeFormat) >
AA  File "/home/osmc/SickRage/sickbeard/subtitles.py", line 458, in run
AA    self.action.run(self.force)
AA  File "/home/osmc/SickRage/sickbeard/scheduler.py", line 105, in run
AATraceback (most recent call last):
2015-12-10 23:52:54 ERROR    FINDSUBTITLES :: Exception generated in thread FINDSUBTITLES: time data 'al (imdb display ti' does not match format '%Y-%m-%d %H:%M:%S'
2015-12-10 23:52:54 INFO     FINDSUBTITLES :: Downloaded pob subtitles for The Originals S02E07
```

**Comment by fernandog** [comment]
@medariox how that string got into the field?!

![image](https://cloud.githubusercontent.com/assets/2620870/11742641/9c14b64c-9fe8-11e5-923a-f1a2c1d835c4.png)

**Comment by labrys** [comment]
Maybe that is related to the issue I was talking about in IRC.

**Comment by medariox** [comment]
I would suggest we replace the current fix_subtitles_codes() with something like this: https://gist.github.com/medariox/98aeaae5dc925b73c862
calling it fix_invalid_subtitles() maybe? This is a very basic approach to fix borked subtitles_lastsearch entries.

**Comment by fernandog** [comment]
FINDSUBTITLES is dead lol. not running

![image](https://cloud.githubusercontent.com/assets/2620870/11744127/c68b39ee-9ff4-11e5-9d4e-87eff3132d03.png)

**Comment by miigotu** [comment]
@medariox instead find how that is being corrupted.

**Comment by medariox** [comment]
@miigotu 
It's probably from some very old SR version that had some even worse sql code, I'm quite sure it won't get corrupted as of the current SR version. That code only fixes corrupt entries that got corrupt with old versions.

**Comment by fernandog** [comment]
Are we going to add sanity check for that?
Like @medariox gist

https://gist.github.com/medariox/98aeaae5dc925b73c862

**Comment by miigotu** [comment]
no need, because when it is found it will be fixed and saved correctly in the subtitle finder
