### ISSUE TITLE
Issue with this

### ISSUE THREAD

**Issue by stanthewizzard** [SickRage/sickrage-issues#197]
2015-12-11 11:20:25 Thread-47 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/nzb/sickrage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/home/nzb/sickrage/sickbeard/webserve.py", line 4316, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/home/nzb/sickrage/sickbeard/providers/newznab.py", line 128, in get_newznab_categories
    for category in data.caps.categories.findAll('category'):
AttributeError: 'NoneType' object has no attribute 'categories'

**Comment by OmgImAlexis** [comment]
Please use the submit button built into SickRage, it's there for a reason.

**Comment by fernandog** [comment]
@stanthewizzard need to add github user/pass in SR settings to submit errors using the button

**Comment by stanthewizzard** [comment]
@fernandog ... I did it and it doesn't work :/

**Comment by labrys** [comment]
Also please wrap log output in ```.  It makes it much easier to read.  I have done it for you this time.

**Comment by stanthewizzard** [comment]
@labrys Thank you very much

**Comment by stanthewizzard** [comment]
@fernandog 
After reading the link to #148 
I already switched to the new repo without "He-Who-Must-Not-Be-Named"

**Comment by fernandog** [comment]
lol - you were in the old repo??

**Comment by stanthewizzard** [comment]
no
not at all ... but in the link the issue comes from the old repo ...
