### ISSUE TITLE
Findsubtitle process checking unecessary epsodes and missing necessary epsodes

### ISSUE THREAD

**Issue by felipesalomao** [SickRage/sickrage-issues#199]
Commit: 95c505af05e3a06cbb0515d0e18a1a8b43c11b05 (Latest)
Branch: Develop
QNAP ARM 219P II

Hi, as talked with @fernandog 
I have 5 epsodes that subtitle is pending, 2 of those epsodes already have available subtitles.. Homeland S05E09 and Homeland S05E10.. 
Problem is that it isnt downloading automatically subtitles 

Its strange, i stoped SR, cleaned logs and started it again.. It start FINDSUBTITLES thread automatically.. It checked if hundreds of old epsodes already has subtitles (they have and it is registered on SR DB), but it does not check all, i have 1344 epsodes downloaded, it checked 324 epsodes, so, it does not checked if both Homeland S05E09 and Homeland S05E10 need subtitle.. Have something wrong with this, it should check only if manage missed subtitles already have available subtitles, not check hundreds epsodes (missing a lot of epsodes)..

Here is Full Log:
https://gist.github.com/felipesalomao/7a27671768736753da3e

Here is TV Show Page:
![fullsizerender 7](https://cloud.githubusercontent.com/assets/2954256/11745963/b32c88ea-a002-11e5-9119-82280ae3e334.jpg)

Manage Missed Subtitles (5 pending subs including Homeland S05E09 and Homeland S05E10):
![img_6135](https://cloud.githubusercontent.com/assets/2954256/11746069/30984986-a003-11e5-8303-156edc0bda9e.JPG)

and here name of Video Files (Homeland S05E09 and Homeland S05E10):
![fullsizerender 8](https://cloud.githubusercontent.com/assets/2954256/11746009/e1036054-a002-11e5-8033-cf7ad138e076.jpg)

I have 1344 epsodes downloaded and FINDSUBTITLES only checked 324 epsodes (missing a lot):
![img_6139](https://cloud.githubusercontent.com/assets/2954256/11745517/dad45858-9fff-11e5-8828-5a266e457b13.JPG)
![img_6151](https://cloud.githubusercontent.com/assets/2954256/11745518/dad58264-9fff-11e5-8a3a-39cb3bd27b27.JPG)

Then after wait 5 minutes, i decided click on CC button to it make manual subs search for specific epsode, it downloaded perfectly within seconds with max score of 136 points..

Here is photos showing manual sub download (including log):
![img_6141](https://cloud.githubusercontent.com/assets/2954256/11745540/07c75c2a-a000-11e5-98b6-50345a3f4544.JPG)
![img_6142](https://cloud.githubusercontent.com/assets/2954256/11745542/0b826e72-a000-11e5-877d-994063b424c3.JPG)
![img_6150](https://cloud.githubusercontent.com/assets/2954256/11745545/11076960-a000-11e5-8b39-513c26b8e310.JPG)

Subtitle Settings:
![fullsizerender 5](https://cloud.githubusercontent.com/assets/2954256/11745483/9ebfd888-9fff-11e5-9ba0-efa594094533.jpg)
![fullsizerender 4](https://cloud.githubusercontent.com/assets/2954256/11745484/9ec05c22-9fff-11e5-8fc8-79ec20443659.jpg)
![fullsizerender 6](https://cloud.githubusercontent.com/assets/2954256/11745482/9ebfb880-9fff-11e5-8e17-b4c870401e92.jpg)

**Comment by medariox** [comment]
Sadly can't reproduce this.

**Comment by felipesalomao** [comment]
@medariox 
This is normal, check if 324 files already has subtitle, it wouldnt check only if epsodes of manage missed subtitles (only 5 epsodes) is available ? Do you have an idea what could be ?

**Comment by medariox** [comment]
I got the issue behind this. Am working on a fix.

**Comment by felipesalomao** [comment]
@medariox look this. is showing BR flag below the "None". also the title is weird

"Episodes without Portuguese (undefined) subtitles

![image](https://cloud.githubusercontent.com/assets/2954256/11747465/8256d1d2-a00a-11e5-9cf0-3c4686864277.png)

**Comment by medariox** [comment]
That's because you have a subtitle there with language code pt-BR. You have to remove the pt-BR from the name. You have to be consistent. Either you use multi language or you don't.

**Comment by fernandog** [comment]
also he doesn't have this:

![image](https://cloud.githubusercontent.com/assets/2620870/11747557/060b4f6c-a00b-11e5-8ab6-0c91006db615.png)


only 'Portuguese' and it points to : /manage/subtitleMissed?whichSubs=und 

instead of /manage/subtitleMissed?whichSubs=pob like mine

**Comment by fernandog** [comment]
opening /manage/subtitleMissed?whichSubs=pob shows this:

![image](https://cloud.githubusercontent.com/assets/2620870/11747634/830d0c8a-a00b-11e5-8614-854928693eca.png)

**Comment by labrys** [comment]
@felipesalomao Might I suggest [Lightshot](https://app.prntscr.com/en/index.html) for screencaps in the future?  It allows you to screencap all or just a defined portion of the screen and either save locally or to the web.

**Comment by miigotu** [comment]
Find subtitles does not search for every missing subtitle forever.

It tries to search for the subtitle 2 times in the first 7 days, and then 7 more times over the next week, and then never again automatically. Otherwise it would spam the providers.

**Comment by felipesalomao** [comment]
@medariox 
I do not have pt-br on name, it added brazil flag because Sr downloaded subtitle.. I haven't lang on any subtitle name..
The problem is related und, and pob as @fernandog posted here.. I see last commits.. Had some updates.. But problem existing und subtitle continues.. I already tried full refresh and rescan files.. 
For example, I have all subtitles for homeland, when I open und on manage missed subtitles, it show that I do not have any pending subs for this show, but if I open pob, it say that I have 58 pending subs.. It's like do not recognize v (without flag) as subtitle download.. And it'd impossible make it show brazil flag.. Only if I would add pt-br in srt subtitle name (i think if I make it) and rescan, all would appear brasil flag and would disappear all pending subs in pob manage missed subtitles..

Problem for sure is related this und / pob showed by @fernandog..

@medariox 
Did you finished all fixed that you think that could fix it?

Thank you

**Comment by miigotu** [comment]
If single subs are used (without a language tag) then they will never show a flag. We cannot and will not make the assumption that an untagged sub is some specific language.

**Comment by felipesalomao** [comment]
@miigotu 
I think you do not understood.. See bug posted by @fernandog here.. I dont want brazil flags for subs without pt-br in name.. Problem is that it create some kind of different language when don't have brazil flag (und).. It show missed subtitles for subtitles that i already have and made rescan files without success.. I only am able to acess und subs by gui (selected Portuguese), then editing link changed und for pob and was able to see that have some kind of 2 languages (und for subtitles without brazil flag and pob for subs with brazil flag), as all my subs name don't have pt-br, I have problem and it think that I don't have any português subtitles.. It's bug that @fernandog see (team viewer), he can tell you better.. 
And also @medariox said that is working on a fix.. 

Please, if possible m, reopen thread..

See entire posts and photos 

If any doubt, just contact me 

Thanks

**Comment by miigotu** [comment]
that bug is fixed, and released to master already.

**Comment by felipesalomao** [comment]
Strange.. When it was fixed? I updated and not see any change, it's fixed on develop branch too? I need only update or need make something more?

**Comment by felipesalomao** [comment]
@miigotu 
I tested here, updated to latest commit on master.. Error continues..

See 

Only one language option (Portuguese)
![image](https://cloud.githubusercontent.com/assets/2954256/11760285/d87dd75a-a07c-11e5-9bff-b2622358a657.png)

It opens that URL when I select Portuguese:
192.168.1.113:7073/manage/subtitleMissed?whichSubs=und
Photo: 
![image](https://cloud.githubusercontent.com/assets/2954256/11760290/15caaf0c-a07d-11e5-8804-6869826d3072.jpeg)

Then if I change end to pob on URL like this:
192.168.1.113:7073/manage/subtitleMissed?whichSubs=pob
It show several missed subs that already has subtitle..
Photo: 
![image](https://cloud.githubusercontent.com/assets/2954256/11760296/56c2dff2-a07d-11e5-97eb-c507e54a01b1.jpeg)

I already tried rescan files and full refresh, but seems like impossible make tv show as not appear on missed subs..

I don't know about download process, if continue with problem, could not test it yet, will need wait until next subtitle release to see logs and see if it found subs on first scan after sub published on provider..

**Comment by miigotu** [comment]
if you are not using multi subs, ALL EPISODES WILL ALWAYS BE MISSING POB.

**Comment by felipesalomao** [comment]
Not understood.. I need enable download more than one language like pob and eng? That doesn't make too much sense for me.. How I could fit that, what I need to do exactly? Thank you

**Comment by miigotu** [comment]
192.168.1.113:7073/manage/subtitleMissed?whichSubs=und <- this is the url for the episodes missing subtitles when you are not using MULTI_SUBS option. It is correct.

**Comment by medariox** [comment]
@felipesalomao 
Please don't change url to something you think is right. If we do something it has its reasons. With multi languages unchecked (your case) the url must be subtitleMissed?whichSubs=und, because the subtitles language in the file name can't be determined. The only subs you seem to be missing are 3 of Minority Report. If you are sure the subs should be there, try a show refresh. Otherwise you have to manually download them in the show page, as they most probably won't download as the show is too old/too many days passed/too many searches for subs already/etc.

**Comment by fernandog** [comment]
@medariox yes ^^

**Comment by felipesalomao** [comment]
Ok.. There is not subs for this show now.. Subtitlers left show.. My doubt is about new show scans.. Will need wait until next subtitle release to see how it will scan, if will find sub on first scan after published on subtitle provider
