### ISSUE TITLE
SickRage Subtitle's disables after each update & Newznab search categories still has blank boxes

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SickRage/sickrage-issues#20]
Branch Master
commit ac5ccd7fec056ae974f9913f7685978dac2b1ec6
Your operating system and python version: Mac os EL Capitan Ver 10.11.1, Python Ver: Python 2.7.10

after every update this keeps happening: ![](http://puu.sh/lreZX.png) and some time's after a restart
Only log i have for this is this:
15-11-20 03:36:15 FINDSUBTITLES :: Not enough services selected. At least 1 service is required to search subtitles in the background

and as for Newznab search categories, still not fixed after the update & there is no log to go with this.

![](http://puu.sh/lreZe.png)

even after re adding the provider manually this issue still persists..

**Comment by adaur** [comment]
@OmgImAlexis maybe a JS issue?

**Comment by OmgImAlexis** [comment]
@adaur I can have a look tomorrow. I believe it may be a js issue. A lot of the config pages were playing and I think I've got them all working now in dev. I don't use a lot of the features that broke so most of it was hard to actually test as I didn't really know what to expect from it all.

@alisonatwork maybe we need to add some Javascript unit tests?

**Comment by miigotu** [comment]
Pretty sure this is fixed (categories is, and subtitles work here), ping if not.

**Comment by fernandog** [comment]
it happened to me too now

**Comment by labrys** [comment]
I wonder if this is related:  When DOG went down for daily updates, I started getting:
```
2015-11-24 15:58:13 WARNING  Thread-41 :: Error getting xml for [http://nzb.is/api?apikey=**********&t=caps]
2015-11-24 15:58:13 WARNING  Thread-41 :: Connection timed out accessing getURL http://nzb.is/api?apikey=**********&t=caps Error: u"error HTTPConnectionPool(host='nzb.is', port=80): Read timed out. (read timeout=30)"
2015-11-24 15:55:56 WARNING  Thread-40 :: Error getting xml for [http://nzb.is/api?apikey=**********&t=caps]
2015-11-24 15:55:56 WARNING  Thread-40 :: Connection error to getURL http://nzb.is/api?apikey=**********&t=caps Error: u"error ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))"
2015-11-24 15:55:00 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
```
Which is odd becaus I don't even use nzb.is

**Comment by duramato** [comment]
@labrys also got the exact same lines

**Comment by miigotu** [comment]
That's just because you went to the provider options when it was down. Totally separate from the OP and  it can be ignored.

**Comment by labrys** [comment]
No problem, but why is it attempting nzb.is when that isnt even one of my active providers?

**Comment by miigotu** [comment]
Not sure, js loads that method that gets caps, maybe it needs to check if it is active first (I could also simply return inside the _get_newznab_categories method if the provider is not enabled but I think thats a bandaid)

**Comment by fernandog** [comment]
Check your config. Is that provider enabled?

**Comment by labrys** [comment]
disabled:
```
[NZB_IS]
nzb_is = 0
nzb_is_search_mode = eponly
nzb_is_search_fallback = 0
nzb_is_enable_daily = 1
nzb_is_enable_backlog = 1
```

**Comment by fernandog** [comment]
That is odd. We never had problem with providers like this

**Comment by miigotu** [comment]
The caps wasnt working AT ALL. Dont say things that make it sound like we are breaking stuff, more than half of SR was rewritten within the last month.

**Comment by felipesalomao** [comment]
I am getting it too.. It disable Legendas.tv subtitle provider automatically.. But I not use nzb, only torrent.. How solve it?

Not enough services selected. At least 1 service is required to search subtitles in the background

**Comment by miigotu** [comment]
Both of these issues are fixed here @felipesalomao

**Comment by felipesalomao** [comment]
How fixed ? My version is more updated possible and it happened 30 minutes ago.. Whats i need to do to fix ?

**Comment by miigotu** [comment]
@felipesalomao have you switched your install over to the repo in this new organization? we are nearing 1000 new commits since we moved to this new Org.
https://github.com/SickRage/SickRage/pull/202

**Comment by felipesalomao** [comment]
Not.. Continued old oficial repo.. How switch? I am on Qnap ARM..
Do you know if I can update using list of commands in putty?

Em sexta-feira, 27 de novembro de 2015, miigotu <notifications@github.com>
escreveu:

**Comment by miigotu** [comment]
@felipesalomao Im not sure if we have a way for that yet, let's see if anyone can help you...
@SickRage/collaborators @SickRage/moderators 

@clinton-hall Is there any possibility to get your qnap packages updated to be able to use our new url?

**Comment by felipesalomao** [comment]
Thank you so much, qpkg or at least list of commands need for QNAP would be really great.. There so much people that use Qnap NAS and i not found any tutorial showing how update to this new fork..

**Comment by fernandog** [comment]
@felipesalomao the subtitle provider being disabled is a known issue. fixed in DEV afaik

**Comment by miigotu** [comment]
fixed in master.

**Comment by felipesalomao** [comment]
I see.. Problem is that i still use oficial repo.. And seems that this new fork is better, But i dont know how upgrade to this fork.. I already nade it using gitclone commands in the past (about 2 years ago), But i dont remember what was commands used (was simple, about 2 or 3 commands only)..

**Comment by labrys** [comment]
If you have access to git its pretty easy.  Try following the steps in #3, and let us know how it goes.

**Comment by felipesalomao** [comment]
Done ! that was simple.. thanks.. 
Only 1 tip i would like to know, in subtitle setings  have this option: Subtitle Find Frequency: 1
It means that it will look for subtitles every 1 hour ? If yes, its possible look for subtititles each 30 minutes,Subtitle Find Frequency: 0.5 would work ? Thank you very much
