### ISSUE TITLE
Mysterious "subtitle score" prevents subtitles from being downloaded

### ISSUE THREAD

**Issue by anonvoy** [SickRage/sickrage-issues#201]
For some time now (one or two) weeks I have noticed that SR downloads few subtitles and if it does, only from Thesubdb. I have activated Addic7ed, Podnapisi and Tvsubtitles as well (in that order, followed by Thesubdb), and until said one or two weeks ago, subtitle download (of subtitles in English) from all 4 worked fine.

Now it seems that SR does find subtitles, but does not download them. Or only some of them. For example, here's a log excerpt:

```2015-12-11 22:17:21 DEBUG    Thread-62 :: 95491: No subtitles downloaded for The Vampire Diaries S07E08```
```2015-12-11 22:17:21 DEBUG    Thread-62 :: [tvsubtitles] Subtitle score for 299745 is: 117 (min=132)```
```2015-12-11 22:17:21 DEBUG    Thread-62 :: [tvsubtitles] Subtitle score for 299744 is: 117 (min=132)```
```2015-12-11 22:17:21 DEBUG    Thread-62 :: [podnapisi] Subtitle score for 7LY- is: 121 (min=132)```
```2015-12-11 22:17:21 DEBUG    Thread-62 :: [podnapisi] Subtitle score for N7g- is: 124 (min=132)```
```2015-12-11 22:17:20 DEBUG    Thread-34 :: 95491: No subtitles downloaded for The Vampire Diaries S07E09```
```2015-12-11 22:17:20 DEBUG    Thread-34 :: [tvsubtitles] Subtitle score for 300116 is: 117 (min=132)```
```2015-12-11 22:17:20 DEBUG    Thread-34 :: [podnapisi] Subtitle score for 8MY- is: 120 (min=132)```
```2015-12-11 22:17:16 DEBUG    Thread-34 :: 95491: Downloading subtitles for The Vampire Diaries S07E09```
```2015-12-11 22:17:15 DEBUG    Thread-62 :: 95491: Downloading subtitles for The Vampire Diaries S07E08```

So subtitles **are** found on podnapisi and tvsubtitles, but not downloaded. "Subtitle scores" from 117 to 124 are named, and also a minimum score of 132 apparently needed.

Subtitles on Addic7ed are apparently not found at all, though they are definitely available there and work fine with the video files.

So: What is happening here? What is this mysterious "subtitle score" that apparently stops subtitles from being downloaded? Can it be disabled, or at least the necessary "minimum" set to a lower value? And why are Addic7ed subtitles not even found anymore?

**Comment by fernandog** [comment]
This score is to match: show name + season + episode + source + release group.

The min score to dont download a out of sync sub.
In develop we added a setting to reduce the score to 111 BUT you may get out of sync subs

**Comment by anonvoy** [comment]
Is this new? I can't remember seeing it until now, and as I wrote it worked fine before.

Also, score or not, it doesn't explain the not found subtitles on Addic7ed. Which were definitely found and downloaded "before".

**Comment by labrys** [comment]
Yes this is new, as @fernandog mentioned, the score will be able to be adjusted soon.

**Comment by medariox** [comment]
@anonvoy 
Did you add your login credentials for addic7ed?
The option is new and you will be able to download subs with lower score in the next master release.

**Comment by fernandog** [comment]
If you dont mind out of sync subs just disable the new setting we have in develop "Subtitles perfect matches"

**Comment by ward0** [comment]
is this in master already pls? I don't see option to change to 111

**Comment by duramato** [comment]
@ward0 It is , perfect match on sub settings

**Comment by ward0** [comment]
@duramato , I have this problem because of this change : https://github.com/SickRage/sickrage-issues/issues/611

I'm looking for this subtitle : http://www.opensubtitles.org/nl/search/sublanguageid-dut/imdbid-5211576

I get these logs :
"
2016-01-24 21:51:18 DEBUG    Thread-42 :: [opensubtitles] Subtitle score for 1955042192 is: 119 (min=132)
2016-01-24 21:51:18 DEBUG    Thread-52 :: [opensubtitles] Subtitle score for 1955049547 is: 121 (min=132)
2016-01-24 21:51:18 DEBUG    Thread-42 :: [opensubtitles] Subtitle score for 1955042194 is: 121 (min=132)"

**Comment by duramato** [comment]
Did you disabled the option i mentioned?

**Comment by ward0** [comment]
Yes i did , and its downloading , but how can i tell what download he did ? he KILLERS one? or the other one?

**Comment by duramato** [comment]
The logs should tell you

**Comment by ward0** [comment]
@duramato Sorry but not getting extra log info also no debug info ( debug mode is enabled ).

I don't know why its saying 121 instead of 132 because the name and everything is the same and it worked before.

**Comment by medariox** [comment]
@ward0 
What is the video file called and what is the subtitle called on the subtitle provider **exactly**?

**Comment by ward0** [comment]
Video file name : Chicago.PD.S03E10.720p.HDTV.x264-KILLERS[ettv].mkv(https://extratorrent.unblockme.co/torrent_files/4631725/Chicago.PD.S03E10.720p.HDTV.x264-KILLERS%5Bettv%5D.html)
Sub provider name : Chicago.PD.S03E10.HDTV.x264-KILLERS[ettv].mp4 ( http://www.opensubtitles.org/nl/search/sublanguageid-dut/imdbid-5211576)

aha! sub provider using .mp4 and video file is mkv ...

How can i resolve this problem pls?

**Comment by medariox** [comment]
@ward0 
Download the correct release? These are two different releases...
Chicago.PD.S03E10.***720p***.HDTV.x264-KILLERS[ettv].mkv
Chicago.PD.S03E10.HDTV.x264-KILLERS[ettv].mp4

**Comment by ward0** [comment]
@medariox  So the uploader for the subtitle is not following the correct quality preset then?

https://github.com/SiCKRAGETV/SickRage/wiki/Quality-Settings

If i change my quality for PD to SDTV i should get the MP4 file ?

**Comment by medariox** [comment]
@ward0 
There is just no NL subtitle for Chicago.PD.S03E10.720p.HDTV.x264-KILLERS[ettv].mkv on OpenSubtitles. So either you download the SD version by changing your quality, or you download the WEB-DL version (Chicago.PD.S03E10.720p.WEB.DL.DD5.1.H.264-MOLY).
