### ISSUE TITLE
ERROR: '_socketobject' object has no attribute 'set_tlsext_host_name'

### ISSUE THREAD

**Issue by funkyslap** [SickRage/sickrage-issues#202]
Hi guys, just switched to new repo and SickRage show me this error:

```
2015-12-11 23:01:42 INFO     SEARCHQUEUE-MANUAL-295515 :: [NBZPlanet] :: Unable to find a download for:
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 295, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 250, in connect
AA    conn.connect()
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 782, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
AA    body=body, headers=headers)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
AA    timeout=timeout
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 376, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 468, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 480, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1440, in getURL
2015-12-11 23:01:42 WARNING  SEARCHQUEUE-MANUAL-295515 :: [NBZPlanet] :: Traceback (most recent call last):
2015-12-11 23:01:42 WARNING  SEARCHQUEUE-MANUAL-295515 :: [NBZPlanet] :: Unknown exception in getURL https://www.nzbplanet.net/api?apikey=**********&tvdbid=295515&season=1&maxage=6&cat=5030%2C5040&q=Quantico&limit=100&t=tvsearch&offset=0&ep=10 Error: "'_socketobject' object has no attribute 'set_tlsext_host_name'"
2015-12-11 23:01:41 INFO     SEARCHQUEUE-MANUAL-295515 :: [NBZPlanet] :: Performing episode search for Quantico
```

**Comment by miigotu** [comment]
@clinton-hall any chance of a package updated for this version of SR?

**Comment by labrys** [comment]
@funkyslap please wrap your logs in ``` as it makes it much easier to read.  I have done it for you this time.  Also if you could please follow the guidelines here https://github.com/SickRage/sickrage-issues#before-you-open-an-issue and include information such as OS, Python version, Commit etc.  Thanks :grinning:

**Comment by funkyslap** [comment]
@labrys you're right sorry. Here you are:

QNAP TS-212
OS Version: 4.1.4 build 20150910
Python 2.7 (r27:82500, Aug 21 2010, 10:10:43)
OpenSSL 1.0.1p 9 Jul 2015

SickRage installed from this .qpkg by @clinton-hall
http://forum.qnap.com/viewtopic.php?f=223&t=35015

**Comment by clinton-hall** [comment]
I have an updated qpkg that removes the modules and checks for latest Python.
I still need to fix the dependency checks and add an option/tag to select which SockRage fork to use (I am trying to avoid the fork debate, and let users choose).

**Comment by labrys** [comment]
@clinton-hall sounds fair

**Comment by labrys** [comment]
### hehe *SockRage*  ###

![Sock Rage](http://ragecomics.com/-img/4ed98399186133045d00d350.png?w=480&h=360)

**Comment by funkyslap** [comment]
@clinton-hall that's a good news! can't wait :+1: thank you

**Comment by bouwew** [comment]
I have the same problem as mentioned above.
I am running a TS-419P with Clinton-Hall's Sickrage, Python 2.7.10 (Entware-ng-version) and have pyOpenssl 0.15.1 installed.

**Comment by miigotu** [comment]
@bouwew remove pyOpenSSL.

**Comment by bouwew** [comment]
@miigotu 
Thanks!
Did that, makes no difference though, still showing the same error.
Why remove pyOpenssl? I thought v0.15.1 was required for this? That's what I remember from the previous discussion before this issue-list disappeared for a short time.
I had it working for some time with pyOpenssl 0.13.1, but some weeks ago it stopped working, so I tried to get v0.15.1 to compile.

**Comment by miigotu** [comment]
Also is something about the arm folder in `/share/MD0_DATA/.qpkg/SickBeard-TVRage/` iirc. Either way this is not a SR issue it is the package/environment, so you will have to wait until @clinton-hall or someone else can release a new package. @ricebus ?

**Comment by bouwew** [comment]
Ok, thanks! I'll wait :)

**Comment by ricebus** [comment]
@bouwew, could you run this command from shell for me please:
`python -c "import ssl; print ssl.OPENSSL_VERSION"`

**Comment by funkyslap** [comment]
@ricebus @bouwew 

[/share/MD0_DATA/.qpkg/Python/bin] # ./python -c "import ssl; print ssl.OPENSS>
OpenSSL 1.0.1p 9 Jul 2015
[/share/MD0_DATA/.qpkg/Python/bin] #

**Comment by bouwew** [comment]
My result: OpenSSL 1.0.2d 9 Jul 2015

**Comment by miigotu** [comment]
You need to install python 2.7.9-2.7.11 and remove pyOpenSSL, or 2.7.3-2.7.8 with pyOpenSSL working.

**Comment by bouwew** [comment]
I have Python 2.7.10 installed, and no pyOpenssl.
I do have the packages python-openssl (2.7.10-6a) and libopenssl ( 1.0.2d-1) installed.
Verify SSL Certs in SickRage is unticked.
Still the same error as above.

**Comment by miigotu** [comment]
python-openssl IS pyOpenSSL

**Comment by bouwew** [comment]
Removed the python-openssl package.

Result of  python -c "import ssl; print ssl.OPENSSL_VERSION" now is:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl

Starting Sickrage throws the same error:
Starting SickBeard-TVRage
Traceback (most recent call last):
  File "SickBeard.py", line 50, in <module>
    import ssl
  File "/opt/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl

So, that doesn't work.

**Comment by miigotu** [comment]
python --version

**Comment by bouwew** [comment]
Python 2.7.10

**Comment by miigotu** [comment]
none of that nonsense works correctly. that python 2.7.10 was not compiled with ssl support.

**Comment by ricebus** [comment]
try using the python package from http://apps.qnap.community/

**Comment by bouwew** [comment]
Have installed ricebus' Python package.
``` python -c "import ssl; print ssl.OPENSSL_VERSION"
```
gives
```
OpenSSL 1.0.1p 9 Jul 2015
```

**Comment by bouwew** [comment]
Testing with SickRage still shows the same error as above :(

**Comment by miigotu** [comment]
The sickrage qpkg is not using the right version of python on the system. Read up about the coming update to the qnap package
This IS NOT a sickrage issue.

**Comment by bouwew** [comment]
Ok, thanks for your support!
I'll wait for clinton-hall's update.

**Comment by fernandog** [comment]
can someone confirm if the updated as made?

**Comment by MrAdam** [comment]
Also want to know if any update is one the way on this? - SickRage is pretty useless at the moment :-)

**Comment by clinton-hall** [comment]
https://github.com/SickRage/sickrage-issues/issues/297#issuecomment-167408876

Try the updated package posted there...

**Comment by labrys** [comment]
Closing this since package has been updated.  If this issue persists after the update, let us know and we'll reopen it.

**Comment by MrAdam** [comment]
Tried installing the 2.7.10 package from apps.qnap.community, but the new updated package from @clinton-hall won't find the correct version of Python:

```
[~] # /etc/init.d/sickbeard-tvrage.sh restart
armv5tel
Restarting SickBeard-TVRage
armv5tel
Shutting down SickBeard-TVRage...
SickBeard-TVRage is not running?
armv5tel
SickBeard-TVRage prestartup checks...
 Checking for git...  Found!
Looking for /usr/bin/python2.7
Looking for /usr/local/bin/python2.7
Looking for /opt/bin/python2.7
Looking for /Apps/opt/bin/python2.7
Looking for /opt/QPython2/bin/python2.7
Found Python Version 2.7.5 at /usr/local/bin/python2.7
Updating SickBeard-TVRage
HEAD is now at 475db54 Merge branch 'develop'
Already up-to-date.
Starting SickBeard-TVRage
Traceback (most recent call last):
  File "SickBeard.py", line 26, in <module>
    import codecs
ImportError: No module named codecs
```

**Comment by labrys** [comment]
@MrAdam have you tried the fixes mentioned in #297?

**Comment by MrAdam** [comment]
I tried adding the path to the 2.7.10 version of Python in the package script, which got it working.
Now the problem is, that CouchPotato won't start with that version of Python installed..

**Comment by labrys** [comment]
Sounds like a CouchPotato problem now :grinning:

**Comment by MrAdam** [comment]
I don't quite agree, as it is sickrage that needs a special version of python, and won't work with the official one 😉

**Comment by clinton-hall** [comment]
Argh... Can you email me the details of Python package, QNAP model, SickRage app and CouchPotato app?...

I feel I am loosing the battle here. I need one current, stable Python app with full module support on all QNAP models...

**Comment by labrys** [comment]
@MrAdam that was meant as a joke :)

**Comment by clinton-hall** [comment]
@MrAdam.
The real issue is at the base... Python.
Official app is about 4 years old and does not have important (SSL) security fixes... New versions are not official and don't include all needed modules.

On a PC the module issue is simply fixed with pip, or apt-get etc... But on an embedded system without compile (gcc) tools, this is a problem.

I should be able to fix CP to use new Python qpkg... But I still have issues with SickRage and newest Python on some QNAP models...

**Comment by MrAdam** [comment]
@clinton-hall I see, sounds like a dependency hell :+1:
So, would it be too difficult to include an embedded version of Python? (I know it would require lots of work, as you would probably need one package for each system)

Regarding the software I'm using:
Python: http://apps.qnap.community/11-community/20-python-community-2
QNAP: TS-112
SickRage: https://www.dropbox.com/s/j1svazqdi9ieq82/SickBeard-TVRage_151227.qpkg
CouchPotato: https://www.dropbox.com/s/q1zgst6tstoonls/CouchPotato2_141108.qpkg

Regards, Adam.

**Comment by miigotu** [comment]
I think the first step should be to figure out which ones do and dont work.

http://apps.qnap.community/11-community/20-python-community-2 (@ricebus arm)
http://apps.qnap.community/11-community/16-python-community (Qnap_Stephanie, intel)

**Comment by MrAdam** [comment]
@clinton-hall Haven't done any QPKG development myself, but wouldn't it be great if we could create a Python package that is linked to a GitHub repository, with one branch for each CPU architecture?
Then people would have the latest python (latest from the repo), and missing dependencies for the popular packages could be added to that repository?

Regards, Adam.

**Comment by masterxdk** [comment]
I have the same issue as mentioned by OP.

Is there coming a package that actually works with doing to much work in SSH?

The QPKG's on QNAP's forum are all old and out of date.

Does the package in the #297 thread work completely?

Its properly @clinton-hall i need to ask?

My errors:
`2016-01-18 08:37:00 SEARCHQUEUE-MANUAL-74709 :: [NZBs.org] :: Unknown exception in getURL https://nzbs.org/api?apikey=2826a14124e91dfe645470e2e3d5de56&tvdbid=74709&season=28&maxage=3&cat=5030%2C5040&q=Cops+S28E23&limit=100&t=tvsearch&offset=0&ep=23 Error: "'_socketobject' object has no attribute 'set_tlsext_host_name'" [af9a7fd]
2016-01-18 08:37:00 SEARCHQUEUE-MANUAL-74709 :: [NZBs.org] :: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1442, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 782, in _validate_conn
    conn.connect()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 250, in connect
    ssl_version=resolved_ssl_version)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 295, in ssl_wrap_socket
    cnx.set_tlsext_host_name(server_hostname)
AttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
 [af9a7fd]`

Hardware Info:
Hardware: QNAP TS-453Mini
OS: 4.2.0 Build 20151118

SickRage info:
`Version:	Branch: master
Commit: af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
Version: v5.1.2
User:	admin
Locale:	Language: en_US
Encoding: UTF-8
Configuration File:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/config.ini
Database:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/sickbeard.db
Cache Directory:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache
Log Directory:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/Logs
Arguments:	['--daemon', '--datadir', '/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config', '--pidfile', '/tmp/SickBeard-TVRage.pid', '--nolaunch']
Python Version:	2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]`

**Comment by ozhan99** [comment]
Even though this issue is closed, I wanted place an update.

I also had the same problem as OP. My problem eventually got solved by reinstalling Git.
