### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by FrancisHG** [SickRage/sickrage-issues#203]
Great job with this new repo.

I would like to request a new feature: the option to override quality checking, and use file-sizes instead.

One example: I have a file with 1080p quality, SickRage downloads another 1080p quality.

The first one was ~160 MB, the new one is ~830 MB. I would like this larger file to replace the old one, however because the quality is the same SR marks it un-safe to replace.

**Comment by FrancisHG** [comment]
Oh, and here is the log from a manual Post-Proc:



Processing folder C:\RemoteAccess\NASAccess\ProductionBuffer\TV\South.Park.S19E10.PC.Principal.Final.Justice.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN
Processing C:\RemoteAccess\NASAccess\ProductionBuffer\TV\South.Park.S19E10.PC.Principal.Final.Justice.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN\South.Park.S19E10.PC.Principal.Final.Justice.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN.mkv (None)
Found result in history: ('indexerid: 75897\nindexer: 1\nname: South Park\nlocation: C:\\RemoteAccess\\NASAccess\\TV\\South Park\nnetwork: Comedy Central\nairs: Wednesday 10:00 PM\nstatus: Continuing\nstartyear: 1997\ngenre: |Animation|Comedy|\nclassification: Scripted\nruntime: 25\nquality: 22053372\nscene: False\nsports: False\nanime: False\n', 19, [], 64, -1)
Retrieving episode object for 19x10
Snatch history had a quality in it, using that: 1080p WEB-DL
Is ep a priority download: False
Snatch history had a version in it, using that: v-1
File C:\RemoteAccess\NASAccess\TV\South Park\Season 19\S19E10 - PC Principal Final Justice.mkv is smaller than C:\RemoteAccess\NASAccess\ProductionBuffer\TV\South.Park.S19E10.PC.Principal.Final.Justice.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN\South.Park.S19E10.PC.Principal.Final.Justice.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN.mkv
File exists and new file is the same or lower quality than existing, marking it unsafe to replace
Processing failed for C:\RemoteAccess\NASAccess\ProductionBuffer\TV\South.Park.S19E10.PC.Principal.Final.Justice.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN\South.Park.S19E10.PC.Principal.Final.Justice.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264-YFN.mkv:

**Comment by OmgImAlexis** [comment]
For FEATURE REQUESTS use [Feathub](http://feathub.com/SickRage/SickRage).

**Comment by labrys** [comment]
@FrancisHG and please wrap logs in ``` as it makes them much easier to read. I have done it for you this time. Thanks :)
