### ISSUE TITLE
Migration Guide and Information

### ISSUE THREAD

**Issue by syrys** [SickRage/sickrage-issues#206]
So, i have been using sickrage for about a year now, and recently came across all the internal issues and restructuring you guys have had. Assuming i havent done any changes to my installation, im likely still on the original repo, so i would like some instructions on how to safely migrate my library to this new repo and to have some info about what to expect. Sorry, i know you guys are having issues, but as an end user, i would like to hear some re-assurance that im not making a mistake by swaping over to the new repo, or if i should ditch SR entirely and maybe go back to sickbeard even.

Anyway, my current installation is on windows 10, and i used the following installer to get it up and running: https://github.com/SiCKRAGETV/sickrage-issues/wiki/SickRage-Windows-Installer
I just need to know what steps i need to take to back everything up and migrate to the new repo.

As for the reason im swapping over, i cannot rely on a open source product that is managed by a single person (life gets in the way, but its unfair for the end users to suffer when life gets in the way of the ONLY developer). At the same time, there have been couple of bugs on the master branch of the main repo that was not fixed in couple of weeks and has not really been addressed (to be fair, one of the developers here may have likely caused the bug, haha). 

Please also inform me if this following bug exists in this repo also: https://sickrage.tv/forums/forum/help-support/bug-issue-reports/31066-post-process-not-happening-unicodedecodeerror

Cheers.

**Comment by fernandog** [comment]
@syrys no

**Comment by syrys** [comment]
@fernandog was that answer "no" meaning: "no, that issue on the linked page (unicode decode error) does not exist in the new repo"?

Cheers.

**Comment by fernandog** [comment]
No. We dont have that unicode issue

**Comment by syrys** [comment]
@fernandog im assuming you guys dont have a straight forward enough guide i can use to migrate to this repo? Do you know somewhere i can look or anyone i can ask?

**Comment by miigotu** [comment]
@syrys First let me say i did not cause that unicode error =P I was working on a migration to full unicode `in develop` when all of this shnazz went down, and had been working on a PR to complete it even after the move. ech decided to merge that PR that was nowhere near complete, and then subsequently merge to master and break SR for everyone.

Now as for your question, its really simple to switch over.

1. With the old SR running, go to `localhost:port/config/backuprestore/` and backup to somewhere outside of the SR installation.
2. Shutdown the SR service
3. Use add/remove programs and uninstall the old version, then go into C:\ and make sure the SR installation has been removed. If it has not rename or delete it
4. Use the newest version of the same installer you used before: https://github.com/VinceVal/SickRageInstaller/releases/latest (there is actually a 0.5 version to be released soon, but 0.4 will do just fine)
5. Once installed and SR is started, go again to `localhost:port/config/backuprestore/` and restore the backup you created in (1).

Enjoy.

**Comment by syrys** [comment]
@miigotu awesome, thanks for the detailed instructions. I do have 1 question though. Does the backup/restore also backs up (and restores) the configs (torrent provider settings, post process settings, download folders etc)?

**Comment by miigotu** [comment]
yes

**Comment by syrys** [comment]
@miigotu 
Awesome, i will give those instructions a go later tonight or tomorrow. Thanks so much for the help. 

On another note, sucks that you guys had huge issues with the management. No offence to either party, but im choosing this repo purely because i cannot rely on a one man show for a product i rely on (and obviously, this branch is much further ahead and not completely broken haha). Saying that though, i would still recommend you guys to be the better man and just make it into a different competing product, otherwise you might have very confused end users going (WTF, SRTV / SR?). Change it to something like SickMedia or something different entirely (slightly offset the theme so end users wont be confused, and its a very easy task anyway), and provide maybe a means/guide for people easily to migrate from SR (echelon's repo), same way that SR has a migration guide from SickBeard.

Cheers, keep up the good work :)

**Comment by miigotu** [comment]
https://github.com/SickRage/sickrage-issues/issues/3
https://github.com/SickRage/sickrage-issues/issues/26

**Comment by syrys** [comment]
Awesome, thanks @miigotu, i will flick some suggestions there later. Will update here if i have any issues with the migration :)
