### ISSUE TITLE
Usenet-crawler Ssl certificate

### ISSUE THREAD

**Issue by tunisiano187** [SickRage/sickrage-issues#212]
Hello,
The certificate for the usenet-crawler.com website has been changed.
The new one is valid from 12-12-15 to 13-12-16.
Can anyone tell me how to change it in the database?

Thank you

**Comment by duramato** [comment]
@tunisiano187  It isnt stored localy afaik ,only when acessing UC so it should auto update..

**Comment by tunisiano187** [comment]
is there a way to force the update?
I tryied to reboot the sickrage app but still the same

**Comment by neoatomic** [comment]
The new Cert for usenet-crawler.com seems to be working fine again.
Sickrage doesn't give an error anymore, and my browser also doesn't complain anymore.

So if you are still getting the error than its probbebly a local issue.
Try to shutdown SR and remove the cache/sessions & mako folders. And then restart.

**Comment by neoatomic** [comment]
Need to correct myself. The Cert. still doesn't work. :( 
Daily search trows an error. : 

`[Usenet-Crawler] :: Connection error to getURL https://www.usenet-crawler.com/api?apikey=**********&maxage=4&cat=5030%2C5040&limit=100&t=tvsearch&offset=0 Error: u'error ("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')],)",)' `

**Comment by tunisiano187** [comment]
Thanks it seems to be working.

**Comment by tunisiano187** [comment]
Sorry, it doesn't work... like you, i was thinking it was okbut not...

**Comment by Thraxis** [comment]
As I'm unable to actually bring up the site in a web browser I'm going to presume the site itself is down.

**Comment by labrys** [comment]
@Thraxis the site is not down, although the cert was still invalid last i checked.

**Comment by miigotu** [comment]
Cert probably will take a bit to propagate through their cloudflare, as well as through various CA.

It is however, now using TLS 1.2, so the same dependencies for tpb and kat now apply to usenet-crawler

**Comment by doczong** [comment]
Just an FYI guys.  SAB 7.0.20 is broken.  Same SSL issue.

However, this is a SAB issue, and in no way related to any version of SR/SB or CP.

Put this in your sabnzbd.py, right after the comments, starting at line 18:
```
opt_out_of_certificate_verification = True
if opt_out_of_certificate_verification:
    try:
        import ssl
        ssl._create_default_https_context = ssl._create_unverified_context
    except:
        pass

**Comment by labrys** [comment]
@doczong thanks for the heads up

**Comment by fernandog** [comment]
we don't have sabnzbd.py anymore - we use nzbtomedia

**Comment by doczong** [comment]
@fernandog - no, you need to edit the SABZNBD python script, this is nothing to do with post processing.  It is here just for an FYI to all.

**Comment by fernandog** [comment]
@doczong 
we don't have sabnzbd.py in our repo. that's what I'm saying.

**Comment by neoatomic** [comment]
This had noting to do with Sabnzbd. Usenet-Crawler simply had a bad Cert setup for there website.
However they have fixed it now, so all should be working fine again.  For me it is. :  


``` 
2015-12-17 10:48:38 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Search url: https://www.usenet-crawler.com/api?apikey=**********&maxage=4&cat=5030%2C5040&limit=100&t=tvsearch&offset=0
2015-12-17 10:48:40 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Attempting to add item to cache: Christmas.Through.the.Decades.Part4.The.90s.720p.HDTV.x264-DHD
2015-12-17 10:48:40 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Unable to parse the filename Christmas.Through.the.Decades.Part4.The.90s.720p.HDTV.x264-DHD into a valid show
2015-12-17 10:48:40 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Attempting to add item to cache: Galis.S01E45.PDTV.XviD-Yonidan
2015-12-17 10:48:40 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Unable to parse the filename Galis.S01E45.PDTV.XviD-Yonidan into a valid show 
```

**Comment by labrys** [comment]
@neoatomic @fernandog he's saying that SAB has an SSL issue totally unrelated to SR and this issue and thats the fix for it.

**Comment by tunisiano187** [comment]
The solution proposed upper doesn't worked for me  so i've searched an other and i found this

In newswrapper.py, I replaced each
`self.nntp.sock.sendall(command)`
with
`self.nntp.sock.sendall(command.encode('ascii', 'ignore'))`
