### ISSUE TITLE
[APP SUBMITTED]: 4

### ISSUE THREAD

**Issue by duramato** [SickRage/sickrage-issues#22]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-33-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@a266e6becef9d16ee894464982c0c14cb2e77fab
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error 4
```

```
AAKeyError: 4
AA    episode_qualities_counts_download[int(row["status"])] += 1
AA  File "/home/home/SickRage/sickbeard/webapi.py", line 2709, in run
AA    curOutDict = func(curArgs, curKwargs).run()
AA  File "/home/home/SickRage/sickbeard/webapi.py", line 207, in call_dispatcher
AA    outDict = _call_dispatcher(args, kwargs)
AA  File "/home/home/SickRage/sickbeard/webapi.py", line 130, in get
AATraceback (most recent call last):
2015-11-19 14:23:55 ERROR    TORNADO :: API :: error 4
2015-11-19 14:23:55 DEBUG    TORNADO :: API :: show.stats: curKwargs {'indexerid': '248742'}
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
@duramato you seem to have an episode with a bad status of just "Downloaded"
