### ISSUE TITLE
No subtitle flags in /config/subtitles

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#24]
@OmgImAlexis JS issue?

@duramato confirm please?

**Comment by duramato** [comment]
![image](https://cloud.githubusercontent.com/assets/10121067/11304117/6f5cf998-8f9e-11e5-9bd1-4d072e60c3b3.png)

**Comment by OmgImAlexis** [comment]
I'm still not sure what part of the js broke to remove the flags. I'm looking into this.

**Comment by fernandog** [comment]
@OmgImAlexis any clue?

**Comment by OmgImAlexis** [comment]
Still haven't had a chance to look into this, I'll get back to it eventually but honestly it's a really low priority as it's just a visual thing.

**Comment by miigotu** [comment]
Fixed in develop

**Comment by fernandog** [comment]
Thanks
