### ISSUE TITLE
/js/new/schedule.js Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#25]
as title

@OmgImAlexis

**Comment by fernandog** [comment]
Also for history.js

/js/new/history.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by OmgImAlexis** [comment]
@fernandog those are just old files that need their reference removed from the mako files. All of the code that use to be in them is in `core.js`.
