### ISSUE TITLE
[APP SUBMITTED]: Thread-25 :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/hotfix-nn-entries: Permission non accord?e
From https://github.com/SickRage/SickRage
 ! 43525ec..425b3c6  hotfix-nn-entries -> origin/hotfix-nn-entries  (unable to update local ref)

### ISSUE THREAD

**Issue by gormson** [SickRage/sickrage-issues#27]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ac5ccd7fec056ae974f9913f7685978dac2b1ec6
Link to Log: https://gist.github.com/72bb185ee365e8a73cf6
### ERROR
```
Thread-25 :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/hotfix-nn-entries: Permission non accord?e
From https://github.com/SickRage/SickRage
 ! 43525ec..425b3c6  hotfix-nn-entries -> origin/hotfix-nn-entries  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gormson** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ac5ccd7fec056ae974f9913f7685978dac2b1ec6
Link to Log: https://gist.github.com/4c2287e1069b8a27819c
### ERROR
```
CHECKVERSION :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/hotfix-nn-entries: Permission non accord?e
From https://github.com/SickRage/SickRage
 ! 43525ec..425b3c6  hotfix-nn-entries -> origin/hotfix-nn-entries  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Something about your permissions fubar somehow, maybe you did git commands with sudo at some point?
```
cd SickRage
sudo chown -R userthatrunsSR:userthatrunsSR .
