### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/hotfix-nn-entries: Permission non accord?e
From https://github.com/SickRage/SickRage
 ! 43525ec..7a2cfa7  hotfix-nn-entries -> origin/hotfix-nn-entries  (unable to update local ref)

### ISSUE THREAD

**Issue by gormson** [SickRage/sickrage-issues#29]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ac5ccd7fec056ae974f9913f7685978dac2b1ec6
Link to Log: https://gist.github.com/b43ac270cda80b5f3829
### ERROR
```
CHECKVERSION :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/hotfix-nn-entries: Permission non accord?e
From https://github.com/SickRage/SickRage
 ! 43525ec..7a2cfa7  hotfix-nn-entries -> origin/hotfix-nn-entries  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gormson** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ac5ccd7fec056ae974f9913f7685978dac2b1ec6
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/hotfix-nn-entries: Permission non accord?e
From https://github.com/SickRage/SickRage
 ! 43525ec..7a2cfa7  hotfix-nn-entries -> origin/hotfix-nn-entries  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gormson** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ac5ccd7fec056ae974f9913f7685978dac2b1ec6
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/hotfix-nn-entries: Permission non accord?e
From https://github.com/SickRage/SickRage
 ! 43525ec..7a2cfa7  hotfix-nn-entries -> origin/hotfix-nn-entries  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gormson** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ac5ccd7fec056ae974f9913f7685978dac2b1ec6
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/hotfix-nn-entries: Permission non accord?e
From https://github.com/SickRage/SickRage
 ! 43525ec..7a2cfa7  hotfix-nn-entries -> origin/hotfix-nn-entries  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gormson** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ac5ccd7fec056ae974f9913f7685978dac2b1ec6
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/hotfix-nn-entries: Permission non accord?e
From https://github.com/SickRage/SickRage
 ! 43525ec..7a2cfa7  hotfix-nn-entries -> origin/hotfix-nn-entries  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gormson** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@ac5ccd7fec056ae974f9913f7685978dac2b1ec6
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/hotfix-nn-entries: Permission non accord?e
From https://github.com/SickRage/SickRage
 ! 43525ec..7a2cfa7  hotfix-nn-entries -> origin/hotfix-nn-entries  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gormson** [comment]
Bonjour. 

Je vous que tout a été clos mais y a t il une opération que je dois réaliser sur mon server pour corriger l'erreur où est ce que cela bien du dépôt?

Merci d'avance. 

JNV

**Comment by duramato** [comment]
@gormson check your permissions
