### ISSUE TITLE
Restart page not showing the "YES" image when task finished

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#36]
@OmgImAlexis 

Missing the ![image](https://raw.githubusercontent.com/SickRage/SickRage/master/gui/slick/images/yes16.png)

Should be:
Waiting for SickRage to shutdown ![image](https://raw.githubusercontent.com/SickRage/SickRage/master/gui/slick/images/yes16.png)
Loading the default page: ![image](https://raw.githubusercontent.com/SickRage/SickRage/master/gui/slick/images/loading16.gif)

What is happening:
![image](https://cloud.githubusercontent.com/assets/2620870/11311133/1d7881f8-8fb5-11e5-82d9-1592c47cfc87.png)

**Comment by OmgImAlexis** [comment]
@fernandog this seems to be working on dev and master. Maybe it's a cache issue?

**Comment by fernandog** [comment]
Phone worked. Will clear cache in desktop. Sorry

**Comment by OmgImAlexis** [comment]
@fernandog all good.
