### ISSUE TITLE
[feature request] Shows with directory not found

### ISSUE THREAD

**Issue by djack42** [SickRage/sickrage-issues#37]
Hi,
I would like a way to tell if a show has no directory without having to go on each show page.
On the mass edit or shows pages, like a check. That way, i could fix them easily.
I have hundreds of shows, and sometime i forgot to set the directory after moving them to another drive.

Also, a way to filter on some values in mass edit could not hurt. It's way too long on a tablet to select manually each checkboxes for a category of shows to mass edit (all animes or all sports, etc.), especially with hundreds of shows.

Thx

**Comment by OmgImAlexis** [comment]
Please add a request on [FeatHub](http://feathub.com/SickRage/SickRage).
