### ISSUE TITLE
Torrent Search settings

### ISSUE THREAD

**Issue by Rouzax** [SickRage/sickrage-issues#4]
I'm not entirely sure but didn't the settings of this page change depending on the selected torrent destination?
![image](https://cloud.githubusercontent.com/assets/4103090/11241024/8c90df8c-8df7-11e5-8427-914b8c1c6730.png)

Running:

SR Version:	BRANCH: (master) / COMMIT: (SIckRage/SickRage@d88f8373f70006bb47a22c294c57828aaaaf6213) 
SR User:	Download
SR Locale:	('nl_NL', 'cp1252')
SR Config:	C:\GitHub\SickRage\config.ini
SR Database:	C:\GitHub\SickRage\sickbeard.db
SR Cache Dir:	C:\GitHub\SickRage\cache
SR Log Dir:	C:\GitHub\SickRage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment]
afaik yes. maybe JS issue
@OmgImAlexis

**Comment by OmgImAlexis** [comment]
Pretty sure this is fixed in dev.

**Comment by OmgImAlexis** [comment]
Should be fixed. https://github.com/SickRage/SickRage/pull/98
