### ISSUE TITLE
Download subtitles to PP folder

### ISSUE THREAD

**Issue by DDamian** [SickRage/sickrage-issues#40]
Hi,

Because we have almost ready PR #93 so that PP is postponed until there are subtitles next to movie file,  we should modify SR built-in subtitle downloader, to download subtitles to PP folder, so that then PP can start for such movie.

@fernandog don't you agree ? ;) ;)

Thanks
Damian

**Comment by medariox** [comment]
We use Feathub for feature requests: http://feathub.com/SickRage/SickRage
