### ISSUE TITLE
Backup/Restore browser window title is wrong

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#41]
If you click "Brownse... " button in "Backup" tab is shows ok the window with title: "Select the folder you wish to save your backup file to"

but then if you click "Restore" is shows the same title instead of "Select the backup file you wish to restore"

Happens the other way around too

**Comment by fernandog** [comment]
@OmgImAlexis

**Comment by Amadeus-** [comment]
PR submitted:  https://github.com/SickRage/SickRage/pull/265

**Comment by Amadeus-** [comment]
Ugh....sorry about assignee spam -- I thought you could assign more than one person :(

**Comment by miigotu** [comment]
Fixed in develop

**Comment by fernandog** [comment]
Thanks!
