### ISSUE TITLE
Problem git at start

### ISSUE THREAD

**Issue by fana13** [SickRage/sickrage-issues#42]
Hi,

I've follow you then i've proceed to new setup.
I've downloaded the last package on master branch.
I've copied my settings et sickbeard.db to a new install.
When i start sickrage i've a warning in log : 
Unable to setup GitHub properly. GitHub will not be available. Error: 
So i can't proceed to update cause this.
I've tried to do a git reset like this 
git remote set-url origin https://github.com/SickRage/SickRage.git
git fetch origin
git checkout master
git branch -u origin/master
git reset --hard origin/master
git pull

But in every lines i've this error:
fatal: Not a git repository (or any of the parent directories): .git
So i can't solved it
Before changed, on last package, i doesn't have this problem.
Thanks for your helpful

**Comment by miigotu** [comment]
"fatal: Not a git repository (or any of the parent directories): .git"
You have to cd into the SickRage directory FIRST.

**Comment by fana13** [comment]
I've read this and i'm in

**Comment by labrys** [comment]
cool glad it works for you

**Comment by fana13** [comment]
It doesn't work.
"i'm in" = i'm in sickrage folder when i run git commands

**Comment by fernandog** [comment]
@fana13 rename old Sickrage folder to Sickrage-old. Clone Sickrage again and copy *.db config.ini cache/ to new folder

**Comment by adaur** [comment]
The message is quite clear : either you're not in the correct folder or you never cloned SR in the first place. 

You need to go into the SR folder, not at its root

**Comment by fana13** [comment]
@fernandog I've already clone a proper sickrage and copied sickbeard.db and config.ini in the new clone and i've the same pb.
@adaur je suis bien dans le dossier sickrage au moment où je lance les commandes git (cd /var/www/sickrage) et j'ai le pb que j'ai énoncé. Le message a beau être clair mais j'ai bien tenté de repartir d'une base propre avec un sickrage tout beau tout neuf et j'ai également bien suivi les étapes pour faire un git reset en partant du dossier sickrage sans plus de succès.

**Comment by adaur** [comment]
Please speak english so everybody can understand.

Can you see a cached .git folder within SR folder?
If not, I'm afraid something was wrong with your previous installation, and you should do a clean installation: cd /folder then git clone

**Comment by fana13** [comment]
Sorry @adaur you're right.
I doesn't have a .git cached folder in my sickrage folder.
Only have .build.
So in the previous fully operationnal sickrage, it doesn't in anyway.
I don't understand what's wrong in this new package...

**Comment by miigotu** [comment]
seems you originally installed from source. back up and reinstall from the new repo.

**Comment by adaur** [comment]
Yeah, this doesn't have anything to do with the 'new' package, it's just that the first installation wasn't done properly.

**Comment by fana13** [comment]
@adaur why do you closed this issue ?
I've always my problem...
I do backup of my sickrage folder, and rename it to sickrageori
i download the .zip here https://github.com/SickRage/SickRage.git
I extract it to /var/www and i copy sickbeard.db and config.ini from sickrageori.
Next i start sickrage and i've got the error message.
Can you explain me what's wrong with this manipulations please ?
Maybe i do a wrong thing, surely even.
If i look in "help and info" i see this :
 SR Version:	BRANCH: (master) / COMMIT: (d294e9faf48d45051a50d4e2cf3a0252c28d5b17)
but i've downloaded the last .zip  the commit : 6cdb5420378f7ae944e087cc1e4272fccdb7fc41
I don't understand... 
The only thing that connects the old repo and the new is my config.ini and my sickbeard.db

**Comment by miigotu** [comment]
You need to stop SR, delete the line cur_commit_hash line in your config.ini

**Comment by fana13** [comment]
I stop SR, i delete this line, i start SR and now i've no commit in help and info
SR Version:	BRANCH: (master) / COMMIT: ()

**Comment by miigotu** [comment]
Check for updates.

**Comment by fana13** [comment]
I do a proper clone (not extract .zip). I know u told me befor but i believed it was the same thing, sorry for that.
Then after do a git clone, i've copied my cache, sickbeard.db and config.ini to the new repo i have the same problem.
But i've .git folder in sickrage.
I did :
git remote set-url origin https://github.com/SickRage/SickRage.git  - OK
git fetch origin  - OK
git checkout master  - OK
git branch -u origin/master - Have this error > error: unknown switch `u'

In my config.ini, i don't have line cur_commit_hash, i tryied to check for new update and in my log i've got this : 
Thread-14 :: Version checking is disabled, not checking for the newest version
But in general settings, update is already checked.

**Comment by fernandog** [comment]
Remove the -u

**Comment by fana13** [comment]
Without -u it's ok but warning with git reset
git reset --hard origin/master
warning: refname 'origin/master' is ambiguous.
warning: refname 'origin/master' is ambiguous.
HEAD is now at 91e54c0 Try to fix https://github.com/SickRage/sickrage-issues/issues/60 -- CANT REPRODUCE
git pull : already up-to-date

I restart SR and always :
WARNING  MAIN :: Unable to setup GitHub properly. GitHub will not be available. Error: 
In Help & Info : 
SR Version:	BRANCH: (master) / COMMIT: () 
In check for update : 
Thread-17 :: Version checking is disabled, not checking for the newest version

**Comment by miigotu** [comment]
noooo. now you need to `git branch -d origin/master` then `git branch --set-upstream-to origin/master && git branch -t origin/master && git reset --hard origin/master`

**Comment by fana13** [comment]
i've this error on the second command (the first delete branck OK)
error: unknown option `set-upstream-to'

Thanks for your patience

**Comment by miigotu** [comment]
`git branch -t origin/master && git reset --hard origin/master`

**Comment by fana13** [comment]
Branch origin/master set up to track local branch master.
warning: refname 'origin/master' is ambiguous.
warning: refname 'origin/master' is ambiguous.
HEAD is now at 91e54c0 Try to fix https://github.com/SickRage/sickrage-issues/issues/60 -- CANT REPRODUCE

**Comment by miigotu** [comment]
Its updated, but you also didnt delete the branch I said...

`git branch -d origin/master`

**Comment by stvkno** [comment]
i had similar issue when i was changing over repos after the original got echel0n'd.

with the not a repository '.git' error i just went into the main sickrage directory (where config.ini) is and did `git init` then i was able to do the hard reset and creation of upstream.

**Comment by fana13** [comment]
/var/www/sickrage# git branch -d origin/master
Deleted branch origin/master (was 91e54c0).

:/var/www/sickrage# git checkout master && git branch -t origin/master && git reset --hard origin/master
Already on 'master'
Branch origin/master set up to track local branch master.
warning: refname 'origin/master' is ambiguous.
warning: refname 'origin/master' is ambiguous.
HEAD is now at 91e54c0 Try to fix https://github.com/SickRage/sickrage-issues/issues/60 -- CANT REPRODUCE

I'm gonna be crazy...

@stvkno i did git init and after what was supposed to do ?

**Comment by miigotu** [comment]
why would you git init -.- you arent creating a new git project.... Done trying to help, you guys keep doing stuff I didnt say to do that you dont understand what your doing, but not doing what I said to do.

**Comment by stvkno** [comment]
If you install sr by downlaod to zip you won't have the .git folder, so none of the git commands besides clone will work

**Comment by miigotu** [comment]
That doesnt mean you can git init, using any of those command wont get you any updates that way anyways.

Dont install by downloading the zip. Use the installer.

**Comment by fana13** [comment]
@miigotu i didn't git init, i'm waiting to but clearly i don't understand what i do. If i understood, i think my problem would be already fix.
I tryied to follow your instructions as better, and i'm always in same state like my last post.

**Comment by miigotu** [comment]
@fana13 try this:
```bash
git update-ref -d refs/origin/master
git branch -d origin/master
git branch --set-upstream-to=origin/master master
```

**Comment by fana13** [comment]
Thanks again for your help, it's very nice.
One of my problem it's the version of git command. Then i proceed to update and i can execute more command, its better.

The result of three lasts instructions is 

/var/www/sickrage# git update-ref -d refs/origin/master
/var/www/sickrage# git branch -d origin/master
Deleted branch origin/master (was 91e54c0).
:/var/www/sickrage# git branch --set-upstream-to=origin/master master
Branch master set up to track remote branch master from origin.

But at start i've always :
MAIN :: Unable to setup GitHub properly. GitHub will not be available. Error:

I will try to re-clone later and follow instructions

**Comment by miigotu** [comment]
Github is not git.
`MAIN :: Unable to setup GitHub properly. GitHub will not be available. Error:` means your password is incorrect in the settings.

**Comment by fana13** [comment]
Wow this is it.
Sorry to have misled but it's just that.
Thanks for your big patience, with guys like me you need a lot of...

**Comment by miigotu** [comment]
lol. np. just glad it is sorted out.
