### ISSUE TITLE
Manual post processing is redirecting to home page

### ISSUE THREAD

**Issue by alex1651** [SickRage/sickrage-issues#46]
When i am setting up manual post processing. I input my directory and select the process method to bee used and Force already post processed Dir/Files and Mark Dir/Files as priority download. I then click the process button and am immediately redirected to the home page. No errors are given in the logs.
Branch: Master
Commit hash: 6cdb5420378f7ae944e087cc1e4272fccdb7fc41
Your operating system and python version: Debian OS 7, python version is 2.7.3
What you did: tried Manual post processing.
What happened: I clicked process and it redirected me to the home page
What you expected: i am not sure, i have never used manual post processing
How can we reproduce your issue: I am not sure how to reproduce the issue.
Link to logs: http://pastebin.com/raw.php?i=TEWZu2iD

**Comment by OmgImAlexis** [comment]
@miigotu already checked and this isn't a js issue from what I can tell.

**Comment by alex1651** [comment]
OS is Debian 7 running on the latest master release

**Comment by fernandog** [comment]
Develop branch runs ok.
If you are redirect to shows page is because you got and error. View log. Change to debug and post results in GIST and last link.

Read report issues guidelines please

**Comment by OmgImAlexis** [comment]
@fernandog I told him to report it like this.

**Comment by Thraxis** [comment]
@alex1651 

What user is your sickrage running as, and does that user have access rights to /home/alex/Post-Processing

I'm going to presume that it does not as that is your home folder.

**Comment by fernandog** [comment]
welcome back @Thraxis !

**Comment by Thraxis** [comment]
I've been lurking... Just been short of time to really keep up with things

**Comment by alex1651** [comment]
@Thraxis I am the owner of the folder and have create and delete permissions

**Comment by Thraxis** [comment]
@alex1651 Yes, but does the user that sickrage runs as have permissions.

If you go to the Help & Info page on the config section of sickrage it will tell you what user sickrage is running as, that user needs permission to the folder.

![image](https://cloud.githubusercontent.com/assets/1131905/11326203/3572cbba-9118-11e5-82f0-3efa7d9033d3.png)

**Comment by fernandog** [comment]
@Thraxis join us at IRC #sickrage-issues

**Comment by alex1651** [comment]
The user that is listed is Alex

**Comment by OmgImAlexis** [comment]
@Thraxis I have the exact same issue with no permissions issues.

**Comment by miigotu** [comment]
ebkac, fixing in teamviewer.
