### ISSUE TITLE
[APP SUBMITTED]: Failed Unrar archive doctor.who.2005.s09e10.720p.hdtv.x264-tla.rar: Unrar: Invalid Rar Archive

### ISSUE THREAD

**Issue by rgaiser** [SickRage/sickrage-issues#48]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-68-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6cdb5420378f7ae944e087cc1e4272fccdb7fc41
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Failed Unrar archive doctor.who.2005.s09e10.720p.hdtv.x264-tla.rar: Unrar: Invalid Rar Archive
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
Corrupt far file
