### ISSUE TITLE
 [Libertalia] :: Unable to connect to provider

### ISSUE THREAD

**Issue by nicof79** [SickRage/sickrage-issues#49]
2015-11-22 10:44:07 WARNING  SEARCHQUEUE-MANUAL-274431 :: [Libertalia] :: Unable to connect to provider
2015-11-22 10:44:07 WARNING  SEARCHQUEUE-MANUAL-274431 :: [Libertalia] :: Connection timed out (sockets) accessing getURL https://libertalia.me/login.php Error: '__str__ returned non-string (type Error)'

**Comment by adaur** [comment]
Did this happen multiple times? If not, then it's just because LTL was down

**Comment by nicof79** [comment]
ça arrive a chaque recherche. ma daily search est a 10minutes et j ai ce message toute les 10 minutes. du coup je l ai desactivé pour le moment.

**Comment by fernandog** [comment]
@nicof79 add github user/pass in SR and when error hapoens please click the button "submit errors"

I think its a ssl errors. Need the full log from issue submitter

**Comment by nicof79** [comment]
ok I do that.

**Comment by adaur** [comment]
If it's a ssl error you need to disable ssl cert verification

**Comment by nicof79** [comment]
@fernandog i have add user/pass in SR for github but i don t find tje "submit errors" button.
i stopped SR and chage this value in config.ini : 
git_autoissues = 1
Si vous parlez français ça sera plus simple pour moi ^^.

**Comment by duramato** [comment]
`Connection timed out ` its just a simple timeout..

**Comment by nicof79** [comment]
I havnt timout in my browser.

**Comment by duramato** [comment]
It can happen from time to time

**Comment by nicof79** [comment]
i try a wget from my synology command line and the result is :+1: 
wget -p  https://libertalia.me/login.php
--2015-11-22 14:36:12--  https://libertalia.me/login.php
Resolving libertalia.me... 37.156.247.12
Connecting to libertalia.me|37.156.247.12|:443... connected.
ERROR: cannot verify libertalia.me's certificate, issued by '/O=Libertalia/CN=libertalia.me':
  Self-signed certificate encountered.
To connect to libertalia.me insecurely, use `--no-check-certificate'.

**Comment by duramato** [comment]
do you have this option enabled? "Verify SSL Certs"
![image](https://cloud.githubusercontent.com/assets/10121067/11324092/95988c40-911e-11e5-95e0-bebb5158a5c5.png)

**Comment by adaur** [comment]
Come on! I just told you to disable verification 5 posts above!

**Comment by nicof79** [comment]
I finally find it and it's now ok for me
@adaur i m sorry .
Thanks all for you help.

**Comment by duramato** [comment]
Is it now working ?

**Comment by nicof79** [comment]
Yes it s good now. You can close the ticket
