### ISSUE TITLE
[Anime] White- or Blacklisting fansub-groups with special chars in name does not work

### ISSUE THREAD

**Issue by psych0d0g** [SickRage/sickrage-issues#5]
SSIA

**Comment by adaur** [comment]
Hi,

Can you be more specific and provide a full log?

**Comment by psych0d0g** [comment]
i will look into this myself, it just kind of serves as a reminder for me atm.
ill update with findings etc as soon as i have them

**Comment by OmgImAlexis** [comment]
@psych0d0g if we could get some more information I could probably fix this within a day or two.

**Comment by labrys** [comment]
@psych0d0g Any updates on this?

**Comment by OmgImAlexis** [comment]
We can reopen this if it's still an issue and if we get some more information about it.
