### ISSUE TITLE
Pause show not showing with Microsoft IIS Reverse Proxy (ARR) cache issue

### ISSUE THREAD

**Issue by Rouzax** [SickRage/sickrage-issues#50]
When I press pause in a show nothing seems to happen or change.
The debug log only tells:
```
2015-11-22 11:23:14 DEBUG    Thread-44 :: 284190: Saving to database: Marvel's Jessica Jones
```
running:
SR Version:	BRANCH: (master) / COMMIT: (SickRage/SickRage@6cdb5420378f7ae944e087cc1e4272fccdb7fc41) 
SR User:	Download
SR Locale:	('nl_NL', 'cp1252')
SR Config:	C:\GitHub\SickRage\config.ini
SR Database:	C:\GitHub\SickRage\sickbeard.db
SR Cache Dir:	C:\GitHub\SickRage\cache
SR Log Dir:	C:\GitHub\SickRage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment]
@Rouzax can you see if there is any JS error?

**Comment by Rouzax** [comment]
How would I check that?

Somehow I managed to get one show paused but can't get it back to normal.
This seems to be related to my Microsoft IIS Reverse proxy setup, when I connect directly to my SickRage machine it works as expected.
We've had an issue with multiple notifications that was also connected to IIS ARR might this be the same?

**Comment by fernandog** [comment]
I think so.
Change the issue title and add the reverse proxy stuff

**Comment by Rouzax** [comment]
The weird thing is that I sometimes seem to be able to change the pause setting through the show edit page while other shows do not seem to stick the first time.

I was able to change The Affair through the show Edit page but not 2 Broke Girls, only after a few tries.
Debug log shows the same.
```
2015-11-25 10:38:39 DEBUG    Thread-24 :: 248741: Saving to database: 2 Broke Girls
2015-11-25 10:38:27 DEBUG    Thread-54 :: 248741: Saving to database: 2 Broke Girls
2015-11-25 10:38:14 DEBUG    Thread-34 :: 248741: Saving to database: 2 Broke Girls
2015-11-25 10:38:08 DEBUG    Thread-21 :: Looking up XEM scene mapping for show 248741 on theTVDB
2015-11-25 10:38:00 DEBUG    Thread-46 :: 270439: Saving to database: The Affair
```

The IIS logs are as follows.
```
#Software: Microsoft Internet Information Services 8.5
#Version: 1.0
#Date: 2015-11-25 09:46:24
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(Referer) sc-status sc-substatus sc-win32-status time-taken
2015-11-25 09:47:52 192.168.2.2 GET /ui/get_messages - 443 - 195.234.136.77  https://tvseries.XYZ.ZYX/home/displayShow?show=248741 200 0 0 78
2015-11-25 09:47:54 192.168.2.2 GET /home/togglePause show=248741 443 - 195.234.136.77  https://tvseries.XYZ.ZYX/home/displayShow?show=248741 302 0 0 78
2015-11-25 09:47:54 192.168.2.2 GET /home/displayShow show=248741 443 - 195.234.136.77  https://tvseries.XYZ.ZYX/home/displayShow?show=248741 200 0 0 687
2015-11-25 09:47:54 192.168.2.2 GET /home/getManualSearchStatus show=248741 443 - 195.234.136.77  https://tvseries.XYZ.ZYX/home/displayShow?show=248741 304 0 0 78
2015-11-25 09:47:54 192.168.2.2 GET /showPoster/ show=248741&which=poster_thumb 443 - 195.234.136.77  https://tvseries.XYZ.ZYX/home/displayShow?show=248741 304 0 0 62
2015-11-25 09:47:55 192.168.2.2 GET /ui/get_messages - 443 - 195.234.136.77  https://tvseries.XYZ.ZYX/home/displayShow?show=248741 200 0 0 78
2015-11-25 09:47:55 192.168.2.2 GET /home/getManualSearchStatus show=248741 443 - 195.234.136.77  https://tvseries.XYZ.ZYX/home/displayShow?show=248741 304 0 0 78
2015-11-25 09:47:58 192.168.2.2 GET /ui/get_messages - 443 - 195.234.136.77  https://tvseries.XYZ.ZYX/home/displayShow?show=248741 200 0 0 78
2015-11-25 09:48:00 192.168.2.2 GET /home/getManualSearchStatus show=248741 443 - 195.234.136.77  https://tvseries.XYZ.ZYX/home/displayShow?show=248741 304 0 0 62
2015-11-25 09:48:00 192.168.2.2 GET /ui/get_messages - 443 - 195.234.136.77  https://tvseries.XYZ.ZYX/home/displayShow?show=248741 200 0 0 78
```

The press of the pause button gives a HTTP 302 after which several pages give a 304 Not Modified.
Let me know if you need anything, @miigotu.

**Comment by Rouzax** [comment]
I'm pretty sure it is a cache issue.

This is my SickRage through IIS ARR, I've tried to do a Ctrl+f5 and it shows the same.
![image](https://cloud.githubusercontent.com/assets/4103090/11417618/cc1d32b4-9418-11e5-95b2-6fa202767c99.png)

This is the same show when I open the internal site.
![image](https://cloud.githubusercontent.com/assets/4103090/11417646/faaff3d2-9418-11e5-85ce-f145126dcb02.png)

**Comment by OmgImAlexis** [comment]
@Rouzax it may actually be a proxy issue. I had similar issues using Nginx, do you have send headers or something like that enabled on the config page?

**Comment by Rouzax** [comment]
@OmgImAlexis, nope those are not enabled, should they be?
![image](https://cloud.githubusercontent.com/assets/4103090/11418025/423c747a-941c-11e5-804d-5122691bd0ac.png)

**Comment by OmgImAlexis** [comment]
If you're using a proxy, probably. I had massive caching issues without it.

**Comment by Rouzax** [comment]
@OmgImAlexis, That doesn't change the issue. :cry:

**Comment by OmgImAlexis** [comment]
Well it's definitely a proxy issue, since I doubt anyone on the dev team uses anything but Nginx for their proxy to SickRage this may have to wait a while before we look into it. Sorry.

**Comment by Rouzax** [comment]
I know it is a proxy issue but it is a caching issue on the proxy.
SickRage sends 304 response on some pages which tells IIS that the page hasn't changed.

**Comment by miigotu** [comment]
you have to enable the revers proxy headers, stop sickrage, clear cache/sessions, start sickrage, and then test.

**Comment by Rouzax** [comment]
@miigotu, still the same behaviour.

**Comment by miigotu** [comment]
Yeah, no idea how to fix that atm, or how/if it was recently broken.

**Comment by Rouzax** [comment]
No problem, it is not the end of the world :laughing:

**Comment by miigotu** [comment]
Maybe this info will help (ignore the topic, just see the cache stuff)
http://blogs.msdn.com/b/chiranth/archive/2014/08/03/application-request-routing-part-2-reverse-proxy-and-troubleshooting-arr-urlrewrite-issues.aspx

**Comment by Rouzax** [comment]
I don't have any cache disk configured so there is no caching of objects to disk, I think it will keep it in memory but that can't be turned off.

After opening the show The Affair I have 1 cache item
![image](https://cloud.githubusercontent.com/assets/4103090/11420511/d3f34ac6-942e-11e5-8f7a-a0e320dc4c68.png)
That is probably the same page that is served after I try to pause is.

**Comment by Rouzax** [comment]
I figured out a workaround, but that disabled the memory cache all together which is a bit of a shame.

In IIS Manager open up Application Request Routing Cache
![image](https://cloud.githubusercontent.com/assets/4103090/11420813/e777bdc8-9430-11e5-96ef-4e61f50c9e4d.png)

Create a Cache Control Rule, do Add
![image](https://cloud.githubusercontent.com/assets/4103090/11420845/199647ca-9431-11e5-9b9e-2b7c4a176191.png)

Create a new Rule
![image](https://cloud.githubusercontent.com/assets/4103090/11420857/38ef23ee-9431-11e5-8398-8137b456660d.png)

This will create a URL rewrite rule that sets the ARR_CACHE_CONTROL_OVERRIDE server variable to 1,no-cache

This will tell client browsers not to cache any data.

**Comment by miigotu** [comment]
Caching (even in memory) is not really necessary unless you have thousands of requests to the page

**Comment by OmgImAlexis** [comment]
@miigotu it's usually enabled as a IIS proxy is usually used in a domain environment with a few hundred if not a few thousand users.

**Comment by miigotu** [comment]
@OmgImAlexis I understand that, but for @Rouzax I am almost certain that is not the case.

**Comment by OmgImAlexis** [comment]
@miigotu just saying that may be why it was on and was causing issues.

**Comment by miigotu** [comment]
likely =P

**Comment by Rouzax** [comment]
I do not have thousands of users so far you are correct. :wink: 
That being said I would like to be able to have it enabled, so the page in question should send a no-cache response.

**Comment by OmgImAlexis** [comment]
@Rouzax the problem with that is it doesn't affect other users and we like to act in favour of the majority.. :disappointed:

**Comment by miigotu** [comment]
@Rouzax even more the problem is that is our slowest page in all of SR, we cant responsibly send a no-cache there =P

**Comment by Rouzax** [comment]
I know that I'm an odd duckling using a WIndows Server for SickRage in combination with a IIS ARR as reverse proxy :hatching_chick:

**Comment by Rouzax** [comment]
Does this mean it won't ever be fixed?

**Comment by OmgImAlexis** [comment]
@Rouzax it's not really anything we can fix. It's not an issue on any other proxy software like apache or nginx and doesn't affect non-proxy users. So unless you want to submit a PR that doesn't change anything for them I doubt it'll get "fixed". Sorry.

**Comment by Rouzax** [comment]
No problem, just asking.
