### ISSUE TITLE
Anime no longer parsing S01E01 format

### ISSUE THREAD

**Issue by Reedicht** [SickRage/sickrage-issues#58]
## Info
Branch: Master
Commit: ac5ccd7fec056ae974f9913f7685978dac2b1ec6
OS: FreeBSD (FreeNAS 9.3 Jail)
Python: 2.7.10
Problem: I'm seeing ~100 warnings a day regarding no episode number being found in the existing files. Possibly related to 68341f325689b286f8451dd254a2f10c824c85aa.

> 2015-11-22 10:07:18 SHOWQUEUE-REFRESH :: No episode number found in /media/anime/One-Punch Man/Season 01/One-Punch.Man-S01E01-The.Strongest.Man-1080p.HDTV.mkv, ignoring it

**Comment by duramato** [comment]
Enable anime for that show

**Comment by Reedicht** [comment]
This show is set as an Anime. This only seems to affect those shows set as an Anime.

**Comment by duramato** [comment]
Sorry i meant to unset anime , becouse `S01E01` is the numbering for normal shows

**Comment by Reedicht** [comment]
Is there a reason anime should not follow this format? The regex patterns appear to allow for S01E01 as long as the absolute episode number is there (either before or after the absolute number). Generally, anime follows the absolute episode number but many databases list shows by season (thetvdb.com, for example). 

I believe I can change the custom renaming to account for this but it seems like having the option "No Absolute Number" under episode renaming may be a bit counter intuitive at it implies that the absolute episode number is not required although I could be wrong.

**Comment by duramato** [comment]
Anime uses absolute numbering ie E234

**Comment by Reedicht** [comment]
Gotcha. I think if anime requires the absolute numbering for SR's showqueue refresh, it might be a good idea to remove the "No Absolute Number" option under the Episode Naming setting for Anime shows or possibly show a warning when chosen that SR might not be able to recognize the file when SR performs a show refresh.

I don't know if SR utilizes the custom format entered in "Episode Naming" for determining the season/episode number but that might also help eliminate this possibility. I wasn't using custom naming for Anime so maybe it does this already except when custom naming for Anime is disabled.

**Comment by Thraxis** [comment]
There should be no problems importing Anime with the SxxExx pattern, sickrage converts between the SxxExx and Episode value internally when doing checks for the episode number.

**Comment by Reedicht** [comment]
So, importing isn't really an issue but the warnings that come during a show queue refresh later seem to be. For instance, most Specials won't have an absolute episode number (which makes sense) but a warning is still given:

    2015-11-24 10:06:51 SHOWQUEUE-REFRESH :: No episode number found in /media/anime/K/Season 00/K-S00E01-Missing.Kings-1080p.BluRay.mp4, ignoring it

There won't ever be an absolute episode number for the episode although the SXXEXX should be correct. A "Preview Rename" doesn't seem to indicate that SR thinks there should be an absolute number there either (e.g. adding -000 to the episode).

I don't believe this is an issue for all series but for some, it does seem to be a problem for some reason.

**Comment by udochrist** [comment]
Same issue here. Could it be that the additional numbers in the ep name confuse the parser?
Show is set to anime; and all other eps are processed. These are the only ones with numbers in their name. SxxExx name has been created when processing the show by SR.

    2015-11-26 01:53:17 SHOWQUEUE-REFRESH :: No episode number found in /volume1/Media/TV Anime/Monster/Season 01/S01E55 - Room 402.mkv, ignoring it
    2015-11-26 01:53:16 SHOWQUEUE-REFRESH :: No episode number found in /volume1/Media/TV Anime/Monster/Season 01/S01E41 - Ghosts of 511.mkv, ignoring it
    2015-11-26 01:53:15 SHOWQUEUE-REFRESH :: No episode number found in /volume1/Media/TV Anime/Monster/Season 01/S01E11 - Kinderheim 511.mkv, ignoring it

**Comment by Amadeus-** [comment]
I don't have an interest in anime; however, could someone verify yes or no if the problem/bug in this issue matches the same in this one:  https://github.com/SickRage/sickrage-issues/issues/106  ?

**Comment by Reedicht** [comment]
I don't see the same errors when refreshing a show but I do believe that fix should work as it looks like the additional regex doesn't require the absolute number any longer.

**Comment by miigotu** [comment]
Fixed in develop.
