### ISSUE TITLE
Auto update is not working

### ISSUE THREAD

**Issue by mexisd** [SickRage/sickrage-issues#6]
Hi,

I don't know if I should say congrats for the move since it came out of some sort of internal battle... but I am sure everything will be worked out in the end and this is for the best.

I decided to follow you, especially @miigotu since he was one of the most active community members since I started using SickRage.

Hence, I just moved from the SickRageTV to SickRage. I am running SickRage on a QNAP with Python 2.7.10.

Probably in the way my old SickRage had been installed through a QPKG on my QNAP, but it was not exactly a .git repo. Anyway, I renamed the old folder to SickRage_old and then did a git clone. Now my path looks something like this:
/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage

I copied my config and DB files and SickRage started without any problems, except a warning in the log file:

2015-11-18 13:28:03 CHECKVERSION :: git fetch origin returned : fatal: unable to access 'https://github.com/SickRage/SickRage.git/': error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
2015-11-18 13:28:03 CHECKVERSION :: Unable to contact github, can't check for update

I never had an issue with updating automatically before.

Since I used my old config file I noticed the following entries:
git_remote_url = https://github.com/SiCKRAGETV/SickRage.git
cur_commit_hash = d294e9faf48d45051a50d4e2cf3a0252c28d5b17

which I changed to:
git_remote_url = https://github.com/SickRage/SickRage.git
cur_commit_hash = 3823a6846b558a03eba0f3f29aadb89f9d68a1d2

Restarted SickRage and tried again, but that did not fix the issue.

Then it hit me that it seems like a certificate issue.

If I SSH into my QNAP box and try 
curl https://github.com/SickRage/SickRage.git/ 

I am getting 
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

Also, in the /etc/ssl/certs path there is not ca-certificates.crt file. Only myrootca.crt and myhost.crt.

 I tried to get the Root CA that has signed GitHub's certificate and then I used the following command

curl --cacert DigiCertHighAssuranceEVRootCA.crt https://github.com/SickRage/SickRage.git/

which returned the following error:
curl: (77) error setting certificate verify locations:
  CAfile: DigiCertHighAssuranceEVRootCA.crt
  CApath: none

A bit closer to what I see in the SickRage logs.

I run out off ideas, so I thought to raise this issue and ask for your help. Any ideas?

**Comment by adaur** [comment]
Please SSH into your NAS, and try the following commands:

service sickrage stop
cd /path2sickrage
git remote set-url origin https://github.com/SickRage/SickRage.git
git fetch origin
git reset --hard origin/master
service sickrage start

I don't know if the service commands will work on a QNAS,since these commands are written for Debain

**Comment by Arcanemagus** [comment]
The problem is that QNAP is notoriously _terrible_ at security and requires disabling SSL in almost every case to get things working.

If the steps @adaur outline above don't work you might try running the following command from that directory to disable SSL certificate checking:
```ShellSession
git config http.sslVerify "false"
```

**Comment by mexisd** [comment]
I know that QNAP has an inherited issue with certificates. What @adaur described did not work. I had done a git clone anyway, so I was starting from a fresh repository. 

The strange thing is that from the command line, when I did the git clone or git pull, it did not complain, but since even curl does not work it seems to be a more general problem I guess. Why it started happening now, it will remain a mystery though.

@Arcanemagus your step worked. I did not get a warning from SickRage when I clicked "Check for updates". So, as far as I am concerned this issue is closed.

Thanks for your help.

**Comment by Arcanemagus** [comment]
Just in case it wasn't obvious, that _does_ disable checking of the cert so _technically_ somebody could MITM your update process, but that's unlikely :wink:. Just thought I would make sure that was mentioned as I forgot to in the initial message.

**Comment by phaseburn** [comment]
Rather than enable https and disabling verification of its certificates (since your implementation is broken), why not just set your upstream URL to http://github.com/SickRage/SickRage.git and not use https at all? As long as you're working, great, but not using https would be the better solution IMO.

**Comment by pd5rm** [comment]
Neither http/https worked for me on QNAP box, and I got the "fatal: Unable to find remote helper for..." error, but switching to the "git" protocol worked.

git remote set-url origin git://github.com/SickRage/SickRage.git

**Comment by miigotu** [comment]
Either way works, same results =P
