### ISSUE TITLE
[APP SUBMITTED]: saveNotifications() got an unexpected keyword argument 'layout'

### ISSUE THREAD

**Issue by raistlin2912** [SickRage/sickrage-issues#61]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6752769ac0828a51191f18f48bd6a47c47fb6998
Link to Log: https://gist.github.com/b8cd4e206331d643c8c4
### ERROR
```
Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 263, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by raistlin2912** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6752769ac0828a51191f18f48bd6a47c47fb6998
Link to Log: https://gist.github.com/a2eb6a43e145023b0433
### ERROR
```
Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 263, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by raistlin2912** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6752769ac0828a51191f18f48bd6a47c47fb6998
Link to Log: https://gist.github.com/f12d14528a6106b08432
### ERROR
```
Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 263, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment]
Invalid report, nothing sends layout as a keyword to saveNotifications. Only if you modified the url to throw the error.
