### ISSUE TITLE
Bitcannon issues

### ISSUE THREAD

**Issue by OmgImAlexis** [SickRage/sickrage-issues#62]
Bitcannon is hardcoded to only use localhost.

Here's the new search url.
`/api/search/?q=QUERY&category=tv&sort=seed&order=asc&apiKey=API_KEY`

Sort can be changed to seeders, leechers or title with order being asc or desc.

When searching `-` and `""` also work so if you want to remove a certain string from all results use the `-` delimiters before a string and if you want more specific results I'd suggest you use quotes around the search string. **For now** `"Show Name S00E00" "720p"` **will give the best results**. I'm still working on this so be warned this may change.

These can also be in any order and the `API_KEY` may or may not be needed depending on if the user has it set as required or not.

The category can be changed by the user so it'd be good to have tv default to `tv` and anime default to `anime` but have the field change-able.
If you need to do a lookup of categories they can be checked by going to `/api/browse?apiKey=API_KEY`.

Here's an example of what `/api/browse?apiKey=API_KEY` will return.
````
{"categories":[{"_id":"56456516036463f20aa07551","title":"Anime","slug":"anime","aliases":["japanese anime"],"torrentCount":83867},{"_id":"56456474036463f20aa0754f","title":"Applications","slug":"applications","aliases":["apps","programs"],"torrentCount":78912},{"_id":"564565c2036463f20aa07553","title":"Audio Books","slug":"audio-books","aliases":[],"torrentCount":0},{"_id":"564560c3036463f20aa07549","title":"Books","slug":"books","aliases":["ebooks"],"torrentCount":245853},{"_id":"56513de903645f141c820009","title":"Comics","slug":"comics","aliases":[],"torrentCount":0},{"_id":"5645662c036463f20aa07555","title":"Games","slug":"games","aliases":[],"torrentCount":42588},{"_id":"5645602e036463f20aa07545","title":"Miscellaneous","slug":"misc","aliases":["other"],"torrentCount":34729},{"_id":"564563ae036463f20aa0754b","title":"Movies","slug":"movies","aliases":[],"torrentCount":301260},{"_id":"56455fc2036463f20aa07543","title":"Music","slug":"music","aliases":["audio"],"torrentCount":221096},{"_id":"56513e3e03645f141c82000b","title":"Music Videos","slug":"music-videos","aliases":[],"torrentCount":0},{"_id":"5645643a036463f20aa0754d","title":"Pictures","slug":"pictures","aliases":["photos","images"],"torrentCount":0},{"_id":"56455aff036463f20aa07541","title":"TV","slug":"tv","aliases":["tv show","show","episode"],"torrentCount":438553},{"_id":"56519f9003645f141c82000d","title":"XXX","slug":"xxx","aliases":["adult","porn","sex"],"torrentCount":1176708}]}
````

**Comment by Amadeus-** [comment]
I'm working on this.   About 50% completed.

**Comment by Amadeus-** [comment]
I'll have this finished in a day or two.   I have a lot of it working, but just having to learn the application design (how all of the modules interact) as I go. ...but, it's good for learning.     My work-in-progress (ugly I'm sure) is on my branch "fix-bitcannon"

**Comment by OmgImAlexis** [comment]
This is going well. https://github.com/SickRage/SickRage/compare/develop...Amadeus-:fix-bitcannon

**Comment by Amadeus-** [comment]
PR submitted:  https://github.com/SickRage/SickRage/pull/185
