### ISSUE TITLE
Top level folder naming convention - add (YEAR) to initial release date of series

### ISSUE THREAD

**Issue by MrCee** [SickRage/sickrage-issues#63]
Hi team,
It would be great if there was an option to incorporate the IMDB initial year release into new series added folder(s) created by SickRage. For example 'The Flash (2014)'  

This helps in the long run, especially if you need to re-create your db again. Adding the (YEAR) to my NAS (Synology) will keep different versions of the series aligned with international databases. If anyone needs to recreate to db again through the GUI, having the year there works a treat. i.e. 'The Flash (1967)' is not chosen by default. 'The Flash (2014)' is chosen by SickRage by default.

**Comment by miigotu** [comment]
This is a feature requests and belongs on (http://feathub.com/SickRage/SickRage)[feathub]
