### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: '283468.'

### ISSUE THREAD

**Issue by kaymer327** [SickRage/sickrage-issues#65]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-18-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@91e54c0364df98358a01436ee247a348775e88e1
Link to Log: https://gist.github.com/9d90cc5e6c5daaede482
### ERROR
```
Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 263, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1156, in displayShow
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: '283468.'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by medariox** [comment]
Fixed in develop branch. Thanks to @labrys
