### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by adaur** [SickRage/sickrage-issues#66]
I've been working on this a bit, let me know what you think... and feel free to fork/pull request :)

http://adaur.github.io/
https://github.com/adaur/adaur.github.io

Some things aren't supposed to stay, be reassured

**Comment by OmgImAlexis** [comment]
Looks alright, I'd remove the "We're malicious" stuff and fix the mixed content warning.

**Comment by neoatomic** [comment]
I like it. :)

**Comment by medariox** [comment]
I really like it! Will be handy when we have a new name for SR.

**Comment by MGaetan89** [comment]
Looks good. I didn't read the text, but here are a couple of feedbacks about the rest:
- Don't take screenshots with the warning/error badge
- The "History" screenshot has the mobile layout. Why? If it was on purpose, I think there should be a mobile section, not just a random screenshot in the middle of the others.
- The "Features" menu does not scroll to the correct position if we are before the position (home). It it working fine if we are after it (demo/about/download)
- In "Technologies used", I wasn't sure at first what the progress bar meant. I guess if the part of the language in the project?

**Comment by labrys** [comment]
Also at a glance there are some spelling / grammar errors.

**Comment by adaur** [comment]
I'lll have to take new screenshots @MGaetan89 

@labrys I'm not a native speaker, please correct them :)

**Comment by labrys** [comment]
Sure thing, its honestly not bad. I just like to nit-pick that kind of thhing. :)

**Comment by Zipties** [comment]
I am really torn on if I should switch repos or not. The stability of the project seemed to go pretty downhill the last few months, but I doubt echel0n is going ot keep the old one going all by himself.

**Comment by miigotu** [comment]
Guys, PR any changes necessary to the site to sickrage.github.io repo...

**Comment by adaur** [comment]
:+1:
