### ISSUE TITLE
No such file or directory issues need to be generic

### ISSUE THREAD

**Issue by OmgImAlexis** [SickRage/sickrage-issues#662]
@SickRage/collaborators can someone please make issues like https://github.com/SickRage/sickrage-issues/issues/648 more generic when they're submitted so they can all stay in a single closed issue or change it to a warning?

**Comment by neoatomic** [comment]
@OmgImAlexis  Just do a ping from inside https://github.com/SickRage/sickrage-issues/issues/648 
Hopefully @fernandog can change it to a warning instead of an error.
