### ISSUE TITLE
Sickrage keeps snatching same episode over and over

### ISSUE THREAD

**Issue by veribaka** [SickRage/sickrage-issues#69]
Branch: master
Commit hash: 
OS and Python version: Debian Jessie, Python 2.7.9
What I did: Added Rick and Morty, requested that Sickrage download the second season.
What happened: It did everything correctly, but keeps downloading the same episode even though I set the option to archive episode after first option is snatched (no problem with other episodes)
How can we reproduce: not sure if you can...
Log: https://gist.github.com/veribaka/c1994180a2524141ba17 or https://gist.github.com/c1994180a2524141ba17.git 

I already marked it as skipped, as archived, as ignored, but every other day Sickrage keeps snatching it and adding a new torrent.

Any advice?

PS. The show has the option to archive episode after first snatch enabled.

**Comment by miigotu** [comment]
archive on first match is only for your preferred list, not your allowed list. You have a 720p HDTV currently, pressing for 720p WEB-DL (which it would then archive)

**Comment by veribaka** [comment]
Ah, I understand. Thanks. I added more preferred qualities (including ones I already have) to see if it stops adding it. I'll report back if it doesn't.

On a related note, any ideas about that Gotham episode it repeatedly fails to post-process? Should I open a new ticket for that?

Thanks for the quick reply by the way :+1:

**Comment by miigotu** [comment]
`2015-11-24 11:57:16 DEBUG    POSTPROCESSER :: File /media/Disco/Downloads/Series/Gotham/Gotham.S02E08.720p.WEB-DL.DD5.1.H.264-NTb[rarbg]/Gotham.S02E08.720p.WEB-DL.DD5.1.H.264-NTb.mkv is smaller than /media/Disco/Downloads/Torrents/Complete/Gotham.S02E08.1080p.HDTV.X264-DIMENSION/Gotham.S02E08.1080p.HDTV.X264-DIMENSION.mkv
2015-11-24 11:57:16 INFO     POSTPROCESSER :: File exists and new file quality is lower than existing, marking it unsafe to replace`

**Comment by veribaka** [comment]
Thanks, I think I fixed it! :)

**Comment by fernandog** [comment]
1080p.HDTV is much better IMO

**Comment by veribaka** [comment]
Can't disagree, but it doesn't make much of a difference when watching on a 720i TV :)

**Comment by fernandog** [comment]
@miigotu in this case he had 1080p.HDTV quality then remove it from quality list - so maybe if SR detect that the file has quality not in wanted list, should PP remove it and process the existing one ?

**Comment by miigotu** [comment]
SR will always see the real quality of the file.

Some improvements are coming to PP soon, but in this case it worked exactly as designed.

**Comment by veribaka** [comment]
It can be that people like me prefer a smaller release for the space it takes on their hard drive, but will accept bigger files sometimes because there's no other alternative. But I imagine that this would be a minority.

I have a new issue though, I have a show that just downloaded, the post processing works wonderfully. However, after the first post processing, it keeps trying to post process over the same show, and failing.

Log. https://gist.github.com/veribaka/4de3f2f1e5341b3bf5d4

The message says episode is of same size, marking as unsafe. It keeps doing this over and over, this morning I had almost 3000 warnings :)

**Comment by fernandog** [comment]
@miigotu I know. just discussing possible solutions to fix it.

**Comment by veribaka** [comment]
Whelp. The show isn't going to have new episodes, so I just removed it from Sickrage. At some point it might be good to figure out why it happened though!
