### ISSUE TITLE
AttributeError: 'ManageSearches' object has no attribute 'undefined/ui/get_messages'

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#70]
maybe something related to JS changes @OmgImAlexis ?
I don't get this error in "Errors", so I couldn't submit

```
2015-11-24 10:40:06 DEBUG    TORNADO :: Failed doing webui request "undefined/ui/get_messages": Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 247, in get
    method = getattr(self, route)
AttributeError: 'ManageSearches' object has no attribute 'undefined/ui/get_messages'
```

**Comment by OmgImAlexis** [comment]
I don't think that's a JS issue but I can look into it tomorrow. @miigotu is this possibly from some webroot issue?

**Comment by miigotu** [comment]
idk, looks like some var is undefined either in js or mako in ManageSearches... Maybe when you added force subtitle search @fernandog ?

**Comment by fernandog** [comment]
not sure. the button works. and I added the forceSubtitleStatus in webserve.

**Comment by fernandog** [comment]
will monitor logs
