### ISSUE TITLE
Question: low quality snatched episodes should appear as "snatched" or "low quality"

### ISSUE THREAD

**Issue by fernandog** [SickRage/sickrage-issues#72]
...in displayShow?

@SickRage/moderators 
@SickRage/collaborators 

Cause today the low quality snatched are not appearing in the "backlogOverview" and in displayShow they are appearing as "Snatched"

We are still searching for them in backlogSearch thread. So it's just an UI issue.

**Comment by duramato** [comment]
I think they should

**Comment by labrys** [comment]
I'm not particularly found of the term low quality, but I think something better than just snatched would be in order.   First thought was something like sub-optimal or non- preferred but not too sure about those either.  Maybe Snatched (Lower), and if it gets replaced with a higher quality Snatched (Higher), and then when you get your preferred quality Snatched (Best)

**Comment by psych0d0g** [comment]
maybe we could show something like this:

Snatched: 720p HDTV (< 1080p BD)

**Comment by labrys** [comment]
I like that @psych0d0g

**Comment by miigotu** [comment]
https://github.com/SickRage/SickRage/pull/224

WIP
