### ISSUE TITLE
Incorrect ItemSeparator for compound fields being used by SickRage in Kodi NFOs

### ISSUE THREAD

**Issue by labrys** [SickRage/sickrage-issues#73]
See SiCKRAGETV/sickrage-issues#3726.  This is confirmed, although it only appears to affect the credits field in the files I tested.  The genre and director fields appear to be done correctly with / instead of |.   In the process of confirming that | produces the described results in KODI, just waiting on library to update (twiddles thumbs)

**Comment by labrys** [comment]
And thanks @MilhouseVH for the detailed issue with references.

**Comment by MilhouseVH** [comment]
Can you double check `director` as I've got new NFOs that were created yesterday where the `director` tags include pipe characters, eg.: http://sprunge.us/aUMB

**Comment by labrys** [comment]
sure, i ran a limited test since I normally create my nfo's with an external program... but I'll grep directors again

**Comment by labrys** [comment]
lol well that answers that one, apparently none of the files i PP'd had directors in their NFOs.. so I guess ill need to try some more

**Comment by labrys** [comment]
it looks like none had country either

**Comment by labrys** [comment]
genre is correct tho

**Comment by MilhouseVH** [comment]
Yep, `genre` looks fine. And I don't seem to have `country` either, maybe SR doesn't output `country`? So just looks like `director` and `credits` needs some attention - many thanks.

**Comment by labrys** [comment]
Yeah I'm going to look at redoing that once I have an updated libary... May take a while before I PR it though since a bug in PP can cause havoc

**Comment by MilhouseVH** [comment]
Sure, no rush, best to get this right first time. :)

**Comment by labrys** [comment]
Confirmed it is incorrect in KODI for credits and director.

**Comment by labrys** [comment]
Holy label-spam batman!!!   Added the enhancement tag as a reminder to add in missing fields such as country.  We will likely split the fields into multiple tags like actors, if that is properly supported by KODI.

**Comment by OmgImAlexis** [comment]
@labrys would you be able to check if this is supported in Plex? I'm don't personally use NFO files with my Plex but I'm wondering if that's possibly the reason for that field to be the only one using `|` instead of `/`.

**Comment by labrys** [comment]
@OmgImAlexis I'll verify but pretty sure the result is the same in Plex.  (I usually use Plex).  Regardless, the majority of my NFOs use multiple tags for those fields (confirmed with grep) which definitely works on Plex and I'm fairly certain (but still need to verify) that they work the same on KODI since the media manager I use for metadata (Ember Media Manager) is written specifically for KODI.

**Comment by labrys** [comment]
@OmgImAlexis also, since Plex by default doesn't support local NFOs without the [XBMCnfoTVImporter](https://github.com/gboudreau/XBMCnfoTVImporter.bundle) bundle.  If it does not work the same as KODI, it would be an issue request for the plugin.

**Comment by OmgImAlexis** [comment]
Alright, just wanted to make sure. :+1:

**Comment by labrys** [comment]
Need to also implement nfo update with url in nfo as per SiCKRAGETV/sickrage-issues#3356
