### ISSUE TITLE
Unable to setup GitHub properly

### ISSUE THREAD

**Issue by kendog819** [SickRage/sickrage-issues#75]
![image](https://cloud.githubusercontent.com/assets/11353628/11385817/7f552dbc-92ea-11e5-9091-55775b0211f6.png)

![image](https://cloud.githubusercontent.com/assets/11353628/11385838/abd713c8-92ea-11e5-880b-163f95726cdd.png)

I followed @Fetchered 's directions to a T, not sure where to go from here.: 

` Copy the recommended files as mentioned by @Rouzax (cache.db/config.ini/failed.db/sickbeard.db) from the SickRage/DATAS folder, but also copy the /share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/CONFIG/sickbeard.conf file.

Run command './QSickRage.sh stop'
Rename QSickRage/SickRage to QSickRage/old_SickRage
from QSickRage/ run 'git clone https://github.com/SickRage/SickRage.git'
Once clone is complete, create folders SickRage/CONFIG and SickRage/DATAS
put backed up files in their respective locations
run the following from the QSickRage/SickRage folder (as detailed by @OmgImAlexis ):

git remote set-url origin https://github.com/SickRage/SickRage.git
git fetch origin
git reset --hard origin/master

modify the sickbeard.conf file if required (mine needed to be changed, to match the config.ini)
Then I had to follow the solution at #6 (sslverify=false)

Once complete, run './QSickRage.sh start' from the QSickRage folder, and SickRage should start properly. `

Thanks for any help,
Ken

**Comment by miigotu** [comment]
fix your github login/password and it does away.

**Comment by kendog819** [comment]
My github login and password are correct both in the settings and in config.ini. Any other suggestion?

**Comment by miigotu** [comment]
re-enter them, ans save again.

**Comment by kendog819** [comment]
I tried doing all of that multiple times before ever posting here.

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/11387852/36999faa-92fd-11e5-8c89-e47556be254f.png)

Does that "Can't Reproduce" mean anything?

**Comment by miigotu** [comment]
Thats just the commit message.

**Comment by kendog819** [comment]
Not sure if these are all related to me being unable to connect to GitHub or not. Or if there is a larger issue.

![image](https://cloud.githubusercontent.com/assets/11353628/11388376/8155fbaa-9303-11e5-8d23-2c6063c1f67b.png)

Anything else I can try?

**Comment by miigotu** [comment]
stop SR and delete cache/sessions, if that doesnt fix it you have a network problem on that box.

**Comment by kendog819** [comment]
@miigotu  I assume you meant just the sessions folder inside of the cache folder, correct? Not the entire Cache folder?

![image](https://cloud.githubusercontent.com/assets/11353628/11399719/1dd795da-9357-11e5-97f1-ee6ad2eb78cb.png)

Deleting just the sessions folder didn't change anything  :-(

![image](https://cloud.githubusercontent.com/assets/11353628/11399751/51b79a26-9357-11e5-8e1f-23030138f99f.png)

**Comment by labrys** [comment]
Yes he meant just the sessions folder... if you delete the entire cache directory you would need to do a rescan from the mass updates to have it repopulate the show images.

**Comment by kendog819** [comment]
Ok, Yeah, I just deleted the sessions folder, but I already wasn't showing any images since doing this switch over :-/

**Comment by kendog819** [comment]
Restarting my NAS seems to have cleared up the network issue. Can't connect to GitHub now apparently. Thanks @miigotu

**Comment by miigotu** [comment]
@kendog819 the show images should repopulate at 3am, or if you force a full refresh of the show, if they dont might need to clear cache/images and force refresh on all shows.

**Comment by kendog819** [comment]
Got it, everything running smoothly now, Thanks again.
