### ISSUE TITLE
Multicore possible?

### ISSUE THREAD

**Issue by Smultie** [SickRage/sickrage-issues#77]
I'm running SickRage on my RPi2 and when there's stuff to do, it could take quite a lot of time, the RPi2 not being the the quickest tool in the shed. I also noticed that Python2.7/SickRage only uses 1 of the 4 cores. Is it possible to increase the amount of available cores to SR?

**Comment by miigotu** [comment]
This needs to go on [FeatHub](http://feathub.com/SickRage/SickRage)
