### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: '/volume1/Backups/sickrage-20151125142214.zip'

### ISSUE THREAD

**Issue by DonZalmrol** [SickRage/sickrage-issues#79]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@91e54c0364df98358a01436ee247a348775e88e1
Link to Log: https://gist.github.com/f1097f0f5655b4ac7df1
### ERROR
```
Thread-22 :: Zip creation error: "IOError(13, 'Permission denied')" 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
Check your permissions

**Comment by hansbogert** [comment]
Could the error indicate which path it couldn't write to? 
My whole SR root is under the right user, but I still see this.

**Comment by miigotu** [comment]
What is the output of these 2 commands?

`ls -l /usr/local/sickrage/var/config.ini`
`ls -ld /volume1/Backups`

**Comment by hansbogert** [comment]
As the issue OP was about linux, so is mine (whereas your paths imply OSX):

My datadir is in /etc/sickrage:

```
ps aux |grep -i rage
sickbea+ 11618  4.2  3.7 1421064 76264 ?       Sl   07:33   6:03 /usr/bin/python2.7 /opt/SickRage/SickBeard.py -q --daemon --nolaunch --pidfile=/var/run/sickrage/sickrage.pid --datadir=/etc/sickrage
root     16541  0.0  0.1  13216  2280 pts/0    S+   09:56   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -i rage
```
The permissions seem right:
```
ls -alh /etc/sickrage/{config.ini,backup}
-rw-r--r-- 1 sickbeard sickbeard  23K Mar 21 07:33 /etc/sickrage/config.ini

/etc/sickrage/backup:
total 78M
drwxr-xr-x 2 sickbeard sickbeard 4.0K Mar 21 09:52 .
drwxrwxrwx 5 sickbeard sickbeard 4.0K Mar 21 09:33 ..
-rw-rw-rw- 1 sickbeard sickbeard  39M Mar 21 07:33 sickrage-20160321073258.zip
-rw-rw-rw- 1 sickbeard sickbeard  39M Mar 21 09:52 sickrage-20160321095200.zip
```
In fact, it seems to actually create the zip files, is this a false positive? Either way, the actual update does not actually happen as the update fails and I keep the "running behind master" note.

Git version is:
```
git log |head
commit cc2812af9bd824653fbaf9b0fb49c48ce097a766
Merge: 9fcc5d6 e8b4e13
Author: miigotu <miigotu@gmail.com>
Date:   Wed Mar 16 06:19:29 2016 -0700

    Merge branch 'ettv-typo'

commit e8b4e1354ec04fcf3ec93029ec494ab471024c22
Author: miigotu <miigotu@gmail.com>
Date:   Wed Mar 16 06:18:50 2016 -0700
```
