### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: '/volume1/Backups/sickrage-20151125142204.zip'

### ISSUE THREAD

**Issue by DonZalmrol** [SickRage/sickrage-issues#80]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@91e54c0364df98358a01436ee247a348775e88e1
Link to Log: https://gist.github.com/7a74dd5151fa0ecfb63f
### ERROR
```
Thread-30 :: Zip creation error: "IOError(13, 'Permission denied')" 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment]
Chrvk your permissioms
