### ISSUE TITLE
Configuration of a new custom search provider is not working

### ISSUE THREAD

**Issue by DonZalmrol** [SickRage/sickrage-issues#81]
Dear support,

After switching repo's and starting from a clean installation. I've re-created all my settings back from scratch.

Most things are back like they've used to be with the exception of my custom search provider HDME.
But for some reason it's not accepting my RSS URL.

I keep getting the following error:
"Torrent link is not a valid torrent file: not a valid bencoded string"

The RSS URL I'm using is the following one:
https://hdme.eu/rss.php?feed=dl&cat=30,31,32,37,38,39&passkey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

The picture below is from the old SickRage(TV) that accepted it.
<img width="966" alt="2" src="https://cloud.githubusercontent.com/assets/15029801/11398783/2e2ceb02-9383-11e5-8125-5e83f345c654.PNG">

**Comment by DonZalmrol** [comment]
Added the log
[sickrage log.txt](https://github.com/SickRage/sickrage-issues/files/43901/sickrage.log.txt)

**Comment by labrys** [comment]
Unfortunately the log you posted doesn't show the error you mentioned, only the issue we discussed in IRC with your permissions.  Can you enable debug logs and then post a new log the next time this occurs?

**Comment by adaur** [comment]
Hello,

What's in /usr/local/sickrage/var/cache/custom_torrent.html?

Are you sure your perms issues isn't interfering with custom torrents?

**Comment by DonZalmrol** [comment]
This is what I see

<img width="465" alt="capture" src="https://cloud.githubusercontent.com/assets/15029801/11399873/4944019e-938a-11e5-8f7f-6ceed7bc2eae.PNG">

**Comment by DonZalmrol** [comment]
And when I open the custom_torrent.html file with Notepad++ it's encrypted.

But the firstline is plaintext and talks about HDME. Which is odd.

d8:announce68:http://hdme.eu/announce.php?passkey=xxxxxxxxxxxxxxxxxxxxxxx:created by37:ruTorrent (PHP Class - Adrien Gibrat)13:creation datei1448458303e4:infod6:lengthi11943388904e4:name57:Roger.Waters.the.Wall.2014.1080p.BluRay.x264.DTS-WiKi.mkv12:piece lengthi2097152e6:pieces113920:(:�u_\(�Ժ_��ӓZ�87d:-5of*?���u�u!��i�֙��c${F�r�hM�9kLaB|״�q\L�ɉ�;����8�]�:��/�M��q�nc�h�|�i�*=%�� /����	=��ü�X��Τ�-fL�7?�M_��G�H�\�c|c��l��1�ćw��t�-��zS���༷�x��Q<q@6�����fp��9D��7z^B�����BH��h��

**Comment by fernandog** [comment]
@miigotu ^^

**Comment by DonZalmrol** [comment]
@labrys I've contacted HDME and they are interested in talking with you guys.
Would it be possible to add HDME as a build in search provider?

Do you guys have a contact e-mail address for them to contact you on in private?

**Comment by miigotu** [comment]
@DonZalmrol I'm always interested in working closely with providers. As long as they have most things standardized it shouldnt be a problem making them a built in provider. miigotu@gmail

**Comment by fernandog** [comment]
@DonZalmrol with an API would be a lot easier to add as built-in provider

**Comment by DonZalmrol** [comment]
I've send this thread to the people of HDME. They will contact you guys :)

**Comment by labrys** [comment]
Thanks a lot @DonZalmrol

**Comment by DonZalmrol** [comment]
no prob, would be great to have HDME included in SR :)

**Comment by labrys** [comment]
@DonZalmrol Could you please ping the people at HDME again, as I don't believe we've heard from them yet.

**Comment by DonZalmrol** [comment]
You haven't heard from them yet? Odd, I'll send them a message.

**Comment by miigotu** [comment]
Closing until we hear from them, as this isnt an error/issue in sickrage but rather a feature request to include a provider.

**Comment by DonZalmrol** [comment]
Hi @miigotu, just received word from HDME and they've send you an e-mail :)

**Comment by miigotu** [comment]
yep, their RSS is broken =P.

So either their RSS gets fixed or I add a dedicated provider.

**Comment by miigotu** [comment]
Fixed in develop.

**Comment by DonZalmrol** [comment]
Haha thx :p
I'll test it when I get back home. 

So will they also become a custom provider or only RSS? :)

**Comment by miigotu** [comment]
RSS for now. but we have the account to create a built-in sometime, just not as much if a rush now

**Comment by DonZalmrol** [comment]
Ok, no rush.
But for me I still seem to have an issue with adding HDME :/

![capture](https://cloud.githubusercontent.com/assets/15029801/11767986/0a9d6ce4-a1bf-11e5-8f5f-6563fcae2552.PNG)
