### ISSUE TITLE
Problems with recognising status of symlinked files

### ISSUE THREAD

**Issue by ncksol** [SickRage/sickrage-issues#82]
On my seedbox I have the following setup:
1. SickRage is downloading torrent files into blackhole.
2. Deluge is watching folder and automatically picks torrents from there.
3. Filebot script is executed on each torrent once download is finished. This script creates symlinks of downloaded files in folder1.
4. Show in SickRage is setup so that folder1 is the "show location".

My problem is that SickRage never changes the status of an episode from Snatched to Downloaded if the folder contains just symlinks. It doesn't do it automatically, it doesn't do it if I press Rescan files.
It works just fine with hardlinks or actual files.

**Comment by medariox** [comment]
Why don't you just use hard links?

A symlink does not guarantee the existence of the linked file and is therefore unreliable.

**Comment by ncksol** [comment]
Hard link occupies space doesn't it? So on each downloaded Gb I will have 2 Gb used. And since it's a seedbox, space is quite limited.

**Comment by Zipties** [comment]
No, that would be too copies. A hard link is two identical pointers to the same file on the drive. No more space is used creating a hardlink.

**Comment by ncksol** [comment]
So I've just tried to create a hardlink and then check the size of a folder using du command. And it showed me that folder's size is the size of the file from which the link has been created.
When I create symbolic link the size of the folder is few bytes.

**Comment by Zipties** [comment]
Because its a hard link. The OS cant tell the difference between it and the original...because it pretty much is the original. If you delete either one you will notice the other still works and you didnt regain any space.

**Comment by ncksol** [comment]
Ok. It seems like du command doesn't calculate the size twice if I check the size of a folder that contains both original file and hardlink, but the File Manager does. Just need to make that the seedbox statistics is using the correct way to calculate free space.

Still it's weird that SickRage doesn't update the status correctly. It does update the size of the file from symlinks.

**Comment by Zipties** [comment]
it shouldn't effect over all free space calculations. The same block level space is being used either way.

**Comment by miigotu** [comment]
Hard link is just enough bytes to hold the file name and pointer in the MFT/inode =P
