### ISSUE TITLE
wiki install package for docker

### ISSUE THREAD

**Issue by sparklyballs** [SickRage/sickrage-issues#83]
https://github.com/SickRage/sickrage-issues/wiki/Sickrage-installation-packages#docker

your install packages link for docker points to needos docker that is using the echelon repo to pull from.

might i suggest 

https://github.com/linuxserver/docker-sickrage

(should add, i'm a member of linuxserver team)

**Comment by sparklyballs** [comment]
dockerhub link

https://hub.docker.com/r/linuxserver/sickrage/

**Comment by labrys** [comment]
fixed.. thanks for the heads up!
