### ISSUE TITLE
Changing CSS to LESS or SASS

### ISSUE THREAD

**Issue by OmgImAlexis** [SickRage/sickrage-issues#85]
I'm thinking it'd be a good time to switch from standard CSS to something like LESS or SASS since the new Bootstrap relies on it and it'd mean we can get grunt to build the CSS and add things like browser dependant CSS so we don't have to maintain it ourselves.

Obviously this would mean grunt would be needed for the CSS and Javascript but I honestly think it'd be for the best.

@SickRage/moderators @SickRage/collaborators

**Comment by MGaetan89** [comment]
I like and support your idea.
(why locking this? Any feedback is welcome I guess, not only from the teams).

**Comment by OmgImAlexis** [comment]
A few times I've had people come into issues like this and try telling us that we're doing it wrong or that one of their issues is related to us switching software so I figured this would be easier.

**Comment by alisonatwork** [comment]
I also very much want this to happen. I think it will make the styles much easier to reason about, and it will encourage more contributions.

Two small opinions on this.

1. I would prefer LESS over SASS for the sole reason that LESS does not require developers to install anything new just to develop the software (i.e. Ruby).
2. I think we should strongly consider a dev/watch mode for both JS and CSS, so that we don't need developers to manually recompile every time they want to change a line of code.

**Comment by OmgImAlexis** [comment]
@alisonatwork the main reason I added LESS and SASS to the discussion is I rather LESS over SASS but Bootstrap v4 uses SASS and since we rely on it for a lot of things it'd probably be better to just use that.

I can add in a Grunt script to watch the Javascript and CSS/LESS/SASS files but they'll still need the whole Grunt setup working with bower, node, etc.
These two Grunt modules can build [SASS](https://github.com/gruntjs/grunt-contrib-sass) and [LESS](https://github.com/gruntjs/grunt-contrib-less) without any other dependencies.

**Comment by miigotu** [comment]
From what I read the sass site says you need ruby either way (maybe that is inaccurate), but I will say sass looks nicer. Less seems simpler to implement and develop with.

You guys are hell bent on pushing us further into node dependancy I see, lol

**Comment by alisonatwork** [comment]
Ahh, that is unfortunate (Bootstrap pushing SASS). I guess if we are heavily on the Bootstrap train we should go with whatever is considered best practice there. I don't know enough about the current state of Bootstrap/JQuery to provide insight there (my last couple jobs were LESS/React/Angular).

Whatever technology we go with I am sure will be fine as long as we can detail in contributing doc how to get started with it from a blank OS install. I am happy to help there; there are a few steps around bootstrapping (heh) the JS environment I have been meaning to add anyway.

**Comment by OmgImAlexis** [comment]
@miigotu I just like how node handles everything cleanly. Also pretty sure there's no "web" "building" tools for Python that work this easily. :stuck_out_tongue: 

@alisonatwork Sounds good, I mean if it comes down to it we can always find a way to import the LESS into SASS or build it into CSS and then copy it to the top of the SASS file.

**Comment by Amadeus-** [comment]
I'm honestly not familiar with what the change entails (I'm not familiar with SASS or LESS); however, if/when the migration starts, I would suggest keeping it separate from both the current master *and* develop branches until it's fully tested and ready to release...whether that takes weeks or months.    That's my only input -- I trust everyone else to decide what is best. :)

**Comment by OmgImAlexis** [comment]
Added SASS support: https://github.com/SickRage/SickRage/pull/302

**Comment by OmgImAlexis** [comment]
We still need to convert our CSS to SASS but for now at least we've added support for it.

**Comment by labrys** [comment]
Speaking of which, the light theme needs some TLC, white on white is fairly ugly.

**Comment by OmgImAlexis** [comment]
Apart from Bootstrap v4 using SASS that's the other main reason for the switch. Instead of having sections where colours may not be updated/fixed everything will be defined at the top of the file in variables and then when changing things it can all be done in a single location that'll effect the other sections of the file.

I hope that makes sense. I was actually going to jump on IRC and explain it all but freenode is still down.

**Comment by labrys** [comment]
if you change freenode to e.g. adams.freenode.irc thats currently up

**Comment by adaur** [comment]
Or we have gitter ;)

**Comment by miigotu** [comment]
@adaur we tried gitter and shot it down because it sucks ass
