### ISSUE TITLE
Smaller but preferred files are skipped by postprocess

### ISSUE THREAD

**Issue by pven** [SickRage/sickrage-issues#86]
In the past I preferred 1080p for my series, but since some days I changed this to 720p. Downloading goes fine, but postprocessing does not. When a preferred 720p file has been downloaded, it won't be postprocessed succesfully if a bigger non-preferred file is already in the final directory. Right now I fix this by deleting the non-preferred file and start the postprocess.

Can this be automated?

**Comment by pven** [comment]
https://github.com/SickRage/sickrage-issues/issues/8

**Comment by miigotu** [comment]
sorry, working on something was a little slow on referencing the other issue number =P
