### ISSUE TITLE
Broken API command and API builder

### ISSUE THREAD

**Issue by MGaetan89** [SickRage/sickrage-issues#87]
Since today's update, the API Builder can not be accessed:

```
Error !

KeyError: 'allowedValues'

<div id="content"> <div class="panel-group" id="commands_list"> % for command in sorted(commands): <% command_id = command.replace('.', '-') help = commands[command]((), {'help': 1}).run() %> <div class="panel panel-default"> <div class="panel-heading">
/volume1/@appstore/sickrage/var/SickRage/sickbeard/webapi.py, line 308:
if paramDict[paramName]["allowedValues"]:
/usr/local/sickrage/var/SickRage/gui/slick/views/apiBuilder.mako, line 116:
<%
/volume1/@appstore/sickrage/var/SickRage/lib/mako/runtime.py, line 883:
callable_(context, *args, **kwargs)
```

And the `shows` command does not return anything.

**Comment by fernandog** [comment]
@labrys

**Comment by eucalyptus30** [comment]
I've the same problem.
http://upload.dinhosting.fr/q/J/6/Capturedn_crande2015-11-26193248.png

**Comment by Thraxis** [comment]
@eucalyptus30 the API commands are working for me, but yes the API Builder does throw the above error.

Using:
 SR Version:	BRANCH: (master) / COMMIT: (df074006606f9185acb8bf07098dc545f2357b26) 

http(s)://sickrageurl:8081/api/{API_KEY}/?cmd=shows
Returns the list of shows 

http(s)://sickrageurl:8081/apibuilder/
throws the allowedValues error

**Comment by eucalyptus30** [comment]
i've : <b> BRANCH: (master) / COMMIT: (df074006606f9185acb8bf07098dc545f2357b26) </b>

api shows is empty and yet in the home page : http://upload.dinhosting.fr/4/n/p/Capturedn_crande2015-11-26205427.png

i don't have any error... i don't understand. :-(

**Comment by Thraxis** [comment]
@labrys 

In a recent commit:
Lines 333-387  allowedValues was changed to allowed_values
Lines 431-449  allowedValues was changed to allowed_values

reverting those changes to allowedValues fixes the apiBuilder

**Comment by MGaetan89** [comment]
Or change `allowedValues` everywhere`.

**Comment by eucalyptus30** [comment]
api shows command is not fixed for me.

I've just tested with the last master and last develop branch.
i've with both an empty result for shows api cmd. http://upload.dinhosting.fr/q/J/6/Capturedn_crande2015-11-26193248.png

tested with : <b>BRANCH: (develop) / COMMIT: (2c0d11bb05071eef5bbd2e415a66cdf9e5053701) </b>
and <b>BRANCH: (master) / COMMIT: (df074006606f9185acb8bf07098dc545f2357b26) </b>

On <b>Debian Jessie</b> with <b>2.7.9</b>

**Comment by OmgImAlexis** [comment]
@MGaetan89 keep in mind a lot of the js was changed to fix jshint warnings so that may have caused some of it to break.

**Comment by Thraxis** [comment]
@eucalyptus30 Screen shots like that don't tell the whole picture, a debug log would be a bit more informative to show what may be happening behind the scenes on your system.  Your issue is also seperate from Mgaetan89's reported issue which was that the apiBuilder page was broken and would not display.  For clarity's sake you should post your problem as a new issue.

**Comment by MGaetan89** [comment]
JS doesn't have any impact on the execution of the API command.

**Comment by labrys** [comment]
@eucalyptus30 The issue raised here was fixed (I missed a couple variables during a rename - forgot to search strings for it).  It looks like what you have is a separate issue. If you could please open a new issue with a debug log, it would be much appreciated.

**Comment by MGaetan89** [comment]
I also mentioned @eucalyptus30 issue in my original message.
But I admit I did not think to add the logs. I'll add them later if no one does before me.

**Comment by labrys** [comment]
@eucalyptus30 @MGaetan89 is this still an issue after the fix?  I'm not getting any errors on any of the routes on the api builder.

**Comment by eucalyptus30** [comment]
@labrys 

I've done the tests again.

### With BRANCH: (master) / COMMIT: (df074006606f9185acb8bf07098dc545f2357b26) 
I added one show (Screenshot : http://upload.dinhosting.fr/C/E/P/Capturedn_crande2015-11-27141150.png )

The API cdm (/api/[KEY]/?cmd=shows) has this result: 
```
{"data": {}, "message": "", "result": "success"}
```

Le log result is 
```
2015-11-27 14:07:25 DEBUG    TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2015-11-27 14:07:25 DEBUG    TORNADO :: API :: all args: '()'
2015-11-27 14:07:25 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'shows'}'
2015-11-27 14:07:25 DEBUG    TORNADO :: API :: shows: cur_kwargs {}
```
Full log : https://dl.dropboxusercontent.com/u/27751092/master.log

Same test with develop
### With 	BRANCH: (develop) / COMMIT: (820eecf643fa8a0c45175ea5d96bd40aee6aaf80) 

The API cdm (/api/[KEY]/?cmd=shows) has this result: 
```
{"data": {}, "message": "", "result": "success"}
```
Le log result is 
```
2015-11-27 14:09:49 DEBUG    TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2015-11-27 14:09:49 DEBUG    TORNADO :: API :: all args: '()'
2015-11-27 14:09:49 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'shows'}'
2015-11-27 14:09:49 DEBUG    TORNADO :: API :: shows: cur_kwargs {}
```

Full log : https://dl.dropboxusercontent.com/u/27751092/develop.log

**Comment by labrys** [comment]
It looks like it defaults to paused = 0, so its returning the list of paused shows, of which you have none.  Obviously if that's the case then this should be changed to default to 1 since it's more likely that someone has not requested a list of paused shows, but all shows.

**Comment by MGaetan89** [comment]
The behaviour should be:
- if paused=0, return the list of not paused show
- if paused=1, return the list of paused show
- if paused is missing, return all shows

**Comment by labrys** [comment]
looks like it does the opposite atm
