### ISSUE TITLE
Better Schema indexes for faster query response

### ISSUE THREAD

**Issue by weevis** [SickRage/sickrage-issues#88]
There are indexes on some columns on some tables - but basically, if you use a column in a 'where' clause, it benefits being indexed (if the column is indexable or makes sense to be indexable) to improve query performance across the board.

Cache tables, history tables, scene exception tables - if had indexes would improve lookup performance here a great deal.

Even in tv_shows table, if you are using airdate in a where, indexing it makes sense - indexes will improve query response time drastically, at the cost of using more memory to keep these indexes around.

**Comment by OmgImAlexis** [comment]
Increasing the minimum amount of memory used probably isn't the best idea since a lot of users use SickRage on embedded NAS devices and raspberry pis. We might look at adding an option to enable more indexes, for now I'd suggest you add it to [feathub](http://feathub.com/SickRage/SickRage).
