### ISSUE TITLE
Post processing file I downloaded

### ISSUE THREAD

**Issue by veribaka** [SickRage/sickrage-issues#89]
So sickrage added a torrent without seeders (or at least there were no seeders for a few hours). I added a different torrent for the same episode and deleted the one that SR added. As a result, SR now refuses to PP the new episode, saying I haven't added this show to SR. The filename is exactly the same as the others too, since it's the same release group (HorribleSubs).

https://gist.github.com/veribaka/5f649d9d313a9abc4ee4

Should I just archive it and symlink it myself?

**Comment by miigotu** [comment]
You need to name it like it would be if it were downloaded by SR, before PP. aka that one is at least missing fansub group. Otherwise it doesnt match the anime regexes

**Comment by veribaka** [comment]
Crap, how did I miss that :/
Sorry to waste your time. 

Shouldn't PP be able to see that it's the same show though? Or BECAUSE it's an anime, the fansub group in the name must match?

**Comment by miigotu** [comment]
It has to be able to match a regex, this means it must be a scene name, aka how it came from the provider...

**Comment by veribaka** [comment]
Ok, my bad. Again, sorry for wasting your time.

Thanks for all the hard work, loving this service on my Cubie!

**Comment by miigotu** [comment]
Np, glad you appreciate it as much as we do!
