### ISSUE TITLE
Unable to retrieve 'news' when using proxy.

### ISSUE THREAD

**Issue by Tragalix** [SickRage/sickrage-issues#9]
Branch: Master
Commit hash: 3823a6846b558a03eba0f3f29aadb89f9d68a1d2

I've just migrated over to your new repository and found that i'm receiving the following error whenever Sickrage checks for new 'news'...

2015-11-18 19:20:31 DEBUG    Thread-17 :: check_for_new_news: Checking GitHub for latest news.
2015-11-18 19:20:31 WARNING  Thread-17 :: check_for_new_news: Could not load news from repo.

...I narrowed it down to my proxy settings which have prior to the migration worked just fine. If I blank out the proxy host setting in Sickrage the news loads up fine, add the proxy back in and I once again receive the above error. I am able to manually visit the news url http://sickrage.github.io/sickrage-news/news.md (which I located in __init__.py)in my browser via the same proxy just fine so it's not that the proxy cannot connect. Help :(

**Comment by medariox** [comment]
Can you please post a debug log with the error?

**Comment by adaur** [comment]
Then it's normal, you have to update git or it will update from the old repo.

**Comment by Tragalix** [comment]
@adaur Maybe I didn't explain clearly enough or i'm misunderstanding. The package I downloaded and ran was from this repo, The only remnants of the old one are the config and db files that I was under the assumption were okay to copy over in order to keep setting and such.

**Comment by adaur** [comment]
The package is a thing, the git command is another. If you installed the old files using git clone, uploading new files won't solve anything.

Moreover, in the config.ini, there should be a link to the old repo ;)
