### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by BenjV** [SickRage/sickrage-issues#92]
BRANCH: (master) / COMMIT: (6cdb5420378f7ae944e087cc1e4272fccdb7fc41) 
I run on a Synology Nas.

Every time I do an update I get this message and the update fails

```
2015-11-27 16:19:23 Thread-21 :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/master: Permission denied
error: Cannot update the ref 'refs/remotes/origin/master'.
From https://github.com/SickRage/SickRage
 ! 6cdb542..df07400  master     -> origin/master  (unable to update local ref)
error: Unable to append to .git/logs/refs/remotes/origin/develop: Permission denied
error: Cannot update the ref 'refs/remotes/origin/develop'.
 ! 96997d3..3b4bfad  develop    -> origin/develop  (unable to update local ref)
```

**Comment by duramato** [comment]
```error: Unable to append to .git/logs/refs/remotes/origin/develop: Permission denied``` check your permissions

**Comment by BenjV** [comment]
I think my permissions are not the problem.
It always worked but after the change from the old Sickrage to here I have this problem.

But I will check again.

**Comment by adaur** [comment]
It is certain that it won't update if it can't edit .git/ files

**Comment by BenjV** [comment]
I am sorry to have bothered you with this.
You pointed me in the right direction, it was an permission problem.

I did the change to this github with the git commands as root and as a result some files are now owned by root and not by the user 'sickrage'.
I corrected this and everything is working fine again.

Thanks for the help.
