### ISSUE TITLE
[APP SUBMITTED]: max() arg is an empty sequence

### ISSUE THREAD

**Issue by crow50** [SickRage/sickrage-issues#93]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@df074006606f9185acb8bf07098dc545f2357b26
Link to Log: https://gist.github.com/d001afce50a4d25f52c1
### ERROR
```
Thread-35 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 264, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 1262, in displayShow
    curEpCat = showObj.getOverview(int(curResult["status"] or -1))
  File "C:\SickRage\sickbeard\tv.py", line 1310, in getOverview
    if curQuality != Quality.UNKNOWN and curQuality > max(anyQualities):
ValueError: max() arg is an empty sequence

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by crow50** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@df074006606f9185acb8bf07098dc545f2357b26
Link to Log: https://gist.github.com/b7ea8d6489aaa40adb82
### ERROR
```
Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 264, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 1262, in displayShow
    curEpCat = showObj.getOverview(int(curResult["status"] or -1))
  File "C:\SickRage\sickbeard\tv.py", line 1310, in getOverview
    if curQuality != Quality.UNKNOWN and curQuality > max(anyQualities):
ValueError: max() arg is an empty sequence

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by phaseburn** [comment]
### INFO
Python Version: **2.7.10 (default, Sep  7 2015, 13:51:49) [GCC 5.2.0]**
Operating System: **Linux-4.2.5-1-ARCH-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@df074006606f9185acb8bf07098dc545f2357b26
Link to Log: https://gist.github.com/7f92f381a6ee0240a74a
### ERROR
```
Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 264, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1262, in displayShow
    curEpCat = showObj.getOverview(int(curResult["status"] or -1))
  File "/opt/sickrage/sickbeard/tv.py", line 1310, in getOverview
    if curQuality != Quality.UNKNOWN and curQuality > max(anyQualities):
ValueError: max() arg is an empty sequence

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
