### ISSUE TITLE
Post Processing Skips Replacing With Smaller File

### ISSUE THREAD

**Issue by ulrick65** [SickRage/sickrage-issues#97]
I could not find the forum...so I figured I would post this here and see.

I use nzbtomedia for postprocessing between SR and SABNZBD. I am updating shows with a custom quality so that my HDTV episodes will be replaced with WEBDL or BLURAY versions.

The problem I have is if it downloads a WEBDL version that is smaller than the HDTV version I currently have, it fails post processing. This makes sense...because it is not safe to replace the file as we would expect it to be bigger. The ones that this happens to are ones where the sound is 2.0 rather than DTS, etc...so the file size is definitely smaller. I don't want the 2.0 ones for sure (I wish we had a good way to dictate that to SR...but that a different story) so this is a good thing.

The problem is that it does not flag that download as failed and there I am just stuck with a downloaded file, SR sitting there with a status of "Snatched WEBDL720p" and no way for me to easily get out of it. If I try to manually snatch again, it does not give me the option of flagging the currently snatched one as failed (which would be the fix). So if I snatch it again, it simply asks if I want to look for the same quality (which I do, because I want WEBDL720p) and then goes out and simply grabs the same one again and craps out again.  

Also it continues to redownload the same files everyday...until I manually intervene and change the status I guess? 

Thoughts? Is there something that can be done differently?

Thanks.

**Comment by miigotu** [comment]
This is a duplicate, and was fixed in develop. I have just released to master so you shouldnt have this issue.

**Comment by ulrick65** [comment]
Can you point me to the duplicate so I can read up on it?  What was the fix?

**Comment by labrys** [comment]
@ulrick65 #8 was the original.
